/**
 * Base de Dados Oficial F1 Academy MBJ 2026
 * Extraído diretamente do PDF oficial do editor: "Banco_F1_Academy_MBJ_2026-a1f69.pdf"
 *
 * Regras editoriais estritas:
 * - 17 pilotas fixas (sem wild card rotativo).
 * - 45 campos completos com proveniência e regras V/P/O.
 * - Escala 0-100, sem overall (R03: não armazenar nem exibir média universal).
 * - Visibilidade V/P/O: V pública; P estimada/faixa; O oculta do motor.
 * - Valores monetários: USD anuais no documento (proposta de negociação F1/desenvolvimento).
 * - Status LIVRE no mercado F1 (não exclui vínculo com equipe F1 Academy).
 * - Adaptação F1 com meta 80 e taxas por adaptabilidade (R08).
 * - Traços TR09 (Aprendizado em simulador) e TR10 (Preparação de volta) com status 'Não revelado'.
 */

export interface F1AcademyPilotMBJ {
  id: string
  name: string
  birthDate: string
  age: number
  nationalities: string[]
  academyNumber: number
  operatingTeam: string
  supporterBrand: string
  f1MarketStatus: 'LIVRE'
  sourceUrl: string

  // Performance P (14 atributos exatos do motor)
  speed: number // Velocidade
  qualifying: number // Classificação
  racePace: number // Ritmo corrida
  consistency: number // Consistência
  start: number // Largada
  overtake: number // Ultrapassagem
  defense: number // Defesa
  rain: number // Chuva
  tires: number // Pneus
  energy: number // Energia
  feedback: number // Feedback
  pressure: number // Pressão
  concentration: number // Concentração
  resilience: number // Resiliência

  // Personalidade P/O/V
  aggressiveness: number // P
  ambition: number // P
  loyalty: number // P
  professionalism: number // P
  temperament: number // O (oculto, apenas simulação)
  reputation: number // V
  globalPopularity: number // V
  localPopularity: number // V
  localMarket: string // V

  // Evolução O (14 tetos de habilidade + parâmetros de carreira)
  learningRateSkill: number // Aprendizagem O
  ceilings: {
    speed: number
    qualifying: number
    racePace: number
    consistency: number
    start: number
    overtake: number
    defense: number
    rain: number
    tires: number
    energy: number
    feedback: number
    pressure: number
    concentration: number
    resilience: number
  }
  declineStart: number // Início de declínio em anos
  retirementHorizon: number // Horizonte aposentadoria em anos
  annualLosses: {
    speed: number
    qualifying: number
    racePace: number
    consistency: number
    start: number
    overtake: number
    defense: number
    rain: number
    tires: number
    energy: number
    feedback: number
    pressure: number
    concentration: number
    resilience: number
  }

  // Estado atual P
  morale: number // 65
  confidence: number // 50
  condition: number // 100
  stress: number // 20
  adaptability: number
  adaptationF1: number
  carAdaptation: number // 0
  teamAdaptation: number // 0
  combinedAdaptation: string // "Sem contexto"
  adaptationLearningRate: string // ex: "10,6%"
  stepsToF1_80: number // etapas até atingir F1=80
  contextNote: string // "Carro/equipe ainda não definidos"

  // Finanças
  referenceAnnualUsd: number // P (em USD)
  minimumAnnualUsd: number // O (em USD)
  negotiationWeights: {
    money: number
    project: number
    prestige: number
    stability: number
    role: number
    relationship: number
  }
  acceptsReserve: boolean // Sim
  acceptedRoles: string[] // ['LIDER', 'IGUAL', 'APOIO']
  activeCommercialRevenueUsd: number // 0
  valuePurpose: string // "Bolsa anual de desenvolvimento"

  // Biografia V
  referenceCategory: string
  biography: string
  bioSourceUrl: string
  coverage: string // "Resumo; não é histórico completo de resultados"

  // Traços
  traits: Array<{
    code: 'TR09' | 'TR10'
    name: string
    revealedStatus: string // 'Não revelado'
    nature: string // 'DESIGN editorial'
    startDate: string // '2026-03-01'
  }>
}

export const OFFICIAL_F1_ACADEMY_MBJ_2026: F1AcademyPilotMBJ[] = [
  {
    id: 'pil_0030',
    name: 'Nina Gademan',
    birthDate: '2003-08-30',
    age: 22,
    nationalities: ['NL'],
    academyNumber: 3,
    operatingTeam: 'MP Motorsport',
    supporterBrand: 'Alpine',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 60,
    qualifying: 61,
    racePace: 59,
    consistency: 58,
    start: 59,
    overtake: 60,
    defense: 58,
    rain: 60,
    tires: 56,
    energy: 56,
    feedback: 53,
    pressure: 56,
    concentration: 56,
    resilience: 68,
    aggressiveness: 44,
    ambition: 74,
    loyalty: 64,
    professionalism: 85,
    temperament: 31,
    reputation: 34,
    globalPopularity: 24,
    localPopularity: 46,
    localMarket: 'NL',
    learningRateSkill: 85,
    ceilings: {
      speed: 84,
      qualifying: 89,
      racePace: 84,
      consistency: 85,
      start: 85,
      overtake: 83,
      defense: 85,
      rain: 84,
      tires: 89,
      energy: 86,
      feedback: 80,
      pressure: 76,
      concentration: 73,
      resilience: 89,
    },
    declineStart: 35,
    retirementHorizon: 20,
    annualLosses: {
      speed: 0.9,
      qualifying: 0.9,
      racePace: 0.2,
      consistency: 0.2,
      start: 0.9,
      overtake: 0.2,
      defense: 0.2,
      rain: 0.2,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.2,
      concentration: 0.2,
      resilience: 0.2,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 83,
    adaptationF1: 25,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,6%',
    stepsToF1_80: 12,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 150000,
    minimumAnnualUsd: 90000,
    negotiationWeights: {
      money: 0.237,
      project: 0.237,
      prestige: 0.167,
      stability: 0.096,
      role: 0.079,
      relationship: 0.184,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Disputou a F4 britânica antes de avançar na F1 Academy. Terminou a temporada de 2025 da categoria em sexto lugar.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Nina_Gademan',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0011',
    name: 'Megan Bruce',
    birthDate: '2004-08-02',
    age: 21,
    nationalities: ['GB'],
    academyNumber: 4,
    operatingTeam: 'Campos Racing',
    supporterBrand: 'TAG Heuer',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 52,
    qualifying: 51,
    racePace: 54,
    consistency: 53,
    start: 48,
    overtake: 54,
    defense: 52,
    rain: 52,
    tires: 54,
    energy: 51,
    feedback: 49,
    pressure: 50,
    concentration: 52,
    resilience: 67,
    aggressiveness: 67,
    ambition: 67,
    loyalty: 74,
    professionalism: 75,
    temperament: 41,
    reputation: 23,
    globalPopularity: 13,
    localPopularity: 35,
    localMarket: 'GB',
    learningRateSkill: 77,
    ceilings: {
      speed: 80,
      qualifying: 76,
      racePace: 76,
      consistency: 84,
      start: 71,
      overtake: 81,
      defense: 76,
      rain: 80,
      tires: 84,
      energy: 78,
      feedback: 80,
      pressure: 67,
      concentration: 73,
      resilience: 85,
    },
    declineStart: 36,
    retirementHorizon: 20,
    annualLosses: {
      speed: 2.0,
      qualifying: 2.0,
      racePace: 0.6,
      consistency: 0.6,
      start: 2.0,
      overtake: 0.6,
      defense: 0.6,
      rain: 0.6,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.6,
      concentration: 0.6,
      resilience: 0.6,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 72,
    adaptationF1: 24,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '4,3%',
    stepsToF1_80: 31,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 80000,
    minimumAnnualUsd: 48000,
    negotiationWeights: {
      money: 0.155,
      project: 0.255,
      prestige: 0.182,
      stability: 0.109,
      role: 0.1,
      relationship: 0.2,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Iniciou nas competições da Caterham e migrou para a GB4 em 2024. Participou da F1 Academy em 2025.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Megan_Bruce',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0026',
    name: 'Emma Felbermayr',
    birthDate: '2007-01-27',
    age: 19,
    nationalities: ['AT'],
    academyNumber: 5,
    operatingTeam: 'Rodin Motorsport',
    supporterBrand: 'Audi',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 58,
    qualifying: 57,
    racePace: 57,
    consistency: 54,
    start: 57,
    overtake: 54,
    defense: 50,
    rain: 53,
    tires: 54,
    energy: 53,
    feedback: 47,
    pressure: 57,
    concentration: 56,
    resilience: 76,
    aggressiveness: 61,
    ambition: 70,
    loyalty: 71,
    professionalism: 84,
    temperament: 38,
    reputation: 31,
    globalPopularity: 21,
    localPopularity: 43,
    localMarket: 'AT',
    learningRateSkill: 89,
    ceilings: {
      speed: 81,
      qualifying: 84,
      racePace: 81,
      consistency: 87,
      start: 82,
      overtake: 76,
      defense: 76,
      rain: 76,
      tires: 86,
      energy: 82,
      feedback: 80,
      pressure: 76,
      concentration: 72,
      resilience: 96,
    },
    declineStart: 39,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.5,
      qualifying: 1.5,
      racePace: 0.1,
      consistency: 0.1,
      start: 1.5,
      overtake: 0.1,
      defense: 0.1,
      rain: 0.1,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.1,
      concentration: 0.1,
      resilience: 0.1,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 82,
    adaptationF1: 21,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,6%',
    stepsToF1_80: 13,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 120000,
    minimumAnnualUsd: 72000,
    negotiationWeights: {
      money: 0.228,
      project: 0.202,
      prestige: 0.123,
      stability: 0.202,
      role: 0.096,
      relationship: 0.149,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Chegou à F1 Academy em 2025 com a Rodin Motorsport. Encerrou sua primeira temporada em décimo lugar.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Emma_Felbermayr',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0059',
    name: 'Mathilda Paatz',
    birthDate: '2008-08-01',
    age: 17,
    nationalities: ['DE'],
    academyNumber: 8,
    operatingTeam: 'PREMA Racing',
    supporterBrand: 'Aston Martin',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 52,
    qualifying: 54,
    racePace: 51,
    consistency: 52,
    start: 55,
    overtake: 54,
    defense: 54,
    rain: 49,
    tires: 49,
    energy: 51,
    feedback: 44,
    pressure: 52,
    concentration: 51,
    resilience: 75,
    aggressiveness: 61,
    ambition: 67,
    loyalty: 52,
    professionalism: 87,
    temperament: 50,
    reputation: 23,
    globalPopularity: 13,
    localPopularity: 35,
    localMarket: 'DE',
    learningRateSkill: 90,
    ceilings: {
      speed: 78,
      qualifying: 77,
      racePace: 78,
      consistency: 81,
      start: 83,
      overtake: 79,
      defense: 76,
      rain: 75,
      tires: 77,
      energy: 83,
      feedback: 73,
      pressure: 74,
      concentration: 70,
      resilience: 91,
    },
    declineStart: 36,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.8,
      qualifying: 1.8,
      racePace: 0.4,
      consistency: 0.4,
      start: 1.8,
      overtake: 0.4,
      defense: 0.4,
      rain: 0.4,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.4,
      concentration: 0.4,
      resilience: 0.4,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 80,
    adaptationF1: 26,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,4%',
    stepsToF1_80: 12,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 80000,
    minimumAnnualUsd: 48000,
    negotiationWeights: {
      money: 0.238,
      project: 0.23,
      prestige: 0.115,
      stability: 0.098,
      role: 0.139,
      relationship: 0.18,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Fórmula 4',
    biography:
      'Sua trajetória de formação inclui a F4 francesa e a F4 da Europa Central. Avança para a F1 Academy em 2026.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Mathilda_Paatz',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0080',
    name: 'Payton Westcott',
    birthDate: '2009-03-20',
    age: 16,
    nationalities: ['US'],
    academyNumber: 9,
    operatingTeam: 'PREMA Racing',
    supporterBrand: 'Mercedes',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 51,
    qualifying: 53,
    racePace: 49,
    consistency: 49,
    start: 50,
    overtake: 46,
    defense: 45,
    rain: 45,
    tires: 47,
    energy: 49,
    feedback: 40,
    pressure: 52,
    concentration: 49,
    resilience: 72,
    aggressiveness: 46,
    ambition: 76,
    loyalty: 54,
    professionalism: 87,
    temperament: 52,
    reputation: 21,
    globalPopularity: 11,
    localPopularity: 33,
    localMarket: 'US',
    learningRateSkill: 92,
    ceilings: {
      speed: 77,
      qualifying: 76,
      racePace: 76,
      consistency: 78,
      start: 78,
      overtake: 71,
      defense: 67,
      rain: 71,
      tires: 75,
      energy: 81,
      feedback: 69,
      pressure: 74,
      concentration: 68,
      resilience: 88,
    },
    declineStart: 37,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.1,
      qualifying: 1.1,
      racePace: 0.4,
      consistency: 0.4,
      start: 1.1,
      overtake: 0.4,
      defense: 0.4,
      rain: 0.4,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.4,
      concentration: 0.4,
      resilience: 0.4,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 84,
    adaptationF1: 20,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,7%',
    stepsToF1_80: 13,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 70000,
    minimumAnnualUsd: 42000,
    negotiationWeights: {
      money: 0.264,
      project: 0.191,
      prestige: 0.091,
      stability: 0.191,
      role: 0.127,
      relationship: 0.136,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Fórmula 4',
    biography:
      'Sua formação começou no karting norte-americano. Progrediu para monopostos de base e integra o elenco proposto para desenvolvimento no cenário.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Payton_Westcott',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0045',
    name: 'Alba Hurup Larsen',
    birthDate: '2008-12-12',
    age: 17,
    nationalities: ['DK'],
    academyNumber: 12,
    operatingTeam: 'MP Motorsport',
    supporterBrand: 'Ferrari',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 59,
    qualifying: 60,
    racePace: 57,
    consistency: 57,
    start: 63,
    overtake: 55,
    defense: 54,
    rain: 55,
    tires: 55,
    energy: 57,
    feedback: 47,
    pressure: 52,
    concentration: 58,
    resilience: 77,
    aggressiveness: 71,
    ambition: 77,
    loyalty: 61,
    professionalism: 73,
    temperament: 59,
    reputation: 34,
    globalPopularity: 24,
    localPopularity: 46,
    localMarket: 'DK',
    learningRateSkill: 94,
    ceilings: {
      speed: 85,
      qualifying: 83,
      racePace: 84,
      consistency: 86,
      start: 91,
      overtake: 80,
      defense: 76,
      rain: 81,
      tires: 83,
      energy: 89,
      feedback: 76,
      pressure: 74,
      concentration: 77,
      resilience: 93,
    },
    declineStart: 38,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.8,
      qualifying: 1.8,
      racePace: 0.4,
      consistency: 0.4,
      start: 1.8,
      overtake: 0.4,
      defense: 0.4,
      rain: 0.4,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.4,
      concentration: 0.4,
      resilience: 0.4,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 88,
    adaptationF1: 22,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '19,3%',
    stepsToF1_80: 7,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 150000,
    minimumAnnualUsd: 90000,
    negotiationWeights: {
      money: 0.155,
      project: 0.227,
      prestige: 0.134,
      stability: 0.227,
      role: 0.093,
      relationship: 0.165,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Competiu na F4 e estreou na F1 Academy em 2025. Terminou essa primeira temporada em sétimo lugar.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Alba_Hurup_Larsen',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0007',
    name: 'Lisa Billard',
    birthDate: '2009-09-12',
    age: 16,
    nationalities: ['FR'],
    academyNumber: 14,
    operatingTeam: 'ART Grand Prix',
    supporterBrand: 'Gatorade',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 53,
    qualifying: 55,
    racePace: 51,
    consistency: 50,
    start: 51,
    overtake: 47,
    defense: 45,
    rain: 51,
    tires: 48,
    energy: 44,
    feedback: 43,
    pressure: 52,
    concentration: 53,
    resilience: 75,
    aggressiveness: 51,
    ambition: 87,
    loyalty: 50,
    professionalism: 74,
    temperament: 48,
    reputation: 24,
    globalPopularity: 14,
    localPopularity: 36,
    localMarket: 'FR',
    learningRateSkill: 91,
    ceilings: {
      speed: 80,
      qualifying: 79,
      racePace: 79,
      consistency: 80,
      start: 73,
      overtake: 73,
      defense: 68,
      rain: 78,
      tires: 77,
      energy: 77,
      feedback: 73,
      pressure: 68,
      concentration: 73,
      resilience: 92,
    },
    declineStart: 40,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.2,
      qualifying: 1.2,
      racePace: 0.5,
      consistency: 0.5,
      start: 1.2,
      overtake: 0.5,
      defense: 0.5,
      rain: 0.5,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.5,
      concentration: 0.5,
      resilience: 0.5,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 82,
    adaptationF1: 28,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,6%',
    stepsToF1_80: 12,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 80000,
    minimumAnnualUsd: 48000,
    negotiationWeights: {
      money: 0.145,
      project: 0.218,
      prestige: 0.136,
      stability: 0.218,
      role: 0.118,
      relationship: 0.164,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Fórmula 4',
    biography:
      'Iniciou a carreira em monopostos na F4 francesa. Participou da F1 Academy como convidada em 2025.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Lisa_Billard',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0027',
    name: 'Rafaela Ferreira',
    birthDate: '2005-04-18',
    age: 20,
    nationalities: ['BR'],
    academyNumber: 18,
    operatingTeam: 'Campos Racing',
    supporterBrand: 'Racing Bulls',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 55,
    qualifying: 56,
    racePace: 54,
    consistency: 54,
    start: 53,
    overtake: 52,
    defense: 51,
    rain: 55,
    tires: 52,
    energy: 53,
    feedback: 46,
    pressure: 49,
    concentration: 53,
    resilience: 61,
    aggressiveness: 65,
    ambition: 83,
    loyalty: 46,
    professionalism: 79,
    temperament: 44,
    reputation: 29,
    globalPopularity: 19,
    localPopularity: 41,
    localMarket: 'BR',
    learningRateSkill: 85,
    ceilings: {
      speed: 80,
      qualifying: 78,
      racePace: 80,
      consistency: 82,
      start: 80,
      overtake: 76,
      defense: 79,
      rain: 80,
      tires: 79,
      energy: 84,
      feedback: 74,
      pressure: 70,
      concentration: 71,
      resilience: 83,
    },
    declineStart: 36,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.0,
      qualifying: 1.0,
      racePace: 0.3,
      consistency: 0.3,
      start: 1.0,
      overtake: 0.3,
      defense: 0.3,
      rain: 0.3,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.3,
      concentration: 0.3,
      resilience: 0.3,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 79,
    adaptationF1: 22,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,3%',
    stepsToF1_80: 13,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 100000,
    minimumAnnualUsd: 60000,
    negotiationWeights: {
      money: 0.176,
      project: 0.235,
      prestige: 0.151,
      stability: 0.101,
      role: 0.151,
      relationship: 0.185,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Venceu na F4 brasileira e estreou na F1 Academy em 2025. Sua formação inclui temporadas de F4 e participação na Formula Winter Series.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Rafaela_Ferreira',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0032',
    name: 'Natalia Granada',
    birthDate: '2008-03-18',
    age: 17,
    nationalities: ['ES'],
    academyNumber: 19,
    operatingTeam: 'PREMA Racing',
    supporterBrand: 'SEPHORA',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 48,
    qualifying: 50,
    racePace: 46,
    consistency: 47,
    start: 52,
    overtake: 49,
    defense: 49,
    rain: 46,
    tires: 43,
    energy: 40,
    feedback: 38,
    pressure: 47,
    concentration: 47,
    resilience: 64,
    aggressiveness: 52,
    ambition: 76,
    loyalty: 45,
    professionalism: 75,
    temperament: 43,
    reputation: 18,
    globalPopularity: 8,
    localPopularity: 30,
    localMarket: 'ES',
    learningRateSkill: 92,
    ceilings: {
      speed: 76,
      qualifying: 75,
      racePace: 68,
      consistency: 78,
      start: 75,
      overtake: 76,
      defense: 73,
      rain: 74,
      tires: 73,
      energy: 67,
      feedback: 69,
      pressure: 64,
      concentration: 68,
      resilience: 82,
    },
    declineStart: 37,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.3,
      qualifying: 1.3,
      racePace: 0.6,
      consistency: 0.6,
      start: 1.3,
      overtake: 0.6,
      defense: 0.6,
      rain: 0.6,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.6,
      concentration: 0.6,
      resilience: 0.6,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 83,
    adaptationF1: 17,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,6%',
    stepsToF1_80: 13,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 60000,
    minimumAnnualUsd: 36000,
    negotiationWeights: {
      money: 0.173,
      project: 0.214,
      prestige: 0.163,
      stability: 0.214,
      role: 0.082,
      relationship: 0.153,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Karting',
    biography:
      'Construiu sua formação no karting. Representou as Iron Dames nessa modalidade antes da transição para monopostos.',
    bioSourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers/69/Natalia-Granada',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0050',
    name: 'Ella Lloyd',
    birthDate: '2005-07-20',
    age: 20,
    nationalities: ['GB'],
    academyNumber: 20,
    operatingTeam: 'Rodin Motorsport',
    supporterBrand: 'McLaren',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 61,
    qualifying: 60,
    racePace: 62,
    consistency: 60,
    start: 59,
    overtake: 65,
    defense: 62,
    rain: 61,
    tires: 58,
    energy: 56,
    feedback: 54,
    pressure: 60,
    concentration: 62,
    resilience: 80,
    aggressiveness: 58,
    ambition: 70,
    loyalty: 60,
    professionalism: 90,
    temperament: 58,
    reputation: 35,
    globalPopularity: 25,
    localPopularity: 47,
    localMarket: 'GB',
    learningRateSkill: 86,
    ceilings: {
      speed: 83,
      qualifying: 86,
      racePace: 85,
      consistency: 92,
      start: 83,
      overtake: 93,
      defense: 87,
      rain: 83,
      tires: 89,
      energy: 84,
      feedback: 86,
      pressure: 78,
      concentration: 84,
      resilience: 99,
    },
    declineStart: 39,
    retirementHorizon: 19,
    annualLosses: {
      speed: 2.1,
      qualifying: 2.1,
      racePace: 0.7,
      consistency: 0.7,
      start: 2.1,
      overtake: 0.7,
      defense: 0.7,
      rain: 0.7,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.7,
      concentration: 0.7,
      resilience: 0.7,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 84,
    adaptationF1: 27,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,7%',
    stepsToF1_80: 12,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 180000,
    minimumAnnualUsd: 108000,
    negotiationWeights: {
      money: 0.103,
      project: 0.29,
      prestige: 0.103,
      stability: 0.14,
      role: 0.131,
      relationship: 0.234,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Vice-campeã da Ginetta GT5 Challenge em 2023. Passou à F4 britânica e terminou a F1 Academy de 2025 em quarto lugar.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Ella_Lloyd',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0060',
    name: 'Alisha Palmowski',
    birthDate: '2006-09-21',
    age: 19,
    nationalities: ['GB'],
    academyNumber: 21,
    operatingTeam: 'Campos Racing',
    supporterBrand: 'Red Bull Racing',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 64,
    qualifying: 64,
    racePace: 63,
    consistency: 62,
    start: 62,
    overtake: 58,
    defense: 65,
    rain: 59,
    tires: 60,
    energy: 57,
    feedback: 52,
    pressure: 63,
    concentration: 66,
    resilience: 60,
    aggressiveness: 65,
    ambition: 80,
    loyalty: 58,
    professionalism: 82,
    temperament: 56,
    reputation: 38,
    globalPopularity: 28,
    localPopularity: 50,
    localMarket: 'GB',
    learningRateSkill: 92,
    ceilings: {
      speed: 92,
      qualifying: 89,
      racePace: 85,
      consistency: 93,
      start: 85,
      overtake: 85,
      defense: 89,
      rain: 87,
      tires: 90,
      energy: 84,
      feedback: 83,
      pressure: 80,
      concentration: 87,
      resilience: 78,
    },
    declineStart: 33,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.3,
      qualifying: 1.3,
      racePace: 0.6,
      consistency: 0.6,
      start: 1.3,
      overtake: 0.6,
      defense: 0.6,
      rain: 0.6,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.6,
      concentration: 0.6,
      resilience: 0.6,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 87,
    adaptationF1: 28,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '11,0%',
    stepsToF1_80: 12,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 200000,
    minimumAnnualUsd: 120000,
    negotiationWeights: {
      money: 0.214,
      project: 0.295,
      prestige: 0.161,
      stability: 0.152,
      role: 0.08,
      relationship: 0.098,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'F1 Academy',
    biography:
      'Vice-campeã da GB4 em 2024. Terminou a temporada de 2025 da F1 Academy em quinto lugar.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Alisha_Palmowski',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0135',
    name: 'Ella Stevens',
    birthDate: '2006-09-10',
    age: 19,
    nationalities: ['GB'],
    academyNumber: 28,
    operatingTeam: 'Rodin Motorsport',
    supporterBrand: 'McLaren Oxagon',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 54,
    qualifying: 56,
    racePace: 49,
    consistency: 50,
    start: 44,
    overtake: 46,
    defense: 46,
    rain: 53,
    tires: 44,
    energy: 40,
    feedback: 38,
    pressure: 45,
    concentration: 53,
    resilience: 79,
    aggressiveness: 68,
    ambition: 71,
    loyalty: 74,
    professionalism: 85,
    temperament: 41,
    reputation: 25,
    globalPopularity: 15,
    localPopularity: 37,
    localMarket: 'GB',
    learningRateSkill: 95,
    ceilings: {
      speed: 78,
      qualifying: 84,
      racePace: 74,
      consistency: 77,
      start: 70,
      overtake: 69,
      defense: 73,
      rain: 77,
      tires: 77,
      energy: 70,
      feedback: 65,
      pressure: 65,
      concentration: 70,
      resilience: 100,
    },
    declineStart: 40,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.6,
      qualifying: 1.6,
      racePace: 0.2,
      consistency: 0.2,
      start: 1.6,
      overtake: 0.2,
      defense: 0.2,
      rain: 0.2,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.2,
      concentration: 0.2,
      resilience: 0.2,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 88,
    adaptationF1: 12,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '19,3%',
    stepsToF1_80: 7,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 80000,
    minimumAnnualUsd: 48000,
    negotiationWeights: {
      money: 0.241,
      project: 0.214,
      prestige: 0.089,
      stability: 0.214,
      role: 0.08,
      relationship: 0.161,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Karting',
    biography:
      'Construiu sua trajetória no karting britânico. Em 2025 ainda competia no kart antes da transição para a F1 Academy.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Ella_Stevens_%28racing_driver%29',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0043',
    name: 'Esmee Kosterman',
    birthDate: '2005-04-16',
    age: 20,
    nationalities: ['NL'],
    academyNumber: 32,
    operatingTeam: 'MP Motorsport',
    supporterBrand: 'LEGO',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 51,
    qualifying: 49,
    racePace: 54,
    consistency: 54,
    start: 52,
    overtake: 50,
    defense: 49,
    rain: 51,
    tires: 54,
    energy: 52,
    feedback: 49,
    pressure: 56,
    concentration: 53,
    resilience: 81,
    aggressiveness: 63,
    ambition: 75,
    loyalty: 49,
    professionalism: 83,
    temperament: 47,
    reputation: 22,
    globalPopularity: 12,
    localPopularity: 34,
    localMarket: 'NL',
    learningRateSkill: 80,
    ceilings: {
      speed: 73,
      qualifying: 75,
      racePace: 77,
      consistency: 86,
      start: 76,
      overtake: 78,
      defense: 74,
      rain: 73,
      tires: 85,
      energy: 80,
      feedback: 81,
      pressure: 74,
      concentration: 75,
      resilience: 100,
    },
    declineStart: 36,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.4,
      qualifying: 1.4,
      racePace: 0.7,
      consistency: 0.7,
      start: 1.4,
      overtake: 0.7,
      defense: 0.7,
      rain: 0.7,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.7,
      concentration: 0.7,
      resilience: 0.7,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 73,
    adaptationF1: 28,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '4,3%',
    stepsToF1_80: 30,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 80000,
    minimumAnnualUsd: 48000,
    negotiationWeights: {
      money: 0.221,
      project: 0.248,
      prestige: 0.142,
      stability: 0.106,
      role: 0.088,
      relationship: 0.195,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Fórmula 4',
    biography:
      'Passou por competições de turismo antes dos monopostos. Seu histórico inclui Ford Fiesta Sprint Cup, F4 indiana e F4 britânica.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Esmee_Kosterman',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0020',
    name: 'Ava Dobson',
    birthDate: '2008-06-09',
    age: 17,
    nationalities: ['US'],
    academyNumber: 55,
    operatingTeam: 'Hitech',
    supporterBrand: 'American Express',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 51,
    qualifying: 52,
    racePace: 50,
    consistency: 50,
    start: 50,
    overtake: 50,
    defense: 49,
    rain: 51,
    tires: 48,
    energy: 49,
    feedback: 43,
    pressure: 47,
    concentration: 54,
    resilience: 62,
    aggressiveness: 70,
    ambition: 88,
    loyalty: 66,
    professionalism: 72,
    temperament: 33,
    reputation: 20,
    globalPopularity: 10,
    localPopularity: 32,
    localMarket: 'US',
    learningRateSkill: 88,
    ceilings: {
      speed: 76,
      qualifying: 74,
      racePace: 76,
      consistency: 78,
      start: 77,
      overtake: 74,
      defense: 77,
      rain: 76,
      tires: 75,
      energy: 80,
      feedback: 71,
      pressure: 68,
      concentration: 72,
      resilience: 84,
    },
    declineStart: 33,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.7,
      qualifying: 1.7,
      racePace: 0.3,
      consistency: 0.3,
      start: 1.7,
      overtake: 0.3,
      defense: 0.3,
      rain: 0.3,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.3,
      concentration: 0.3,
      resilience: 0.3,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 79,
    adaptationF1: 23,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,3%',
    stepsToF1_80: 13,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 70000,
    minimumAnnualUsd: 42000,
    negotiationWeights: {
      money: 0.128,
      project: 0.229,
      prestige: 0.11,
      stability: 0.229,
      role: 0.128,
      relationship: 0.174,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'GB4',
    biography:
      'Passou pela F4 dos Estados Unidos, USF Juniors e GB4. Competiu na GB4 em 2024 e 2025.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Ava_Dobson',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0067',
    name: 'Rachel Robertson',
    birthDate: '2007-07-28',
    age: 18,
    nationalities: ['GB'],
    academyNumber: 56,
    operatingTeam: 'Hitech',
    supporterBrand: 'PUMA',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 54,
    qualifying: 53,
    racePace: 55,
    consistency: 52,
    start: 51,
    overtake: 57,
    defense: 53,
    rain: 61,
    tires: 51,
    energy: 48,
    feedback: 46,
    pressure: 51,
    concentration: 51,
    resilience: 85,
    aggressiveness: 60,
    ambition: 75,
    loyalty: 69,
    professionalism: 89,
    temperament: 36,
    reputation: 23,
    globalPopularity: 13,
    localPopularity: 35,
    localMarket: 'GB',
    learningRateSkill: 90,
    ceilings: {
      speed: 82,
      qualifying: 78,
      racePace: 77,
      consistency: 83,
      start: 74,
      overtake: 84,
      defense: 77,
      rain: 89,
      tires: 81,
      energy: 75,
      feedback: 77,
      pressure: 68,
      concentration: 72,
      resilience: 100,
    },
    declineStart: 36,
    retirementHorizon: 20,
    annualLosses: {
      speed: 2.0,
      qualifying: 2.0,
      racePace: 0.6,
      consistency: 0.6,
      start: 2.0,
      overtake: 0.6,
      defense: 0.6,
      rain: 0.6,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.6,
      concentration: 0.6,
      resilience: 0.6,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 85,
    adaptationF1: 26,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,8%',
    stepsToF1_80: 12,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 90000,
    minimumAnnualUsd: 54000,
    negotiationWeights: {
      money: 0.111,
      project: 0.222,
      prestige: 0.144,
      stability: 0.222,
      role: 0.144,
      relationship: 0.156,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Radical',
    biography:
      'Disputou a Radical Cup UK e a F4 saudita em 2025. Terminou em quarto na estreia na F1 Academy, em uma corrida molhada em Las Vegas.',
    bioSourceUrl: 'https://en.wikipedia.org/wiki/Rachel_Robertson',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0017',
    name: 'Kaylee Countryman',
    birthDate: '2010-01-03',
    age: 16,
    nationalities: ['US'],
    academyNumber: 91,
    operatingTeam: 'ART Grand Prix',
    supporterBrand: 'Haas',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 48,
    qualifying: 49,
    racePace: 47,
    consistency: 48,
    start: 47,
    overtake: 44,
    defense: 44,
    rain: 44,
    tires: 46,
    energy: 48,
    feedback: 40,
    pressure: 51,
    concentration: 45,
    resilience: 81,
    aggressiveness: 58,
    ambition: 73,
    loyalty: 48,
    professionalism: 87,
    temperament: 46,
    reputation: 19,
    globalPopularity: 9,
    localPopularity: 31,
    localMarket: 'US',
    learningRateSkill: 88,
    ceilings: {
      speed: 74,
      qualifying: 72,
      racePace: 74,
      consistency: 77,
      start: 75,
      overtake: 69,
      defense: 66,
      rain: 70,
      tires: 74,
      energy: 80,
      feedback: 69,
      pressure: 73,
      concentration: 64,
      resilience: 97,
    },
    declineStart: 34,
    retirementHorizon: 20,
    annualLosses: {
      speed: 1.8,
      qualifying: 1.8,
      racePace: 0.4,
      consistency: 0.4,
      start: 1.8,
      overtake: 0.4,
      defense: 0.4,
      rain: 0.4,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.4,
      concentration: 0.4,
      resilience: 0.4,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 77,
    adaptationF1: 18,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,2%',
    stepsToF1_80: 14,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 60000,
    minimumAnnualUsd: 36000,
    negotiationWeights: {
      money: 0.279,
      project: 0.25,
      prestige: 0.106,
      stability: 0.096,
      role: 0.077,
      relationship: 0.192,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'USF Juniors',
    biography:
      'Competiu na USF Juniors em 2025 com a Exclusive Autosport. Seu histórico inicial está ligado à formação em monopostos nos Estados Unidos.',
    bioSourceUrl:
      'https://www.usf2000.com/news/kaylee-countryman-continues-journey-up-usf-pro-championship-ladder-with-exclusive-autosport',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
  {
    id: 'pil_0039',
    name: 'Jade Jacquet',
    birthDate: '2009-12-01',
    age: 16,
    nationalities: ['FR'],
    academyNumber: 95,
    operatingTeam: 'ART Grand Prix',
    supporterBrand: 'Williams',
    f1MarketStatus: 'LIVRE',
    sourceUrl: 'https://www.f1academy.com/Racing-Series/Drivers',
    speed: 49,
    qualifying: 50,
    racePace: 48,
    consistency: 48,
    start: 51,
    overtake: 49,
    defense: 48,
    rain: 47,
    tires: 45,
    energy: 42,
    feedback: 41,
    pressure: 46,
    concentration: 51,
    resilience: 63,
    aggressiveness: 47,
    ambition: 71,
    loyalty: 56,
    professionalism: 82,
    temperament: 54,
    reputation: 19,
    globalPopularity: 9,
    localPopularity: 31,
    localMarket: 'FR',
    learningRateSkill: 88,
    ceilings: {
      speed: 77,
      qualifying: 75,
      racePace: 70,
      consistency: 79,
      start: 74,
      overtake: 76,
      defense: 72,
      rain: 75,
      tires: 75,
      energy: 69,
      feedback: 72,
      pressure: 63,
      concentration: 72,
      resilience: 81,
    },
    declineStart: 40,
    retirementHorizon: 20,
    annualLosses: {
      speed: 2.0,
      qualifying: 2.0,
      racePace: 0.6,
      consistency: 0.6,
      start: 2.0,
      overtake: 0.6,
      defense: 0.6,
      rain: 0.6,
      tires: 0,
      energy: 0,
      feedback: 0,
      pressure: 0.6,
      concentration: 0.6,
      resilience: 0.6,
    },
    morale: 65,
    confidence: 50,
    condition: 100,
    stress: 20,
    adaptability: 78,
    adaptationF1: 24,
    carAdaptation: 0,
    teamAdaptation: 0,
    combinedAdaptation: 'Sem contexto',
    adaptationLearningRate: '10,2%',
    stepsToF1_80: 13,
    contextNote: 'Carro/equipe ainda não definidos',
    referenceAnnualUsd: 60000,
    minimumAnnualUsd: 36000,
    negotiationWeights: {
      money: 0.212,
      project: 0.212,
      prestige: 0.097,
      stability: 0.212,
      role: 0.106,
      relationship: 0.159,
    },
    acceptsReserve: true,
    acceptedRoles: ['LIDER', 'IGUAL', 'APOIO'],
    activeCommercialRevenueUsd: 0,
    valuePurpose: 'Bolsa anual de desenvolvimento',
    referenceCategory: 'Fórmula 4',
    biography:
      'Competiu na F4 francesa em 2025. Foi anunciada pela Williams para representar a equipe na F1 Academy de 2026.',
    bioSourceUrl:
      'https://www.williamsf1.com/articles/8d0371a4-d07e-4513-b533-1809c540ba6c/jade-jacquet-atlassian-williams-racing-f1-academy',
    coverage: 'Resumo; não é histórico completo de resultados',
    traits: [
      {
        code: 'TR10',
        name: 'Preparação de volta',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
      {
        code: 'TR09',
        name: 'Aprendizado em simulador',
        revealedStatus: 'Não revelado',
        nature: 'DESIGN editorial',
        startDate: '2026-03-01',
      },
    ],
  },
]

/**
 * Validação programática das regras do documento MBJ 2026 (R19 / R02 / R03)
 */
export function validateF1AcademyOfficialData(
  data: F1AcademyPilotMBJ[] = OFFICIAL_F1_ACADEMY_MBJ_2026,
) {
  const errors: string[] = []
  if (data.length !== 17) {
    errors.push(`Esperava 17 pilotas, encontrou ${data.length}`)
  }

  const ids = new Set<string>()
  for (const pilot of data) {
    if (ids.has(pilot.id)) {
      errors.push(`ID duplicado: ${pilot.id}`)
    }
    ids.add(pilot.id)

    // Pesos somam 1 +/- 0.001 (R19)
    const weightSum =
      pilot.negotiationWeights.money +
      pilot.negotiationWeights.project +
      pilot.negotiationWeights.prestige +
      pilot.negotiationWeights.stability +
      pilot.negotiationWeights.role +
      pilot.negotiationWeights.relationship
    if (Math.abs(weightSum - 1.0) > 0.005) {
      errors.push(`Pesos da pilota ${pilot.name} somam ${weightSum}, esperado ~1.0`)
    }

    // 14 tetos
    const ceilingKeys = Object.keys(pilot.ceilings)
    if (ceilingKeys.length !== 14) {
      errors.push(`Pilota ${pilot.name} não possui os 14 tetos (tem ${ceilingKeys.length})`)
    }

    // Traços
    if (!pilot.traits || pilot.traits.length === 0 || pilot.traits.length > 4) {
      errors.push(`Pilota ${pilot.name} tem quantidade inválida de traços: ${pilot.traits?.length}`)
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}
