import { GrandPrixInfo, EngineSupplierSpec } from '@/types/f1'

export const F1_2026_CALENDAR: GrandPrixInfo[] = [
  {
    round: 1,
    name: 'Grande Prêmio da Austrália',
    circuit: 'Circuito de Albert Park, Melbourne',
    country: 'Austrália',
    flag: '🇦🇺',
    laps: 58,
    circuitLengthKm: 5.278,
    characteristic: 'Misto rápido com frenagens fortes',
  },
  {
    round: 2,
    name: 'Grande Prêmio da China',
    circuit: 'Circuito Internacional de Xangai',
    country: 'China',
    flag: '🇨🇳',
    laps: 56,
    circuitLengthKm: 5.451,
    characteristic: 'Reta longa e curvas fechadas',
  },
  {
    round: 3,
    name: 'Grande Prêmio do Japão',
    circuit: 'Circuito de Suzuka',
    country: 'Japão',
    flag: '🇯🇵',
    laps: 53,
    circuitLengthKm: 5.807,
    characteristic: 'Alta pressão aerodinâmica em S',
  },
  {
    round: 4,
    name: 'Grande Prêmio do Bahrein',
    circuit: 'Circuito Internacional do Bahrein, Sakhir',
    country: 'Bahrein',
    flag: '🇧🇭',
    laps: 57,
    circuitLengthKm: 5.412,
    characteristic: 'Exigência de tração e frenagens',
  },
  {
    round: 5,
    name: 'Grande Prêmio da Arábia Saudita',
    circuit: 'Circuito de Corniche de Jeddah',
    country: 'Arábia Saudita',
    flag: '🇸🇦',
    laps: 50,
    circuitLengthKm: 6.174,
    characteristic: 'Circuito de rua de altíssima velocidade',
  },
  {
    round: 6,
    name: 'Grande Prêmio de Miami',
    circuit: 'Autódromo Internacional de Miami',
    country: 'Estados Unidos',
    flag: '🇺🇸',
    laps: 57,
    circuitLengthKm: 5.412,
    characteristic: 'Misto de rua com longas retas',
  },
  {
    round: 7,
    name: 'Grande Prêmio da Emília-Romanha',
    circuit: 'Autodromo Enzo e Dino Ferrari, Imola',
    country: 'Itália',
    flag: '🇮🇹',
    laps: 63,
    circuitLengthKm: 4.909,
    characteristic: 'Técnico tradicional, poucas ultrapassagens',
  },
  {
    round: 8,
    name: 'Grande Prêmio de Mônaco',
    circuit: 'Circuito de Mônaco, Monte Carlo',
    country: 'Mônaco',
    flag: '🇲🇨',
    laps: 78,
    circuitLengthKm: 3.337,
    characteristic: 'Travado, chassi ágil e qualificação vital',
  },
  {
    round: 9,
    name: 'Grande Prêmio da Espanha',
    circuit: 'Circuito de Barcelona-Catalunha',
    country: 'Espanha',
    flag: '🇪🇸',
    laps: 66,
    circuitLengthKm: 4.657,
    characteristic: 'Referência aerodinâmica global',
  },
  {
    round: 10,
    name: 'Grande Prêmio do Canadá',
    circuit: 'Circuito Gilles Villeneuve, Montreal',
    country: 'Canadá',
    flag: '🇨🇦',
    laps: 70,
    circuitLengthKm: 4.361,
    characteristic: 'Stop-and-go com zebras altas',
  },
  {
    round: 11,
    name: 'Grande Prêmio da Áustria',
    circuit: 'Red Bull Ring, Spielberg',
    country: 'Áustria',
    flag: '🇦🇹',
    laps: 71,
    circuitLengthKm: 4.318,
    characteristic: 'Volta rápida em montanha com elevação',
  },
  {
    round: 12,
    name: 'Grande Prêmio da Grã-Bretanha',
    circuit: 'Circuito de Silverstone',
    country: 'Reino Unido',
    flag: '🇬🇧',
    laps: 52,
    circuitLengthKm: 5.891,
    characteristic: 'Curvas lendárias de alta velocidade',
  },
  {
    round: 13,
    name: 'Grande Prêmio da Bélgica',
    circuit: 'Circuito de Spa-Francorchamps',
    country: 'Bélgica',
    flag: '🇧🇪',
    laps: 44,
    circuitLengthKm: 7.004,
    characteristic: 'Eau Rouge, clima instável e potência 50/50',
  },
  {
    round: 14,
    name: 'Grande Prêmio da Hungria',
    circuit: 'Hungaroring, Budapeste',
    country: 'Hungria',
    flag: '🇭🇺',
    laps: 70,
    circuitLengthKm: 4.381,
    characteristic: 'Travado e quente, sem descanso',
  },
  {
    round: 15,
    name: 'Grande Prêmio dos Países Baixos',
    circuit: 'Circuito de Zandvoort',
    country: 'Holanda',
    flag: '🇳🇱',
    laps: 72,
    circuitLengthKm: 4.259,
    characteristic: 'Curvas inclinadas e vento costeiro',
  },
  {
    round: 16,
    name: 'Grande Prêmio da Itália',
    circuit: 'Autodromo Nazionale Monza',
    country: 'Itália',
    flag: '🇮🇹',
    laps: 53,
    circuitLengthKm: 5.793,
    characteristic: 'Templo da velocidade, baixo arrasto',
  },
  {
    round: 17,
    name: 'Grande Prêmio do Azerbaijão',
    circuit: 'Circuito de Rua de Baku',
    country: 'Azerbaijão',
    flag: '🇦🇿',
    laps: 51,
    circuitLengthKm: 6.003,
    characteristic: 'Reta gigantesca e castelo estreito',
  },
  {
    round: 18,
    name: 'Grande Prêmio de Singapura',
    circuit: 'Circuito de Rua de Marina Bay',
    country: 'Singapura',
    flag: '🇸🇬',
    laps: 62,
    circuitLengthKm: 4.94,
    characteristic: 'Noturna, umidade extrema e calor',
  },
  {
    round: 19,
    name: 'Grande Prêmio dos Estados Unidos',
    circuit: 'Circuito das Américas, Austin',
    country: 'Estados Unidos',
    flag: '🇺🇸',
    laps: 56,
    circuitLengthKm: 5.513,
    characteristic: 'Subida na curva 1 e sequências velozes',
  },
  {
    round: 20,
    name: 'Grande Prêmio do México',
    circuit: 'Autódromo Hermanos Rodríguez, Cidade do México',
    country: 'México',
    flag: '🇲🇽',
    laps: 71,
    circuitLengthKm: 4.304,
    characteristic: 'Ar rarefeito a 2.200m de altitude',
  },
  {
    round: 21,
    name: 'Grande Prêmio de São Paulo',
    circuit: 'Autódromo José Carlos Pace, Interlagos',
    country: 'Brasil',
    flag: '🇧🇷',
    laps: 71,
    circuitLengthKm: 4.309,
    characteristic: 'Sentido anti-horário, fãs fervorosos e clima imprevisível',
  },
  {
    round: 22,
    name: 'Grande Prêmio de Las Vegas',
    circuit: 'Circuito da Las Vegas Strip',
    country: 'Estados Unidos',
    flag: '🇺🇸',
    laps: 50,
    circuitLengthKm: 6.201,
    characteristic: 'Frio noturno na Strip a mais de 340 km/h',
  },
  {
    round: 23,
    name: 'Grande Prêmio do Catar',
    circuit: 'Circuito Internacional de Lusail',
    country: 'Catar',
    flag: '🇶🇦',
    laps: 57,
    circuitLengthKm: 5.419,
    characteristic: 'Sequência fluida de curvas rápidas sob holofotes',
  },
  {
    round: 24,
    name: 'Grande Prêmio de Abu Dhabi',
    circuit: 'Circuito de Yas Marina',
    country: 'Emirados Árabes Unidos',
    flag: '🇦🇪',
    laps: 58,
    circuitLengthKm: 5.281,
    characteristic: 'Final do campeonato ao entardecer',
  },
]

export const ENGINE_SUPPLIERS: EngineSupplierSpec[] = [
  {
    name: 'Ferrari',
    power: 92,
    reliability: 86,
    costAnnual: 32000000,
    description:
      'Unidade de potência Scuderia Ferrari 067/26 com recuperação elétrica agressiva e alto pico elétrico nas retas.',
    techBadge: '50/50 Turbo-Híbrido Maranello',
  },
  {
    name: 'Mercedes',
    power: 90,
    reliability: 93,
    costAnnual: 30000000,
    description:
      'Brixworth High Performance Powertrains. Referência em gerenciamento térmico, eficiência do MGU-K e consistência exemplar.',
    techBadge: '50/50 M17 E-Performance',
  },
  {
    name: 'Honda',
    power: 91,
    reliability: 88,
    costAnnual: 28000000,
    description:
      'Honda Racing Corporation (HRC). Entrega linear de torque híbrido e aerodinâmica compacta do pacote.',
    techBadge: 'HRC RA626H',
  },
  {
    name: 'Ford',
    power: 94,
    reliability: 82,
    costAnnual: 34000000,
    description:
      'Red Bull Ford Powertrains. Monstro de aceleração com software preditivo de deploy elétrico, porém maior taxa de desgaste.',
    techBadge: 'Ford Red Bull EcoBoost F1',
  },
]

export interface AICompetitor {
  id: string
  name: string
  color: string
  engine: 'Ferrari' | 'Mercedes' | 'Honda' | 'Ford'
  carLevel: number
  driver1: {
    name: string
    speed: number
    consistency: number
    rain: number
    defense: number
    nationality: string
    flag: string
  }
  driver2: {
    name: string
    speed: number
    consistency: number
    rain: number
    defense: number
    nationality: string
    flag: string
  }
}

export const AI_GRID_TEAMS: AICompetitor[] = [
  {
    id: 'ai_redbull',
    name: 'Red Bull Racing',
    color: '#1E41FF',
    engine: 'Ford',
    carLevel: 88,
    driver1: {
      name: 'Max Verstappen',
      speed: 95,
      consistency: 90,
      rain: 88,
      defense: 88,
      nationality: 'Holanda',
      flag: '🇳🇱',
    },
    driver2: {
      name: 'Liam Lawson',
      speed: 82,
      consistency: 79,
      rain: 76,
      defense: 77,
      nationality: 'Nova Zelândia',
      flag: '🇳🇿',
    },
  },
  {
    id: 'ai_ferrari',
    name: 'Scuderia Ferrari',
    color: '#E8002D',
    engine: 'Ferrari',
    carLevel: 87,
    driver1: {
      name: 'Lewis Hamilton',
      speed: 91,
      consistency: 88,
      rain: 86,
      defense: 83,
      nationality: 'Reino Unido',
      flag: '🇬🇧',
    },
    driver2: {
      name: 'Charles Leclerc',
      speed: 89,
      consistency: 85,
      rain: 81,
      defense: 84,
      nationality: 'Mônaco',
      flag: '🇲🇨',
    },
  },
  {
    id: 'ai_mclaren',
    name: 'McLaren F1 Team',
    color: '#FF8000',
    engine: 'Mercedes',
    carLevel: 89,
    driver1: {
      name: 'Lando Norris',
      speed: 88,
      consistency: 85,
      rain: 83,
      defense: 81,
      nationality: 'Reino Unido',
      flag: '🇬🇧',
    },
    driver2: {
      name: 'Oscar Piastri',
      speed: 87,
      consistency: 86,
      rain: 81,
      defense: 79,
      nationality: 'Austrália',
      flag: '🇦🇺',
    },
  },
  {
    id: 'ai_mercedes',
    name: 'Mercedes-AMG Petronas',
    color: '#27F4D2',
    engine: 'Mercedes',
    carLevel: 86,
    driver1: {
      name: 'George Russell',
      speed: 86,
      consistency: 84,
      rain: 79,
      defense: 83,
      nationality: 'Reino Unido',
      flag: '🇬🇧',
    },
    driver2: {
      name: 'Andrea Kimi Antonelli',
      speed: 84,
      consistency: 78,
      rain: 77,
      defense: 76,
      nationality: 'Itália',
      flag: '🇮🇹',
    },
  },
  {
    id: 'ai_astonmartin',
    name: 'Aston Martin Aramco',
    color: '#229971',
    engine: 'Honda',
    carLevel: 83,
    driver1: {
      name: 'Fernando Alonso',
      speed: 88,
      consistency: 85,
      rain: 90,
      defense: 86,
      nationality: 'Espanha',
      flag: '🇪🇸',
    },
    driver2: {
      name: 'Lance Stroll',
      speed: 77,
      consistency: 74,
      rain: 80,
      defense: 74,
      nationality: 'Canadá',
      flag: '🇨🇦',
    },
  },
  {
    id: 'ai_alpine',
    name: 'Alpine F1 Team',
    color: '#0093CC',
    engine: 'Mercedes',
    carLevel: 78,
    driver1: {
      name: 'Pierre Gasly',
      speed: 83,
      consistency: 81,
      rain: 79,
      defense: 80,
      nationality: 'França',
      flag: '🇫🇷',
    },
    driver2: {
      name: 'Jack Doohan',
      speed: 76,
      consistency: 75,
      rain: 74,
      defense: 73,
      nationality: 'Austrália',
      flag: '🇦🇺',
    },
  },
  {
    id: 'ai_williams',
    name: 'Williams Racing',
    color: '#64C4FF',
    engine: 'Mercedes',
    carLevel: 80,
    driver1: {
      name: 'Carlos Sainz',
      speed: 85,
      consistency: 83,
      rain: 79,
      defense: 81,
      nationality: 'Espanha',
      flag: '🇪🇸',
    },
    driver2: {
      name: 'Alexander Albon',
      speed: 83,
      consistency: 82,
      rain: 78,
      defense: 80,
      nationality: 'Tailândia',
      flag: '🇹🇭',
    },
  },
  {
    id: 'ai_racingbulls',
    name: 'Visa Cash App RB',
    color: '#6692FF',
    engine: 'Ford',
    carLevel: 79,
    driver1: {
      name: 'Yuki Tsunoda',
      speed: 81,
      consistency: 78,
      rain: 76,
      defense: 79,
      nationality: 'Japão',
      flag: '🇯🇵',
    },
    driver2: {
      name: 'Isack Hadjar',
      speed: 78,
      consistency: 76,
      rain: 75,
      defense: 74,
      nationality: 'França',
      flag: '🇫🇷',
    },
  },
  {
    id: 'ai_audi',
    name: 'Audi F1 Team',
    color: '#FF2A00',
    engine: 'Ferrari',
    carLevel: 79,
    driver1: {
      name: 'Nico Hülkenberg',
      speed: 82,
      consistency: 84,
      rain: 80,
      defense: 81,
      nationality: 'Alemanha',
      flag: '🇩🇪',
    },
    driver2: {
      name: 'Gabriel Bortoleto Jr.',
      speed: 79,
      consistency: 78,
      rain: 77,
      defense: 75,
      nationality: 'Brasil',
      flag: '🇧🇷',
    },
  },
  {
    id: 'ai_haas',
    name: 'Haas F1 Team',
    color: '#B6BABD',
    engine: 'Ferrari',
    carLevel: 77,
    driver1: {
      name: 'Esteban Ocon',
      speed: 82,
      consistency: 80,
      rain: 81,
      defense: 83,
      nationality: 'França',
      flag: '🇫🇷',
    },
    driver2: {
      name: 'Oliver Bearman',
      speed: 80,
      consistency: 77,
      rain: 76,
      defense: 76,
      nationality: 'Reino Unido',
      flag: '🇬🇧',
    },
  },
]

export const AVAILABLE_MARKET_SPONSORS = [
  {
    name: 'Petrobras Energy',
    valuePerRound: 28000000,
    requirement: 'Top 6 construtores',
    minConstructorPos: 6,
    minTeamMorale: 0,
    rounds: 12,
    description:
      'Investimento de grande porte focado em combustíveis sintéticos 100% sustentáveis.',
  },
  {
    name: 'Embraer Aerospace Tech',
    valuePerRound: 24000000,
    requirement: 'Top 8 construtores',
    minConstructorPos: 8,
    minTeamMorale: 0,
    rounds: 10,
    description: 'Parceria aeroespacial focada na telemetria de asas ativas e túnel de vento.',
  },
  {
    name: 'Nubank Ultra',
    valuePerRound: 22000000,
    requirement: 'Moral da equipe acima de 65',
    minConstructorPos: 11,
    minTeamMorale: 65,
    rounds: 14,
    description: 'Patrocinador jovem focado na presença digital e engajamento com os fãs.',
  },
  {
    name: 'Vale Verde Sustentabilidade',
    valuePerRound: 18000000,
    requirement: 'Sem exigência de posição',
    minConstructorPos: 11,
    minTeamMorale: 0,
    rounds: 8,
    description: 'Compensação de carbono das viagens e suporte à matriz elétrica 350kW.',
  },
  {
    name: 'Itaú Private Motorsport',
    valuePerRound: 35000000,
    requirement: 'Top 3 construtores',
    minConstructorPos: 3,
    minTeamMorale: 75,
    rounds: 16,
    description: 'Patrocínio master de alta exigência esportiva e bônus expressivos.',
  },
  {
    name: 'Claro 5G Telemetria',
    valuePerRound: 19500000,
    requirement: 'Top 7 construtores',
    minConstructorPos: 7,
    minTeamMorale: 50,
    rounds: 12,
    description: 'Conectividade de borda em tempo real entre a garagem e a fábrica.',
  },
]
