import { GridTeamDefinition } from '@/types/career-wizard'
import { getTeamLogoUrl } from './lobby-assets'

/**
 * Base de 28 Equipes Estruturadas da F1 Manager 2026
 * Extraídas diretamente do documento oficial Equipes.pdf fornecido pelo usuário:
 * 1. Mercedes (Alemanha)
 * 2. McLaren (Reino Unido)
 * 3. Ferrari (Itália)
 * 4. Red Bull Racing (Áustria)
 * 5. Aston Martin (Reino Unido)
 * 6. Audi (Alemanha)
 * 7. Williams (Reino Unido)
 * 8. Racing Bulls (Itália)
 * 9. Haas (EUA)
 * 10. Alpine (França)
 * 11. Cadillac (EUA)
 * 12. Porsche (Alemanha)
 * 13. Honda (Japão)
 * 14. Lamborghini (Itália)
 * 15. Andretti (EUA)
 * 16. BYD (China)
 * 17. Penske (EUA)
 * 18. Lotus (Reino Unido)
 * 19. Toyota (Japão)
 * 20. Benetton (Itália)
 * 21. Copersucar (Brasil)
 * 22. Alfa Romeo (Itália)
 * 23. AlphaTauri (Itália)
 * 24. Fittipaldi (Brasil)
 * 25. Jordan (Irlanda)
 * 26. Renault (França)
 * 27. Sauber (Suíça)
 * 28. Toleman (Reino Unido - nome oficial com logo Tolerman)
 */

export const ALL_GRID_TEAMS_DATABASE: GridTeamDefinition[] = [
  // 1. Mercedes
  {
    key: 'mercedes',
    name: 'Mercedes-AMG Petronas',
    shortName: 'Mercedes',
    country: 'Alemanha',
    flag: '🇩🇪',
    color: '#27F4D2',
    engine: 'Mercedes',
    strengthRating: 10.0,
    strength: 100,
    carLevel: 100,
    budget: 215000000,
    competitivenessVerdict: 'Referência absoluta',
    boardPressure: 'Extrema',
    difficulty: 'Fácil',
    initialObjective: 'Conquistar o título mundial de pilotos e construtores',
    infrastructureRating: 5,
    financesRating: 5,
    historySummary: '8 títulos consecutivos de construtores (2014-2021) na era híbrida original.',
    currentSituation:
      'Referência absoluta no novo regulamento com George Russell e Andrea Kimi Antonelli acelerando o pacote mais completo do grid.',
    logoUrl: getTeamLogoUrl('mercedes'),
    headquarters: 'Brackley & Brixworth, Reino Unido',
    category: 'Oficial de Fábrica (Construtora Integral)',
    specialTraits: [
      'Eficiência Energética PU',
      'Excelência Operacional',
      'Túnel de Vento de Ponta',
    ],
    carRating: 98,
    engineeringRating: 98,
    operationsRating: 96,
    prestigeRating: 98,
    cultureRating: 95,
    potentialRating: 94,
    driver1: {
      name: 'George Russell',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 28,
      speed: 94,
      consistency: 93,
      rain: 90,
      defense: 91,
      salary: 32000000,
    },
    driver2: {
      name: 'Andrea Kimi Antonelli',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 19,
      speed: 91,
      consistency: 88,
      rain: 86,
      defense: 87,
      salary: 12000000,
    },
    reserveDriver: {
      name: 'Frederik Vesti',
      nationality: 'Dinamarca',
      flag: '🇩🇰',
      age: 24,
      speed: 80,
      consistency: 81,
      rain: 79,
      defense: 78,
      salary: 4000000,
    },
  },

  // 2. McLaren
  {
    key: 'mclaren',
    name: 'McLaren F1 Team',
    shortName: 'McLaren',
    country: 'Reino Unido',
    flag: '🇬🇧',
    color: '#FF8000',
    engine: 'Mercedes',
    strengthRating: 8.8,
    strength: 88,
    carLevel: 88,
    budget: 205000000,
    competitivenessVerdict: 'Muito próxima da Ferrari',
    boardPressure: 'Alta',
    difficulty: 'Fácil',
    initialObjective: 'Disputar vitórias e o título mundial de construtores',
    infrastructureRating: 5,
    financesRating: 5,
    historySummary:
      '8 Mundiais de Construtores e 12 de Pilotos. Uma das marcas mais lendárias do automobilismo.',
    currentSituation:
      'Muito próxima da Ferrari, brigando por vitórias com a dupla consolidada Norris e Piastri.',
    logoUrl: getTeamLogoUrl('mclaren'),
    headquarters: 'Woking, Reino Unido (MTC)',
    category: 'Equipe de Ponta Independente (Cliente Mercedes)',
    specialTraits: ['Evolução Aerodinâmica Rápida', 'MTC Ultra Moderno', 'Dupla Sincronizada'],
    carRating: 91,
    engineeringRating: 92,
    operationsRating: 90,
    prestigeRating: 95,
    cultureRating: 92,
    potentialRating: 92,
    driver1: {
      name: 'Lando Norris',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 26,
      speed: 93,
      consistency: 90,
      rain: 89,
      defense: 88,
      salary: 30000000,
    },
    driver2: {
      name: 'Oscar Piastri',
      nationality: 'Austrália',
      flag: '🇦🇺',
      age: 25,
      speed: 92,
      consistency: 91,
      rain: 87,
      defense: 88,
      salary: 28000000,
    },
    reserveDriver: {
      name: "Patricio O'Ward",
      nationality: 'México',
      flag: '🇲🇽',
      age: 26,
      speed: 81,
      consistency: 80,
      rain: 80,
      defense: 79,
      salary: 5000000,
    },
  },

  // 3. Ferrari
  {
    key: 'ferrari',
    name: 'Scuderia Ferrari',
    shortName: 'Ferrari',
    country: 'Itália',
    flag: '🇮🇹',
    color: '#E8002D',
    engine: 'Ferrari',
    strengthRating: 9.1,
    strength: 91,
    carLevel: 91,
    budget: 210000000,
    competitivenessVerdict: 'Principal adversária',
    boardPressure: 'Extrema',
    difficulty: 'Fácil',
    initialObjective: 'Conquistar vitórias frequentes e trazer o caneco para Maranello',
    infrastructureRating: 5,
    financesRating: 5,
    historySummary:
      'A escuderia mais antiga e laureada da história da F1 (16 Construtores, 15 Pilotos).',
    currentSituation:
      'Principal adversária da Mercedes na disputa direta por vitórias com Hamilton e Leclerc.',
    logoUrl: getTeamLogoUrl('ferrari'),
    headquarters: 'Maranello, Itália',
    category: 'Oficial de Fábrica (Histórica Lendária)',
    specialTraits: ['Potência de Motor Puro', 'Tradição Mítica', 'Pressão de Mídia Tifosi'],
    carRating: 93,
    engineeringRating: 94,
    operationsRating: 88,
    prestigeRating: 100,
    cultureRating: 94,
    potentialRating: 95,
    driver1: {
      name: 'Lewis Hamilton',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 41,
      speed: 94,
      consistency: 92,
      rain: 95,
      defense: 92,
      salary: 45000000,
    },
    driver2: {
      name: 'Charles Leclerc',
      nationality: 'Mônaco',
      flag: '🇲🇨',
      age: 28,
      speed: 95,
      consistency: 89,
      rain: 88,
      defense: 89,
      salary: 38000000,
    },
    reserveDriver: {
      name: 'Antonio Giovinazzi',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 32,
      speed: 80,
      consistency: 81,
      rain: 79,
      defense: 79,
      salary: 4500000,
    },
  },

  // 4. Red Bull Racing
  {
    key: 'redbull',
    name: 'Red Bull Racing',
    shortName: 'Red Bull',
    country: 'Áustria',
    flag: '🇦🇹',
    color: '#1E41FF',
    engine: 'Ford',
    strengthRating: 8.4,
    strength: 84,
    carLevel: 84,
    budget: 200000000,
    competitivenessVerdict: 'Pelotão da frente',
    boardPressure: 'Extrema',
    difficulty: 'Fácil',
    initialObjective: 'Disputar pódios e vitórias com motor Red Bull-Ford',
    infrastructureRating: 5,
    financesRating: 5,
    historySummary: 'Hexacampeã mundial de construtores e heptacampeã de pilotos na era moderna.',
    currentSituation: 'Na briga direta pelo topo com Verstappen e os novos motores Red Bull Ford.',
    logoUrl: getTeamLogoUrl('redbull'),
    headquarters: 'Milton Keynes, Reino Unido',
    category: 'Oficial de Fábrica (Red Bull Ford Powertrains)',
    specialTraits: ['Pitstops Relâmpago', 'Agressividade Estratégica', 'RBPT Red Bull Ford'],
    carRating: 87,
    engineeringRating: 89,
    operationsRating: 95,
    prestigeRating: 96,
    cultureRating: 92,
    potentialRating: 91,
    driver1: {
      name: 'Max Verstappen',
      nationality: 'Holanda',
      flag: '🇳🇱',
      age: 28,
      speed: 96,
      consistency: 94,
      rain: 95,
      defense: 94,
      salary: 52000000,
    },
    driver2: {
      name: 'Isack Hadjar',
      nationality: 'França',
      flag: '🇫🇷',
      age: 21,
      speed: 83,
      consistency: 80,
      rain: 80,
      defense: 78,
      salary: 6000000,
    },
    reserveDriver: {
      name: 'Ayumu Iwasa',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 24,
      speed: 79,
      consistency: 79,
      rain: 78,
      defense: 77,
      salary: 3500000,
    },
  },

  // 5. Aston Martin
  {
    key: 'astonmartin',
    name: 'Aston Martin Aramco',
    shortName: 'Aston Martin',
    country: 'Reino Unido',
    flag: '🇬🇧',
    color: '#229971',
    engine: 'Honda',
    strengthRating: 3.7,
    strength: 37,
    carLevel: 37,
    budget: 150000000,
    competitivenessVerdict: 'Pelotão intermediário em reconstrução',
    boardPressure: 'Alta',
    difficulty: 'Desafiadora',
    initialObjective: 'Pontuar com frequência e avançar para o Top 6',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'Fábrica ultramoderna em Silverstone com túnel de vento próprio e parceria oficial Honda.',
    currentSituation: 'Em busca de consistência com Fernando Alonso e Lance Stroll.',
    logoUrl: getTeamLogoUrl('astonmartin'),
    headquarters: 'Silverstone, Reino Unido',
    category: 'Equipe de Fábrica Honda HRC',
    specialTraits: ['Novo Campus Silverstone', 'Parceria Oficial Honda HRC', 'Feedback de Alonso'],
    carRating: 62,
    engineeringRating: 70,
    operationsRating: 68,
    prestigeRating: 80,
    cultureRating: 75,
    potentialRating: 85,
    driver1: {
      name: 'Fernando Alonso',
      nationality: 'Espanha',
      flag: '🇪🇸',
      age: 44,
      speed: 86,
      consistency: 85,
      rain: 89,
      defense: 86,
      salary: 19000000,
    },
    driver2: {
      name: 'Lance Stroll',
      nationality: 'Canadá',
      flag: '🇨🇦',
      age: 27,
      speed: 76,
      consistency: 75,
      rain: 78,
      defense: 75,
      salary: 10000000,
    },
    reserveDriver: {
      name: 'Felipe Drugovich',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 25,
      speed: 80,
      consistency: 80,
      rain: 81,
      defense: 78,
      salary: 5000000,
    },
  },

  // 6. Audi
  {
    key: 'audi',
    name: 'Audi F1 Team',
    shortName: 'Audi',
    country: 'Alemanha',
    flag: '🇩🇪',
    color: '#FF2A00',
    engine: 'Audi',
    strengthRating: 5.2,
    strength: 52,
    carLevel: 52,
    budget: 165000000,
    competitivenessVerdict: 'Claramente evoluindo',
    boardPressure: 'Média',
    difficulty: 'Média',
    initialObjective: 'Consolidar-se no Top 8 e marcar pontos regulares',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'A gigante alemã de Le Mans assume o controle integral para sua estreia de fábrica na F1.',
    currentSituation:
      'Mattia Binotto lidera reestruturação com Nico Hülkenberg e o talento brasileiro Gabriel Bortoleto.',
    logoUrl: getTeamLogoUrl('audi'),
    headquarters: 'Neuburg & Hinwil, Alemanha / Suíça',
    category: 'Oficial de Fábrica (Estreante Integral 2026)',
    specialTraits: [
      'Unidade de Potência Audi 2026',
      'Investimento Alemão de Longo Prazo',
      'Liderança Técnica Binotto',
    ],
    carRating: 70,
    engineeringRating: 76,
    operationsRating: 74,
    prestigeRating: 84,
    cultureRating: 82,
    potentialRating: 90,
    driver1: {
      name: 'Nico Hülkenberg',
      nationality: 'Alemanha',
      flag: '🇩🇪',
      age: 38,
      speed: 83,
      consistency: 83,
      rain: 82,
      defense: 82,
      salary: 11000000,
    },
    driver2: {
      name: 'Gabriel Bortoleto',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 21,
      speed: 83,
      consistency: 82,
      rain: 83,
      defense: 80,
      salary: 8000000,
    },
    reserveDriver: {
      name: 'Zane Maloney',
      nationality: 'Barbados',
      flag: '🇧🇧',
      age: 22,
      speed: 78,
      consistency: 77,
      rain: 77,
      defense: 76,
      salary: 3500000,
    },
  },

  // 7. Williams
  {
    key: 'williams',
    name: 'Williams Racing',
    shortName: 'Williams',
    country: 'Reino Unido',
    flag: '🇬🇧',
    color: '#64C4FF',
    engine: 'Mercedes',
    strengthRating: 4.2,
    strength: 42,
    carLevel: 42,
    budget: 145000000,
    competitivenessVerdict: 'Histórica em recuperação',
    boardPressure: 'Média',
    difficulty: 'Desafiadora',
    initialObjective: 'Conquistar pontos regulares no meio do pelotão',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary:
      '9 Mundiais de Construtores e 7 de Pilotos. Um dos maiores legados da categoria.',
    currentSituation:
      'Superdupla experiente com Carlos Sainz e Alexander Albon buscando subir degraus.',
    logoUrl: getTeamLogoUrl('williams'),
    headquarters: 'Grove, Oxfordshire, Reino Unido',
    category: 'Independente Histórica (Cliente Mercedes)',
    specialTraits: [
      'Tradição Britânica Pura',
      'Reconstrução de Fábrica',
      'Velocidade em Linha Reta',
    ],
    carRating: 65,
    engineeringRating: 68,
    operationsRating: 70,
    prestigeRating: 89,
    cultureRating: 80,
    potentialRating: 82,
    driver1: {
      name: 'Carlos Sainz',
      nationality: 'Espanha',
      flag: '🇪🇸',
      age: 31,
      speed: 86,
      consistency: 85,
      rain: 82,
      defense: 83,
      salary: 22000000,
    },
    driver2: {
      name: 'Alexander Albon',
      nationality: 'Tailândia',
      flag: '🇹🇭',
      age: 29,
      speed: 83,
      consistency: 82,
      rain: 79,
      defense: 80,
      salary: 13000000,
    },
    reserveDriver: {
      name: 'Luke Browning',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 24,
      speed: 77,
      consistency: 76,
      rain: 75,
      defense: 75,
      salary: 3200000,
    },
  },

  // 8. Racing Bulls
  {
    key: 'racingbulls',
    name: 'Visa Cash App RB',
    shortName: 'Racing Bulls',
    country: 'Itália',
    flag: '🇮🇹',
    color: '#6692FF',
    engine: 'Ford',
    strengthRating: 6.3,
    strength: 63,
    carLevel: 63,
    budget: 160000000,
    competitivenessVerdict: 'Melhor do segundo pelotão',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Liderar o pelotão intermediário e pontuar todo fim de semana',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'Herdeira da Toro Rosso e Minardi em Faenza, famosa por forjar grandes campeões.',
    currentSituation: 'Consistente na zona de pontos com Liam Lawson e o jovem Arvid Lindblad.',
    logoUrl: getTeamLogoUrl('racingbulls'),
    headquarters: 'Faenza, Itália & Bicester, Reino Unido',
    category: 'Equipe Irmã Red Bull Racing',
    specialTraits: [
      'Sinergia Técnica Red Bull',
      'Celeiro de Jovens Talentos',
      'Agilidade Operacional',
    ],
    carRating: 75,
    engineeringRating: 78,
    operationsRating: 76,
    prestigeRating: 78,
    cultureRating: 79,
    potentialRating: 84,
    driver1: {
      name: 'Liam Lawson',
      nationality: 'Nova Zelândia',
      flag: '🇳🇿',
      age: 24,
      speed: 84,
      consistency: 83,
      rain: 82,
      defense: 83,
      salary: 9000000,
    },
    driver2: {
      name: 'Arvid Lindblad',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 18,
      speed: 82,
      consistency: 80,
      rain: 79,
      defense: 78,
      salary: 4500000,
    },
    reserveDriver: {
      name: 'Jak Crawford',
      nationality: 'Estados Unidos',
      flag: '🇺🇸',
      age: 20,
      speed: 78,
      consistency: 77,
      rain: 76,
      defense: 76,
      salary: 3000000,
    },
  },

  // 9. Haas
  {
    key: 'haas',
    name: 'Haas F1 Team',
    shortName: 'Haas',
    country: 'EUA',
    flag: '🇺🇸',
    color: '#B6BABD',
    engine: 'Ferrari',
    strengthRating: 4.8,
    strength: 48,
    carLevel: 48,
    budget: 140000000,
    competitivenessVerdict: 'Competitiva nos pontos',
    boardPressure: 'Média',
    difficulty: 'Desafiadora',
    initialObjective: 'Aproveitar corridas caóticas para somar pontos vitais',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary: 'Operação americana enxuta em parceria técnica reforçada com Ferrari e Toyota.',
    currentSituation:
      'Esteban Ocon e Oliver Bearman lutam com unhas e dentes na zona de corte do top 10.',
    logoUrl: getTeamLogoUrl('haas'),
    headquarters: 'Kannapolis (EUA) & Banbury (Reino Unido)',
    category: 'Independente Enxuta (Parceria Ferrari & Toyota GR)',
    specialTraits: [
      'Aliança Técnica Toyota GR',
      'Eficiência de Custo por Ponto',
      'DNA Americano de Competição',
    ],
    carRating: 68,
    engineeringRating: 70,
    operationsRating: 72,
    prestigeRating: 72,
    cultureRating: 74,
    potentialRating: 76,
    driver1: {
      name: 'Esteban Ocon',
      nationality: 'França',
      flag: '🇫🇷',
      age: 29,
      speed: 82,
      consistency: 81,
      rain: 82,
      defense: 83,
      salary: 12000000,
    },
    driver2: {
      name: 'Oliver Bearman',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 20,
      speed: 81,
      consistency: 78,
      rain: 78,
      defense: 78,
      salary: 6000000,
    },
    reserveDriver: {
      name: 'Ryo Hirakawa',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 32,
      speed: 77,
      consistency: 78,
      rain: 76,
      defense: 76,
      salary: 3500000,
    },
  },

  // 10. Alpine
  {
    key: 'alpine',
    name: 'Alpine F1 Team',
    shortName: 'Alpine',
    country: 'França',
    flag: '🇫🇷',
    color: '#0093CC',
    engine: 'Mercedes',
    strengthRating: 6.1,
    strength: 61,
    carLevel: 61,
    budget: 155000000,
    competitivenessVerdict: 'Velocidade alta, foco em consistência',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Brigando no Top 7 de construtores',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'Origens na Renault bicampeã em 2005-2006 e na lendária equipe Benetton dos anos 90.',
    currentSituation: 'Motor Mercedes garante picos de ritmo com Pierre Gasly e Franco Colapinto.',
    logoUrl: getTeamLogoUrl('alpine'),
    headquarters: 'Enstone, Reino Unido & Viry-Châtillon, França',
    category: 'Oficial de Marca (Cliente Mercedes UP)',
    specialTraits: [
      'Chassi Ágil em Curvas Médias',
      'Herança Francesa de Competição',
      'Garra em Pistas Travadas',
    ],
    carRating: 74,
    engineeringRating: 76,
    operationsRating: 75,
    prestigeRating: 82,
    cultureRating: 78,
    potentialRating: 80,
    driver1: {
      name: 'Pierre Gasly',
      nationality: 'França',
      flag: '🇫🇷',
      age: 30,
      speed: 84,
      consistency: 81,
      rain: 82,
      defense: 82,
      salary: 16000000,
    },
    driver2: {
      name: 'Franco Colapinto',
      nationality: 'Argentina',
      flag: '🇦🇷',
      age: 23,
      speed: 83,
      consistency: 79,
      rain: 79,
      defense: 79,
      salary: 8500000,
    },
    reserveDriver: {
      name: 'Paul Aron',
      nationality: 'Estônia',
      flag: '🇪🇪',
      age: 22,
      speed: 78,
      consistency: 77,
      rain: 76,
      defense: 75,
      salary: 3500000,
    },
  },

  // 11. Cadillac
  {
    key: 'cadillac',
    name: 'Cadillac F1 Team',
    shortName: 'Cadillac',
    country: 'EUA',
    flag: '🇺🇸',
    color: '#D4AF37',
    engine: 'Ferrari',
    strengthRating: 3.0,
    strength: 30,
    carLevel: 30,
    budget: 130000000,
    competitivenessVerdict: 'Estreante ambiciosa',
    boardPressure: 'Baixa',
    difficulty: 'Muito Difícil',
    initialObjective: 'Evoluir o carro, fugir da lanterna e somar os primeiros pontos históricos',
    infrastructureRating: 3,
    financesRating: 4,
    historySummary:
      'A gigante General Motors traz sua lendária divisão de luxo e velocidade para o pináculo do automobilismo.',
    currentSituation:
      'Estreante fechando a tabela, mesmo com os experientes Sergio Pérez e Valtteri Bottas.',
    logoUrl: undefined, // Cadillac sem logo oficial no pacote -> inicial estilizada
    headquarters: 'Warren, Michigan & Fishers, Indiana, EUA',
    category: 'Estreante Oficial GM (Cliente Ferrari UP temporário)',
    specialTraits: [
      'Apoio Tecnológico General Motors',
      'Dupla Hiper Experiente',
      'Projeção de Fábrica Própria',
    ],
    carRating: 50,
    engineeringRating: 58,
    operationsRating: 62,
    prestigeRating: 75,
    cultureRating: 76,
    potentialRating: 88,
    driver1: {
      name: 'Sergio Pérez',
      nationality: 'México',
      flag: '🇲🇽',
      age: 36,
      speed: 79,
      consistency: 80,
      rain: 78,
      defense: 80,
      salary: 12000000,
    },
    driver2: {
      name: 'Valtteri Bottas',
      nationality: 'Finlândia',
      flag: '🇫🇮',
      age: 36,
      speed: 79,
      consistency: 81,
      rain: 78,
      defense: 78,
      salary: 11000000,
    },
    reserveDriver: {
      name: 'Zhou Guanyu',
      nationality: 'China',
      flag: '🇨🇳',
      age: 26,
      speed: 76,
      consistency: 77,
      rain: 75,
      defense: 75,
      salary: 4000000,
    },
  },

  // 12. Porsche
  {
    key: 'porsche',
    name: 'Porsche Motorsport',
    shortName: 'Porsche',
    country: 'Alemanha',
    flag: '🇩🇪',
    color: '#C4001A',
    engine: 'Audi',
    strengthRating: 5.8,
    strength: 58,
    carLevel: 58,
    budget: 175000000,
    competitivenessVerdict: 'Lenda do endurance entrando na F1',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Lutar por pódios esporádicos e liderar o segundo pelotão',
    infrastructureRating: 5,
    financesRating: 5,
    historySummary:
      'Maior vencedora das 24 Horas de Le Mans, sinônimo absoluto de engenharia alemã refinada.',
    currentSituation: 'Projeto de alta precisão comPascal Wehrlein e António Félix da Costa.',
    logoUrl: getTeamLogoUrl('porsche'),
    headquarters: 'Weissach, Stuttgart, Alemanha',
    category: 'Escuderia Convidada / Reserva FIA',
    specialTraits: [
      'DNA Lendário de Le Mans',
      'Engenharia de Precisão Weissach',
      'Confiabilidade Mecânica',
    ],
    carRating: 72,
    engineeringRating: 80,
    operationsRating: 78,
    prestigeRating: 92,
    cultureRating: 88,
    potentialRating: 86,
    driver1: {
      name: 'Pascal Wehrlein',
      nationality: 'Alemanha',
      flag: '🇩🇪',
      age: 31,
      speed: 82,
      consistency: 82,
      rain: 80,
      defense: 81,
      salary: 8000000,
    },
    driver2: {
      name: 'António Félix da Costa',
      nationality: 'Portugal',
      flag: '🇵🇹',
      age: 34,
      speed: 81,
      consistency: 80,
      rain: 82,
      defense: 80,
      salary: 7000000,
    },
    reserveDriver: {
      name: 'Kévin Estre',
      nationality: 'França',
      flag: '🇫🇷',
      age: 37,
      speed: 79,
      consistency: 81,
      rain: 83,
      defense: 79,
      salary: 4000000,
    },
  },

  // 13. Honda
  {
    key: 'honda',
    name: 'Honda HRC F1 Team',
    shortName: 'Honda',
    country: 'Japão',
    flag: '🇯🇵',
    color: '#DC0000',
    engine: 'Honda',
    strengthRating: 6.0,
    strength: 60,
    carLevel: 60,
    budget: 170000000,
    competitivenessVerdict: 'Força de fábrica japonesa',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Top 5 de construtores com foco na eficiência da UP 2026',
    infrastructureRating: 5,
    financesRating: 4,
    historySummary:
      'Lendária fornecedora dos títulos de Senna e Verstappen, agora com equipe própria de ponta a ponta.',
    currentSituation:
      'Equipe de fábrica com Yuki Tsunoda e Kamui Kobayashi acelerando sob a bandeira de Sakura.',
    logoUrl: getTeamLogoUrl('honda'),
    headquarters: 'Sakura & Tochigi, Japão',
    category: 'Escuderia Convidada / Reserva FIA',
    specialTraits: [
      'HRC Racing Spirit',
      'Excelência em Híbridos ERS',
      'Disciplina Japonesa Monozukuri',
    ],
    carRating: 73,
    engineeringRating: 82,
    operationsRating: 77,
    prestigeRating: 90,
    cultureRating: 87,
    potentialRating: 85,
    driver1: {
      name: 'Yuki Tsunoda',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 25,
      speed: 84,
      consistency: 80,
      rain: 81,
      defense: 82,
      salary: 10000000,
    },
    driver2: {
      name: 'Kamui Kobayashi',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 39,
      speed: 80,
      consistency: 82,
      rain: 84,
      defense: 81,
      salary: 6000000,
    },
    reserveDriver: {
      name: 'Ritomo Miyata',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 26,
      speed: 77,
      consistency: 78,
      rain: 76,
      defense: 76,
      salary: 3000000,
    },
  },

  // 14. Lamborghini
  {
    key: 'lamborghini',
    name: 'Lamborghini Squadra Corse',
    shortName: 'Lamborghini',
    country: 'Itália',
    flag: '🇮🇹',
    color: '#D4AF37',
    engine: 'Audi',
    strengthRating: 5.5,
    strength: 55,
    carLevel: 55,
    budget: 160000000,
    competitivenessVerdict: 'O touro indomável de Sant’Agata',
    boardPressure: 'Média',
    difficulty: 'Média',
    initialObjective: 'Pontuar com os dois carros e desbancar rivais italianos',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'Design arrojado e paixão visceral, trazendo o touro italiano ao circo da velocidade.',
    currentSituation: 'Edoardo Mortara e Daniil Kvyat comandam um projeto de aceleração pura.',
    logoUrl: getTeamLogoUrl('lamborghini'),
    headquarters: 'Sant’Agata Bolognese, Itália',
    category: 'Escuderia Convidada / Reserva FIA',
    specialTraits: ['Design Italiano Arrojado', 'Aceleração Explosiva', 'Paixão de Sant’Agata'],
    carRating: 71,
    engineeringRating: 75,
    operationsRating: 73,
    prestigeRating: 88,
    cultureRating: 84,
    potentialRating: 82,
    driver1: {
      name: 'Edoardo Mortara',
      nationality: 'Suíça',
      flag: '🇨🇭',
      age: 39,
      speed: 80,
      consistency: 81,
      rain: 80,
      defense: 81,
      salary: 6500000,
    },
    driver2: {
      name: 'Mirko Bortolotti',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 36,
      speed: 79,
      consistency: 80,
      rain: 81,
      defense: 80,
      salary: 5000000,
    },
    reserveDriver: {
      name: 'Matteo Cairoli',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 29,
      speed: 76,
      consistency: 77,
      rain: 77,
      defense: 76,
      salary: 3000000,
    },
  },

  // 15. Andretti
  {
    key: 'andretti',
    name: 'Andretti Global',
    shortName: 'Andretti',
    country: 'EUA',
    flag: '🇺🇸',
    color: '#002B49',
    engine: 'Honda',
    strengthRating: 3.5,
    strength: 35,
    carLevel: 35,
    budget: 135000000,
    competitivenessVerdict: 'Raça americana no paddock',
    boardPressure: 'Alta',
    difficulty: 'Muito Difícil',
    initialObjective: 'Conquistar respeitabilidade e os primeiros top 10 no ano',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'Dinastia campeã da IndyCar e da Fórmula 1 construída por Mario e Michael Andretti.',
    currentSituation: 'Colton Herta e Felipe Drugovich no comando de uma nova força americana.',
    logoUrl: getTeamLogoUrl('andretti'),
    headquarters: 'Fishers, Indiana, EUA & Silverstone, Reino Unido',
    category: 'Nova Construtora Oficial 2026',
    specialTraits: [
      'DNA da Família Andretti',
      'Sede Moderna Fishers',
      'Foco em Pilotos de Coragem',
    ],
    carRating: 56,
    engineeringRating: 64,
    operationsRating: 66,
    prestigeRating: 84,
    cultureRating: 81,
    potentialRating: 86,
    driver1: {
      name: 'Colton Herta',
      nationality: 'Estados Unidos',
      flag: '🇺🇸',
      age: 25,
      speed: 80,
      consistency: 77,
      rain: 78,
      defense: 78,
      salary: 8000000,
    },
    driver2: {
      name: 'Felipe Drugovich',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 25,
      speed: 80,
      consistency: 80,
      rain: 81,
      defense: 78,
      salary: 7500000,
    },
    reserveDriver: {
      name: 'Pietro Fittipaldi',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 29,
      speed: 76,
      consistency: 77,
      rain: 76,
      defense: 75,
      salary: 3500000,
    },
  },

  // 16. BYD
  {
    key: 'byd',
    name: 'BYD Formula E-Tech',
    shortName: 'BYD',
    country: 'China',
    flag: '🇨🇳',
    color: '#0062A8',
    engine: 'Mercedes',
    strengthRating: 4.5,
    strength: 45,
    carLevel: 45,
    budget: 160000000,
    competitivenessVerdict: 'Pioneira em eletrificação de ponta',
    boardPressure: 'Média',
    difficulty: 'Desafiadora',
    initialObjective: 'Aproveitar a fatia elétrica 50/50 e surpreender em pistas de alta tração',
    infrastructureRating: 4,
    financesRating: 5,
    historySummary:
      'Maior fabricante mundial de veículos eletrificados entrando com investimento maciço.',
    currentSituation:
      'Guanyu Zhou lidera a bandeira chinesa com forte apoio tecnológico de baterias.',
    logoUrl: getTeamLogoUrl('byd'),
    headquarters: 'Shenzhen, China',
    category: 'Escuderia Convidada / Reserva FIA',
    specialTraits: [
      'Tecnologia de Bateria Blade',
      'Orçamento Massivo de P&D',
      'Eficiência Térmica Elétrica',
    ],
    carRating: 66,
    engineeringRating: 72,
    operationsRating: 70,
    prestigeRating: 76,
    cultureRating: 77,
    potentialRating: 85,
    driver1: {
      name: 'Zhou Guanyu',
      nationality: 'China',
      flag: '🇨🇳',
      age: 26,
      speed: 78,
      consistency: 80,
      rain: 77,
      defense: 79,
      salary: 7000000,
    },
    driver2: {
      name: 'Mitch Evans',
      nationality: 'Nova Zelândia',
      flag: '🇳🇿',
      age: 31,
      speed: 80,
      consistency: 81,
      rain: 82,
      defense: 80,
      salary: 6000000,
    },
    reserveDriver: {
      name: 'Nick Cassidy',
      nationality: 'Nova Zelândia',
      flag: '🇳🇿',
      age: 31,
      speed: 79,
      consistency: 80,
      rain: 81,
      defense: 79,
      salary: 3500000,
    },
  },

  // 17. Penske
  {
    key: 'penske',
    name: 'Team Penske F1',
    shortName: 'Penske',
    country: 'EUA',
    flag: '🇺🇸',
    color: '#E01E26',
    engine: 'Ford',
    strengthRating: 5.0,
    strength: 50,
    carLevel: 50,
    budget: 155000000,
    competitivenessVerdict: 'O padrão ouro do automobilismo norte-americano',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Execução de boxes perfeita e pontos consistentes',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'A equipe de Roger Penske já venceu na F1 nos anos 70 e dominou a Indy e Daytona.',
    currentSituation: 'Josef Newgarden e Scott McLaughlin trazem a disciplina lendária do Capitão.',
    logoUrl: getTeamLogoUrl('penske'),
    headquarters: 'Mooresville, Carolina do Norte, EUA',
    category: 'Escuderia Convidada / Reserva FIA',
    specialTraits: [
      'Disciplina Militar do Capitão',
      'Perfeição de Pitstop',
      'Metodologia Indy/IMSA',
    ],
    carRating: 69,
    engineeringRating: 74,
    operationsRating: 82,
    prestigeRating: 85,
    cultureRating: 86,
    potentialRating: 80,
    driver1: {
      name: 'Josef Newgarden',
      nationality: 'Estados Unidos',
      flag: '🇺🇸',
      age: 35,
      speed: 81,
      consistency: 83,
      rain: 78,
      defense: 82,
      salary: 8000000,
    },
    driver2: {
      name: 'Scott McLaughlin',
      nationality: 'Nova Zelândia',
      flag: '🇳🇿',
      age: 32,
      speed: 80,
      consistency: 81,
      rain: 81,
      defense: 80,
      salary: 7000000,
    },
    reserveDriver: {
      name: 'Will Power',
      nationality: 'Austrália',
      flag: '🇦🇺',
      age: 44,
      speed: 80,
      consistency: 79,
      rain: 78,
      defense: 81,
      salary: 4000000,
    },
  },

  // 18. Lotus
  {
    key: 'lotus',
    name: 'Team Lotus Classic',
    shortName: 'Lotus',
    country: 'Reino Unido',
    flag: '🇬🇧',
    color: '#004225',
    engine: 'Mercedes',
    strengthRating: 4.6,
    strength: 46,
    carLevel: 46,
    budget: 145000000,
    competitivenessVerdict: 'Inovação aerodinâmica e lenda dourada',
    boardPressure: 'Média',
    difficulty: 'Desafiadora',
    initialObjective: 'Honrar o preto e dourado no pelotão intermediário',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary: '7 títulos de construtores de Colin Chapman. O berço do efeito solo na F1.',
    currentSituation: 'Alexander Rossi e Callum Ilott na missão de reviver a glória britânica.',
    logoUrl: getTeamLogoUrl('lotus'),
    headquarters: 'Hethel, Norfolk, Reino Unido',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: ['Legado de Colin Chapman', 'Leveza Estrutural', 'Mística Preto e Dourado'],
    carRating: 67,
    engineeringRating: 73,
    operationsRating: 68,
    prestigeRating: 94,
    cultureRating: 85,
    potentialRating: 78,
    driver1: {
      name: 'Alexander Rossi',
      nationality: 'Estados Unidos',
      flag: '🇺🇸',
      age: 34,
      speed: 79,
      consistency: 80,
      rain: 80,
      defense: 80,
      salary: 6000000,
    },
    driver2: {
      name: 'Oliver Rowland',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 33,
      speed: 79,
      consistency: 79,
      rain: 81,
      defense: 79,
      salary: 5000000,
    },
    reserveDriver: {
      name: 'Jake Dennis',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 30,
      speed: 78,
      consistency: 79,
      rain: 78,
      defense: 78,
      salary: 3000000,
    },
  },

  // 19. Toyota
  {
    key: 'toyota',
    name: 'Toyota Gazoo Racing F1',
    shortName: 'Toyota',
    country: 'Japão',
    flag: '🇯🇵',
    color: '#EB0A1E',
    engine: 'Mercedes', // Conforme especificado pelo usuário na tabela (Toyota com UP Mercedes)
    strengthRating: 6.2,
    strength: 62,
    carLevel: 62,
    budget: 180000000,
    competitivenessVerdict: 'Retorno com força total e motor Mercedes',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Disputar o Top 5 de construtores e pódios regulares',
    infrastructureRating: 5,
    financesRating: 5,
    historySummary:
      'Gigante japonesa sediada em Colônia, multicampeã do WEC e WRC retornando à F1.',
    currentSituation: 'Ryo Hirakawa e Alex Palou formam uma dupla cirúrgica e hipercompetitiva.',
    logoUrl: undefined, // Toyota sem logo no dropbox -> estilizada
    headquarters: 'Colônia, Alemanha & Toyota City, Japão',
    category: 'Escuderia Convidada / Reserva FIA',
    specialTraits: ['Estrutura Hi-Tech de Colônia', 'Kaizen de Produção', 'Campeã WEC & WRC'],
    carRating: 75,
    engineeringRating: 82,
    operationsRating: 80,
    prestigeRating: 91,
    cultureRating: 88,
    potentialRating: 87,
    driver1: {
      name: 'Alex Palou',
      nationality: 'Espanha',
      flag: '🇪🇸',
      age: 28,
      speed: 86,
      consistency: 88,
      rain: 83,
      defense: 85,
      salary: 15000000,
    },
    driver2: {
      name: 'Ryo Hirakawa',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 32,
      speed: 80,
      consistency: 81,
      rain: 80,
      defense: 80,
      salary: 6000000,
    },
    reserveDriver: {
      name: 'Sebastien Buemi',
      nationality: 'Suíça',
      flag: '🇨🇭',
      age: 37,
      speed: 79,
      consistency: 82,
      rain: 83,
      defense: 80,
      salary: 4000000,
    },
  },

  // 20. Benetton
  {
    key: 'benetton',
    name: 'Benetton Formula',
    shortName: 'Benetton',
    country: 'Itália',
    flag: '🇮🇹',
    color: '#00A859',
    engine: 'Ford',
    strengthRating: 4.9,
    strength: 49,
    carLevel: 49,
    budget: 145000000,
    competitivenessVerdict: 'Cores vibrantes e arrojo dos anos 90',
    boardPressure: 'Média',
    difficulty: 'Média',
    initialObjective: 'Ser a pedra no sapato dos grandes no pelotão intermediário',
    infrastructureRating: 3,
    financesRating: 4,
    historySummary: 'Bicampeã com Michael Schumacher e Flavio Briatore em 1994 e 1995.',
    currentSituation: 'Mick Schumacher carrega o legado da família com garra.',
    logoUrl: getTeamLogoUrl('benetton'),
    headquarters: 'Enstone, Reino Unido & Treviso, Itália',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Ousadia Técnica Briatore',
      'Marketing Global United Colors',
      'Herança de Títulos Schumacher',
    ],
    carRating: 68,
    engineeringRating: 71,
    operationsRating: 70,
    prestigeRating: 87,
    cultureRating: 82,
    potentialRating: 77,
    driver1: {
      name: 'Mick Schumacher',
      nationality: 'Alemanha',
      flag: '🇩🇪',
      age: 26,
      speed: 80,
      consistency: 79,
      rain: 81,
      defense: 80,
      salary: 7000000,
    },
    driver2: {
      name: 'Theo Pourchaire',
      nationality: 'França',
      flag: '🇫🇷',
      age: 22,
      speed: 80,
      consistency: 79,
      rain: 78,
      defense: 78,
      salary: 5000000,
    },
    reserveDriver: {
      name: 'Richard Verschoor',
      nationality: 'Holanda',
      flag: '🇳🇱',
      age: 25,
      speed: 77,
      consistency: 77,
      rain: 77,
      defense: 76,
      salary: 3000000,
    },
  },

  // 21. Copersucar
  {
    key: 'copersucar',
    name: 'Copersucar Fittipaldi',
    shortName: 'Copersucar',
    country: 'Brasil',
    flag: '🇧🇷',
    color: '#FED100',
    engine: 'Ford',
    strengthRating: 4.4,
    strength: 44,
    carLevel: 44,
    budget: 138000000,
    competitivenessVerdict: 'Orgulho nacional brasileiro',
    boardPressure: 'Alta',
    difficulty: 'Desafiadora',
    initialObjective: 'Levar a torcida verde e amarela de volta aos pontos',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary:
      'O único carro brasileiro da história da Fórmula 1, fundado pelos irmãos Fittipaldi.',
    currentSituation: 'Pietro Fittipaldi e Rafael Câmara honram as cores nacionais.',
    logoUrl: getTeamLogoUrl('copersucar'),
    headquarters: 'São Paulo, Brasil & Reading, Reino Unido',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Pioneirismo Brasileiro',
      'Paixão Torcida Canarinho',
      'Garra dos Irmãos Fittipaldi',
    ],
    carRating: 64,
    engineeringRating: 68,
    operationsRating: 67,
    prestigeRating: 86,
    cultureRating: 90,
    potentialRating: 75,
    driver1: {
      name: 'Pietro Fittipaldi',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 29,
      speed: 79,
      consistency: 80,
      rain: 79,
      defense: 79,
      salary: 6000000,
    },
    driver2: {
      name: 'Rafael Câmara',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 20,
      speed: 81,
      consistency: 78,
      rain: 80,
      defense: 78,
      salary: 4000000,
    },
    reserveDriver: {
      name: 'Caio Collet',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 23,
      speed: 78,
      consistency: 77,
      rain: 79,
      defense: 77,
      salary: 3000000,
    },
  },

  // 22. Alfa Romeo
  {
    key: 'alfaromeo',
    name: 'Alfa Romeo F1 Team',
    shortName: 'Alfa Romeo',
    country: 'Itália',
    flag: '🇮🇹',
    color: '#900000',
    engine: 'Ferrari',
    strengthRating: 4.7,
    strength: 47,
    carLevel: 47,
    budget: 142000000,
    competitivenessVerdict: 'Tradição secular do Quadrifoglio',
    boardPressure: 'Média',
    difficulty: 'Desafiadora',
    initialObjective: 'Pontuar com constância e brigar pela liderança do pelotão C',
    infrastructureRating: 4,
    financesRating: 3,
    historySummary:
      'Venceu os dois primeiros campeonatos mundiais da história da F1 (1950 com Farina e 1951 com Fangio).',
    currentSituation: 'Equipe italo-suíça combinando tradição de Maranello e eficiência.',
    logoUrl: getTeamLogoUrl('alfaromeo'),
    headquarters: 'Arese & Turim, Itália',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Quadrifoglio Verde Histórico',
      'Campeã Inaugural F1 1950-1951',
      'DNA Puro Cuore Sportivo',
    ],
    carRating: 67,
    engineeringRating: 70,
    operationsRating: 71,
    prestigeRating: 88,
    cultureRating: 85,
    potentialRating: 76,
    driver1: {
      name: 'Antonio Fuoco',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 29,
      speed: 80,
      consistency: 82,
      rain: 81,
      defense: 80,
      salary: 6500000,
    },
    driver2: {
      name: 'Alessandro Pier Guidi',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 42,
      speed: 79,
      consistency: 84,
      rain: 82,
      defense: 81,
      salary: 5500000,
    },
    reserveDriver: {
      name: 'James Calado',
      nationality: 'Reino Unido',
      flag: '🇬🇧',
      age: 36,
      speed: 78,
      consistency: 80,
      rain: 79,
      defense: 79,
      salary: 3500000,
    },
  },

  // 23. AlphaTauri
  {
    key: 'alphatauri',
    name: 'Scuderia AlphaTauri',
    shortName: 'AlphaTauri',
    country: 'Itália',
    flag: '🇮🇹',
    color: '#00293F',
    engine: 'Ford',
    strengthRating: 5.1,
    strength: 51,
    carLevel: 51,
    budget: 150000000,
    competitivenessVerdict: 'Estilo e agressividade jovem',
    boardPressure: 'Média',
    difficulty: 'Média',
    initialObjective: 'Qualificações agressivas e pontos frequentes',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary:
      'A marca fashion da Red Bull que venceu em Monza em 2008 (Vettel) e 2020 (Gasly).',
    currentSituation: 'Zane Maloney e Ayumu Iwasa aceleram com motor Red Bull Ford.',
    logoUrl: getTeamLogoUrl('alphatauri'),
    headquarters: 'Faenza, Itália',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: ['Vencedora Mítica em Monza', 'Estilo Premium Fashion', 'Celeiro Faenza'],
    carRating: 70,
    engineeringRating: 73,
    operationsRating: 74,
    prestigeRating: 80,
    cultureRating: 81,
    potentialRating: 78,
    driver1: {
      name: 'Zane Maloney',
      nationality: 'Barbados',
      flag: '🇧🇧',
      age: 22,
      speed: 80,
      consistency: 79,
      rain: 79,
      defense: 79,
      salary: 5000000,
    },
    driver2: {
      name: 'Ayumu Iwasa',
      nationality: 'Japão',
      flag: '🇯🇵',
      age: 24,
      speed: 80,
      consistency: 79,
      rain: 78,
      defense: 78,
      salary: 4500000,
    },
    reserveDriver: {
      name: 'Dino Beganovic',
      nationality: 'Suécia',
      flag: '🇸🇪',
      age: 22,
      speed: 77,
      consistency: 76,
      rain: 76,
      defense: 76,
      salary: 2800000,
    },
  },

  // 24. Fittipaldi
  {
    key: 'fittipaldi',
    name: 'Fittipaldi Racing Team',
    shortName: 'Fittipaldi',
    country: 'Brasil',
    flag: '🇧🇷',
    color: '#008744',
    engine: 'Ferrari',
    strengthRating: 4.3,
    strength: 43,
    carLevel: 43,
    budget: 135000000,
    competitivenessVerdict: 'Herança campeã de Emerson e Wilson',
    boardPressure: 'Média',
    difficulty: 'Desafiadora',
    initialObjective: 'Evoluir o chassi e colocar pilotos brasileiros no pódio',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary:
      'A escuderia que desafiou os gigantes europeus com engenhosidade e coração latino.',
    currentSituation: 'Felipe Nasr e Pipo Derani lideram uma operação guerreira.',
    logoUrl: getTeamLogoUrl('fittipaldi'),
    headquarters: 'São Paulo, Brasil & Banbury, Reino Unido',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Herança Bicampeã de Emerson',
      'Coração e Garra Brasileira',
      'Espírito Independente',
    ],
    carRating: 63,
    engineeringRating: 66,
    operationsRating: 67,
    prestigeRating: 85,
    cultureRating: 89,
    potentialRating: 74,
    driver1: {
      name: 'Felipe Nasr',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 33,
      speed: 81,
      consistency: 82,
      rain: 82,
      defense: 81,
      salary: 7000000,
    },
    driver2: {
      name: 'Pipo Derani',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 32,
      speed: 80,
      consistency: 81,
      rain: 81,
      defense: 82,
      salary: 6000000,
    },
    reserveDriver: {
      name: 'Nelson Piquet Jr',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 40,
      speed: 78,
      consistency: 80,
      rain: 80,
      defense: 80,
      salary: 3500000,
    },
  },

  // 25. Jordan
  {
    key: 'jordan',
    name: 'Jordan Grand Prix',
    shortName: 'Jordan',
    country: 'Irlanda',
    flag: '🇮🇪',
    color: '#FFD700',
    engine: 'Honda',
    strengthRating: 4.8,
    strength: 48,
    carLevel: 48,
    budget: 140000000,
    competitivenessVerdict: 'Rock’n’roll, chuva e vitórias épicas',
    boardPressure: 'Baixa',
    difficulty: 'Desafiadora',
    initialObjective: 'Dar show na pista e roubar vitórias em corridas molhadas',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary:
      'A equipe amarela de Eddie Jordan que lançou Michael Schumacher e Rubens Barrichello.',
    currentSituation:
      'Rubens Barrichello como mentor e Daniel Ricciardo trazendo o sorriso vencedor.',
    logoUrl: getTeamLogoUrl('jordan'),
    headquarters: 'Silverstone, Northamptonshire, Reino Unido',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Especialista em Pistas Molhadas',
      'Carisma Rock’n’Roll Eddie Jordan',
      'Oportunismo Tático',
    ],
    carRating: 68,
    engineeringRating: 72,
    operationsRating: 70,
    prestigeRating: 88,
    cultureRating: 90,
    potentialRating: 76,
    driver1: {
      name: 'Daniel Ricciardo',
      nationality: 'Austrália',
      flag: '🇦🇺',
      age: 36,
      speed: 82,
      consistency: 81,
      rain: 84,
      defense: 83,
      salary: 11000000,
    },
    driver2: {
      name: 'Alex Dunne',
      nationality: 'Irlanda',
      flag: '🇮🇪',
      age: 20,
      speed: 79,
      consistency: 78,
      rain: 80,
      defense: 77,
      salary: 4000000,
    },
    reserveDriver: {
      name: 'Rubens Barrichello',
      nationality: 'Brasil',
      flag: '🇧🇷',
      age: 53,
      speed: 78,
      consistency: 85,
      rain: 85,
      defense: 81,
      salary: 3000000,
    },
  },

  // 26. Renault
  {
    key: 'renault',
    name: 'Renault F1 Team',
    shortName: 'Renault',
    country: 'França',
    flag: '🇫🇷',
    color: '#FFF500',
    engine: 'Mercedes',
    strengthRating: 5.3,
    strength: 53,
    carLevel: 53,
    budget: 155000000,
    competitivenessVerdict: 'Força industrial e pioneira do turbo',
    boardPressure: 'Alta',
    difficulty: 'Média',
    initialObjective: 'Top 6 regular e disputar pódios nas corridas europeias',
    infrastructureRating: 4,
    financesRating: 4,
    historySummary: 'Introduziu os motores turbo na F1 e venceu mundiais com Fernando Alonso.',
    currentSituation: 'Jean-Éric Vergne e Stoffel Vandoorne formam uma dupla cirúrgica.',
    logoUrl: getTeamLogoUrl('renault'),
    headquarters: 'Viry-Châtillon & Enstone, França / Reino Unido',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Pioneirismo do Motor Turbo',
      'Bicampeã Mundial Alonso 2005-2006',
      'Potência Industrial Francesa',
    ],
    carRating: 72,
    engineeringRating: 76,
    operationsRating: 74,
    prestigeRating: 89,
    cultureRating: 83,
    potentialRating: 79,
    driver1: {
      name: 'Jean Eric Vergne',
      nationality: 'França',
      flag: '🇫🇷',
      age: 35,
      speed: 81,
      consistency: 82,
      rain: 83,
      defense: 82,
      salary: 7500000,
    },
    driver2: {
      name: 'Stoffel Vandoorne',
      nationality: 'Bélgica',
      flag: '🇧🇪',
      age: 33,
      speed: 80,
      consistency: 82,
      rain: 81,
      defense: 80,
      salary: 6500000,
    },
    reserveDriver: {
      name: 'Victor Martins',
      nationality: 'França',
      flag: '🇫🇷',
      age: 24,
      speed: 78,
      consistency: 77,
      rain: 78,
      defense: 77,
      salary: 3000000,
    },
  },

  // 27. Sauber
  {
    key: 'sauber',
    name: 'Sauber Motorsport',
    shortName: 'Sauber',
    country: 'Suíça',
    flag: '🇨🇭',
    color: '#00E700',
    engine: 'Ferrari',
    strengthRating: 4.1,
    strength: 41,
    carLevel: 41,
    budget: 140000000,
    competitivenessVerdict: 'Precisão suíça de Hinwil',
    boardPressure: 'Baixa',
    difficulty: 'Desafiadora',
    initialObjective: 'Evolução aerodinâmica e somar pontos consistentes',
    infrastructureRating: 4,
    financesRating: 3,
    historySummary: 'Mais de 30 anos de permanência e garra operando em Hinwil na Suíça.',
    currentSituation: 'Felipe Drugovich e Robert Kubica aceleram com suporte da fábrica.',
    logoUrl: getTeamLogoUrl('sauber'),
    headquarters: 'Hinwil, Zurique, Suíça',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'Túnel de Vento de Hinwil',
      'Precisão Construtiva Suíça',
      'Celeiro de Raikkonen e Massa',
    ],
    carRating: 62,
    engineeringRating: 70,
    operationsRating: 68,
    prestigeRating: 82,
    cultureRating: 81,
    potentialRating: 75,
    driver1: {
      name: 'Robert Kubica',
      nationality: 'Polônia',
      flag: '🇵🇱',
      age: 41,
      speed: 80,
      consistency: 83,
      rain: 84,
      defense: 82,
      salary: 6000000,
    },
    driver2: {
      name: 'Leonardo Fornaroli',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 21,
      speed: 79,
      consistency: 80,
      rain: 79,
      defense: 78,
      salary: 4000000,
    },
    reserveDriver: {
      name: 'Marcus Ericsson',
      nationality: 'Suécia',
      flag: '🇸🇪',
      age: 35,
      speed: 77,
      consistency: 79,
      rain: 78,
      defense: 78,
      salary: 3000000,
    },
  },

  // 28. Toleman (Logo Tolerman, Nome Oficial TOLEMAN)
  {
    key: 'toleman',
    name: 'Toleman Motorsport',
    shortName: 'Toleman',
    country: 'Reino Unido',
    flag: '🇬🇧',
    color: '#003399',
    engine: 'Ferrari',
    strengthRating: 4.0,
    strength: 40,
    carLevel: 40,
    budget: 135000000,
    competitivenessVerdict: 'A escuderia que revelou Ayrton Senna',
    boardPressure: 'Baixa',
    difficulty: 'Muito Difícil',
    initialObjective: 'Construir a lenda do azarão e buscar pódios milagrosos na chuva',
    infrastructureRating: 3,
    financesRating: 3,
    historySummary:
      'Entrou para a eternidade quando Ayrton Senna quase venceu o GP de Mônaco de 1984 sob temporal.',
    currentSituation: 'Gabriel Bortoleto e Andrea Kimi Antonelli no radar da paixão britânica.',
    logoUrl: getTeamLogoUrl('toleman'),
    headquarters: 'Witney, Oxfordshire, Reino Unido',
    category: 'Escuderia Histórica / Reserva FIA',
    specialTraits: [
      'O Berço de Ayrton Senna',
      'Chassi Milagroso na Chuva',
      'Espírito Indomável de Garagista',
    ],
    carRating: 61,
    engineeringRating: 65,
    operationsRating: 66,
    prestigeRating: 88,
    cultureRating: 89,
    potentialRating: 73,
    driver1: {
      name: 'Jack Doohan',
      nationality: 'Austrália',
      flag: '🇦🇺',
      age: 23,
      speed: 80,
      consistency: 79,
      rain: 81,
      defense: 79,
      salary: 5500000,
    },
    driver2: {
      name: 'Nicola Tsolov',
      nationality: 'Bulgária',
      flag: '🇧🇬',
      age: 19,
      speed: 79,
      consistency: 77,
      rain: 78,
      defense: 77,
      salary: 3500000,
    },
    reserveDriver: {
      name: 'Gabriel Mini',
      nationality: 'Itália',
      flag: '🇮🇹',
      age: 20,
      speed: 78,
      consistency: 77,
      rain: 77,
      defense: 76,
      salary: 2800000,
    },
  },
]

// O Grid Oficial de 2026: 12 Equipes Consagradas do Cenário 2026
// Mercedes, Ferrari, McLaren, Red Bull, Racing Bulls, Alpine, Audi, Haas, Williams, Aston Martin, Andretti, Cadillac
export const OFFICIAL_2026_GRID_KEYS = [
  'mercedes',
  'ferrari',
  'mclaren',
  'redbull',
  'racingbulls',
  'alpine',
  'audi',
  'haas',
  'williams',
  'astonmartin',
  'andretti',
  'cadillac',
]

export function getOfficial2026GridTeams(): GridTeamDefinition[] {
  return OFFICIAL_2026_GRID_KEYS.map((k) => {
    const t = ALL_GRID_TEAMS_DATABASE.find((item) => item.key === k)
    if (!t) throw new Error(`Equipe oficial 2026 não encontrada: ${k}`)
    return t
  })
}
