import { ManagerProfile } from '@/types/career-wizard'
import { MANAGER_AVATAR_ASSETS } from './lobby-assets'

/**
 * Tabela base de 28 atributos do Manager definida no documento oficial Manager.pdf:
 * Liderança, Gestão de Pessoas, Gestão de Pilotos, Visão Estratégica, Tomada de Decisão,
 * Gestão de Corrida, Conhecimento Técnico, Desenvolvimento do Carro, Gestão de Projeto,
 * Gestão Financeira, Negociação, Captação Comercial, Influência Política, Reputação,
 * Desenvolvimento de Talentos, Gestão de Crise, Comunicação, Pressão, Adaptabilidade,
 * Organização, Disciplina, Inovação, Agressividade Gerencial, Lealdade, Ambição, Ego,
 * Temperamento, Espírito de Equipe, Resiliência.
 */
export const BASE_MANAGER_ATTRIBUTES: Record<string, string> = {
  lideranca: 'Liderança',
  gestao_pessoas: 'Gestão de Pessoas',
  gestao_pilotos: 'Gestão de Pilotos',
  visao_estrategica: 'Visão Estratégica',
  tomada_decisao: 'Tomada de Decisão',
  gestao_corrida: 'Gestão de Corrida',
  conhecimento_tecnico: 'Conhecimento Técnico',
  desenvolvimento_carro: 'Desenvolvimento do Carro',
  gestao_projeto: 'Gestão de Projeto',
  gestao_financeira: 'Gestão Financeira',
  negociacao: 'Negociação',
  captacao_comercial: 'Captação Comercial',
  influencia_politica: 'Influência Política',
  reputacao: 'Reputação',
  desenvolvimento_talentos: 'Desenvolvimento de Talentos',
  gestao_crise: 'Gestão de Crise',
  comunicacao: 'Comunicação',
  pressao: 'Pressão',
  adaptabilidade: 'Adaptabilidade',
  organizacao: 'Organização',
  disciplina: 'Disciplina',
  inovacao: 'Inovação',
  agressividade_gerencial: 'Agressividade Gerencial',
  lealdade: 'Lealdade',
  ambicao: 'Ambição',
  ego: 'Ego',
  temperamento: 'Temperamento',
  espirito_equipe: 'Espírito de Equipe',
  resiliencia: 'Resiliência',
}

/**
 * Os 6 arquétipos oficiais de Manager extraídos do documento Manager.pdf
 */
export const MANAGER_PROFILES: ManagerProfile[] = [
  {
    id: 'estrategista',
    number: 1,
    title: 'O Estrategista',
    slug: 'estrategista',
    archetype: 'Estrategista',
    specialty: 'Planejamento',
    style: 'Analítico, racional, longo prazo',
    description:
      'Mestre na leitura de cenários de corrida, pit stops cirúrgicos e alocação financeira de longo prazo. Opera com frieza sob pressão, mas sua postura focada em números pode exigir atenção redobrada no relacionamento humano com pilotos e departamento de pista.',
    bonuses: [
      { attribute: 'Estratégia', value: 10 },
      { attribute: 'Finanças', value: 8 },
      { attribute: 'Negociação', value: 8 },
    ],
    weakness: {
      attribute: 'Gestão de Pessoas',
      value: -5,
    },
    avatarId: 'estrategista',
    avatarFilename: '01-Estrategista.png',
    avatarUrl: MANAGER_AVATAR_ASSETS[0].dropboxUrl,
    baseAttributes: {
      lideranca: 75,
      gestao_pessoas: 60,
      gestao_pilotos: 68,
      visao_estrategica: 92,
      tomada_decisao: 88,
      gestao_corrida: 90,
      conhecimento_tecnico: 74,
      desenvolvimento_carro: 72,
      gestao_projeto: 80,
      gestao_financeira: 88,
      negociacao: 86,
      captacao_comercial: 70,
      influencia_politica: 65,
      reputacao: 78,
      desenvolvimento_talentos: 70,
      gestao_crise: 82,
      comunicacao: 72,
      pressao: 88,
      adaptabilidade: 84,
      organizacao: 86,
      disciplina: 90,
      inovacao: 76,
      agressividade_gerencial: 60,
      lealdade: 80,
      ambicao: 78,
      ego: 55,
      temperamento: 85,
      espirito_equipe: 70,
      resiliencia: 84,
    },
  },
  {
    id: 'competidor',
    number: 2,
    title: 'O Competidor',
    slug: 'competidor',
    archetype: 'Competidor',
    specialty: 'Performance',
    style: 'Agressivo, intenso, resultado imediato',
    description:
      'Espírito combativo que incendeia a garagem e extrai até o último décimo de segundo dos pilotos no domingo. Exige vitória imediata e tem faro aguçado para a pista, embora sua intensidade e aversão à diplomacia política possam desgastar negociações nos bastidores da FIA.',
    bonuses: [
      { attribute: 'Pilotos', value: 10 },
      { attribute: 'Desempenho em Corrida', value: 8 },
      { attribute: 'Motivação', value: 5 },
    ],
    weakness: {
      attribute: 'Relacionamento Político',
      value: -5,
    },
    avatarId: 'competidor',
    avatarFilename: '02-Competidor.png',
    avatarUrl: MANAGER_AVATAR_ASSETS[1].dropboxUrl,
    baseAttributes: {
      lideranca: 88,
      gestao_pessoas: 72,
      gestao_pilotos: 90,
      visao_estrategica: 70,
      tomada_decisao: 85,
      gestao_corrida: 88,
      conhecimento_tecnico: 72,
      desenvolvimento_carro: 75,
      gestao_projeto: 68,
      gestao_financeira: 65,
      negociacao: 74,
      captacao_comercial: 72,
      influencia_politica: 55,
      reputacao: 82,
      desenvolvimento_talentos: 78,
      gestao_crise: 76,
      comunicacao: 80,
      pressao: 92,
      adaptabilidade: 75,
      organizacao: 70,
      disciplina: 75,
      inovacao: 80,
      agressividade_gerencial: 92,
      lealdade: 82,
      ambicao: 95,
      ego: 80,
      temperamento: 65,
      espirito_equipe: 82,
      resiliencia: 88,
    },
  },
  {
    id: 'engenheiro',
    number: 3,
    title: 'O Engenheiro',
    slug: 'engenheiro',
    archetype: 'Engenheiro',
    specialty: 'Tecnologia',
    style: 'Técnico, metódico, desenvolvimento',
    description:
      'Gênio da física aerodinâmica e das unidades de potência híbridas 50/50. Transforma dados de telemetria em saltos quânticos de confiabilidade e peças de ponta. Prefere o túnel de vento ao microfone e pode enfrentar dificuldades quando pilotos entram em atrito pessoal.',
    bonuses: [
      { attribute: 'Desenvolvimento/P&D', value: 12 },
      { attribute: 'Unidade de Potência', value: 10 },
      { attribute: 'Confiabilidade', value: 8 },
    ],
    weakness: {
      attribute: 'Gestão de Pilotos',
      value: -5,
    },
    avatarId: 'engenheiro',
    avatarFilename: '03-Engenheiro.png',
    avatarUrl: MANAGER_AVATAR_ASSETS[2].dropboxUrl,
    baseAttributes: {
      lideranca: 74,
      gestao_pessoas: 66,
      gestao_pilotos: 58,
      visao_estrategica: 84,
      tomada_decisao: 76,
      gestao_corrida: 72,
      conhecimento_tecnico: 96,
      desenvolvimento_carro: 95,
      gestao_projeto: 88,
      gestao_financeira: 74,
      negociacao: 68,
      captacao_comercial: 62,
      influencia_politica: 65,
      reputacao: 80,
      desenvolvimento_talentos: 72,
      gestao_crise: 74,
      comunicacao: 64,
      pressao: 78,
      adaptabilidade: 85,
      organizacao: 90,
      disciplina: 92,
      inovacao: 94,
      agressividade_gerencial: 65,
      lealdade: 86,
      ambicao: 80,
      ego: 60,
      temperamento: 82,
      espirito_equipe: 76,
      resiliencia: 82,
    },
  },
  {
    id: 'gestor',
    number: 4,
    title: 'O Gestor',
    slug: 'gestor',
    archetype: 'Gestor',
    specialty: 'Organização',
    style: 'Equilibrado, estável, consistente',
    description:
      'Garante que cada engrenagem da fábrica funcione em harmonia milimétrica. Cria ambientes de trabalho serenos, reduz desperdício de teto de gastos e desenvolve o chassi com previsibilidade. É cauteloso por natureza, preferindo a segurança da pontuação estável a apostas arrojadas.',
    bonuses: [
      { attribute: 'Gestão de Pessoas', value: 10 },
      { attribute: 'Estabilidade', value: 8 },
      { attribute: 'Desenvolvimento', value: 6 },
    ],
    weakness: {
      attribute: 'Tolerância a Riscos',
      value: -5,
    },
    avatarId: 'gestor',
    avatarFilename: '04-Gestor.png',
    avatarUrl: MANAGER_AVATAR_ASSETS[3].dropboxUrl,
    baseAttributes: {
      lideranca: 86,
      gestao_pessoas: 92,
      gestao_pilotos: 84,
      visao_estrategica: 80,
      tomada_decisao: 82,
      gestao_corrida: 78,
      conhecimento_tecnico: 76,
      desenvolvimento_carro: 82,
      gestao_projeto: 92,
      gestao_financeira: 86,
      negociacao: 80,
      captacao_comercial: 76,
      influencia_politica: 78,
      reputacao: 84,
      desenvolvimento_talentos: 85,
      gestao_crise: 88,
      comunicacao: 86,
      pressao: 82,
      adaptabilidade: 78,
      organizacao: 95,
      disciplina: 94,
      inovacao: 70,
      agressividade_gerencial: 50,
      lealdade: 92,
      ambicao: 75,
      ego: 45,
      temperamento: 90,
      espirito_equipe: 92,
      resiliencia: 86,
    },
  },
  {
    id: 'empresario',
    number: 5,
    title: 'O Empresário',
    slug: 'empresario',
    archetype: 'Empresário',
    specialty: 'Negócios',
    style: 'Comercial, crescimento e oportunidades',
    description:
      'Atrai marcas multinacionais bilionárias para a pintura do carro e negocia contratos estelares no mercado de pilotos. Maximiza o caixa e o fluxo de receita da escuderia, porém delega o desenvolvimento técnico profundo da fábrica a terceiros, precisando de suporte de engenharia.',
    bonuses: [
      { attribute: 'Patrocínio/Receita', value: 12 },
      { attribute: 'Contratação de Talentos', value: 8 },
      { attribute: 'Marketing', value: 8 },
    ],
    weakness: {
      attribute: 'Desenvolvimento Técnico',
      value: -5,
    },
    avatarId: 'empresario',
    avatarFilename: '05-Empresário.png',
    avatarUrl: MANAGER_AVATAR_ASSETS[4].dropboxUrl,
    baseAttributes: {
      lideranca: 82,
      gestao_pessoas: 80,
      gestao_pilotos: 82,
      visao_estrategica: 86,
      tomada_decisao: 84,
      gestao_corrida: 74,
      conhecimento_tecnico: 55,
      desenvolvimento_carro: 60,
      gestao_projeto: 78,
      gestao_financeira: 96,
      negociacao: 94,
      captacao_comercial: 96,
      influencia_politica: 88,
      reputacao: 88,
      desenvolvimento_talentos: 80,
      gestao_crise: 80,
      comunicacao: 92,
      pressao: 85,
      adaptabilidade: 82,
      organizacao: 80,
      disciplina: 76,
      inovacao: 78,
      agressividade_gerencial: 85,
      lealdade: 70,
      ambicao: 94,
      ego: 75,
      temperamento: 78,
      espirito_equipe: 80,
      resiliencia: 84,
    },
  },
  {
    id: 'lider',
    number: 6,
    title: 'A Líder',
    slug: 'lider',
    archetype: 'Líder',
    specialty: 'Pessoas + negócios',
    style: 'Diplomática, agregadora e orientada a crescimento',
    description:
      'Combinação primorosa de visão comercial e inteligência relacional. Conquista investidores de peso, atrai talentos cobiçados e alinha departamentos inteiros sob um mesmo propósito vencedor. No entanto, sua sede de vitória cobra resultados rápidos, com baixa tolerância a temporadas mornas.',
    bonuses: [
      { attribute: 'Talentos/Contratações', value: 10 },
      { attribute: 'Patrocínio/Receita', value: 10 },
      { attribute: 'Organização/Processos', value: 6 },
    ],
    weakness: {
      attribute: 'Paciência com Resultados',
      value: -5,
    },
    avatarId: 'lider',
    avatarFilename: '06-Lider.png',
    avatarUrl: MANAGER_AVATAR_ASSETS[5].dropboxUrl,
    baseAttributes: {
      lideranca: 94,
      gestao_pessoas: 92,
      gestao_pilotos: 88,
      visao_estrategica: 90,
      tomada_decisao: 88,
      gestao_corrida: 82,
      conhecimento_tecnico: 68,
      desenvolvimento_carro: 75,
      gestao_projeto: 86,
      gestao_financeira: 90,
      negociacao: 92,
      captacao_comercial: 94,
      influencia_politica: 90,
      reputacao: 92,
      desenvolvimento_talentos: 90,
      gestao_crise: 88,
      comunicacao: 94,
      pressao: 88,
      adaptabilidade: 86,
      organizacao: 90,
      disciplina: 88,
      inovacao: 84,
      agressividade_gerencial: 80,
      lealdade: 82,
      ambicao: 92,
      ego: 65,
      temperamento: 75,
      espirito_equipe: 92,
      resiliencia: 88,
    },
  },
]

export function getManagerProfileById(id?: string): ManagerProfile {
  return MANAGER_PROFILES.find((p) => p.id === id || p.slug === id) || MANAGER_PROFILES[0]
}
