/**
 * Base de Dados Completa MBJ 2026 - 135 Pilotos
 * Organizados nos grupos:
 * - V (Valores exatos): id, nome, nacionalidade, idade, equipe_id, categoria, salário, contrato
 * - P (Faixas/Projeções): potencial (min-max), elegibilidade, homologação necessária (<18 / sem F1)
 * - O (Alimenta simulação): speed, consistency, rain, defense, physical_condition, morale, fatigue
 */

export interface MBJPilotData {
  id: string
  name: string
  nationality: string
  age: number
  category:
    | 'f1'
    | 'f2'
    | 'indycar'
    | 'indynxt'
    | 'formula_e'
    | 'nascar'
    | 'prototipos'
    | 'mercado'
    | 'f1_academy'
  role?: 'titular' | 'reserva'
  teamKey?: string
  teamName?: string
  speed: number
  consistency: number
  rain: number
  defense: number
  salaryUsd: number
  salaryBrl: number
  contractYears: number
  potentialMin: number
  potentialMax: number
  f1RacesCompleted: number
  superlicensePoints: number
  isAcademyProspect?: boolean
  photoFilename?: string
  notes?: string

  // Novos campos completos da Ficha MBJ 2026 (45 campos)
  // Identidade V
  birthDate?: string
  preferredNumber?: number
  eligibilityStatus?: string
  f1ExperienceTier?: string
  originSchema?: string
  statusScenario?: string
  biography?: string
  operatingTeam?: string
  supporterBrand?: string

  // 14 Atributos Esportivos P
  qualifying?: number
  racePace?: number
  start?: number
  overtake?: number
  tireManagement?: number
  energyManagement?: number
  feedback?: number
  pressure?: number
  concentration?: number
  resilience?: number

  // Personalidade P/V/O
  aggressiveness?: number // P
  ambition?: number // P
  loyalty?: number // P
  professionalism?: number // P
  temperament?: number // O (oculto, apenas simulação)
  reputation?: number // V
  globalPopularity?: number // V
  localPopularity?: number // V
  localMarket?: string // V

  // Estado P
  moraleState?: number // P (qualitativo para fora)
  confidence?: number // P (qualitativo para fora)
  physicalCondition?: number // P (qualitativo para fora)
  stress?: number // P (qualitativo para fora)
  adaptability?: number // P
  adaptationF1?: number // P
  adaptationCar?: number // P
  adaptationTeam?: number // P
  combinedAdaptation?: number | string
  learningRate?: string

  // Negociação
  minSalaryUsd?: number // O
  acceptsReserve?: boolean // O
  acceptedRoles?: string[] // O
  negotiationWeights?: {
    money?: number
    project?: number
    prestige?: number
    stability?: number
    role?: number
    relationship?: number
  } // O

  // Contrato P
  contractStart?: string
  contractEndYear?: number
  exitClauseUsd?: number
  winBonusUsd?: number
  hierarchyRole?: string
  contractNature?: string

  // Traços
  revealedTraits?: string[]

  // Estatísticas e Identidade Canônica FIA 01/01/2026
  permanentNumber?: number
  activeRaceNumber?: number
  f1Gps?: number
  f1Wins?: number
  f1Poles?: number
  f1Titles?: number
  baseAge2026?: number
}

export const USD_TO_BRL_RATE = 5.75

export const MBJ_2026_PILOTS: MBJPilotData[] = [
  // --- 1. TITULARES F1 2026 (22 pilotos - 11 equipes com Cadillac) ---
  {
    id: 'mbj-001',
    name: 'Max Verstappen',
    nationality: 'Holanda',
    age: 28,
    category: 'f1',
    role: 'titular',
    teamKey: 'red_bull',
    teamName: 'Red Bull Racing',
    speed: 98,
    consistency: 96,
    rain: 99,
    defense: 97,
    qualifying: 97,
    racePace: 98,
    start: 94,
    overtake: 96,
    tireManagement: 95,
    energyManagement: 94,
    feedback: 92,
    pressure: 98,
    concentration: 97,
    resilience: 96,
    aggressiveness: 88,
    ambition: 99,
    loyalty: 82,
    professionalism: 94,
    reputation: 99,
    globalPopularity: 98,
    localPopularity: 100,
    localMarket: 'NL',
    moraleState: 92,
    confidence: 96,
    physicalCondition: 98,
    stress: 18,
    adaptability: 96,
    adaptationF1: 99,
    adaptationCar: 95,
    adaptationTeam: 98,
    preferredNumber: 1,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Tetracampeão mundial de Fórmula 1 e recordista histórico de vitórias em uma única temporada. Piloto com velocidade pura avassaladora, controle sob chuva lendário e liderança técnica na Red Bull.',
    revealedTraits: [
      'Especialista em Chuva (TR01)',
      'Mestre da Classificação (TR02)',
      'Sangue Frio sob Pressão (TR10)',
    ],
    salaryUsd: 55000000,
    salaryBrl: 55000000 * USD_TO_BRL_RATE,
    contractYears: 3,
    exitClauseUsd: 120000000,
    winBonusUsd: 2000000,
    potentialMin: 97,
    potentialMax: 99,
    f1RacesCompleted: 205,
    superlicensePoints: 100,
    photoFilename: 'verstappen.webp',
  },
  {
    id: 'mbj-002',
    name: 'Liam Lawson',
    nationality: 'Nova Zelândia',
    age: 24,
    category: 'f1',
    role: 'titular',
    teamKey: 'red_bull',
    teamName: 'Red Bull Racing',
    speed: 84,
    consistency: 82,
    rain: 83,
    defense: 85,
    qualifying: 83,
    racePace: 84,
    start: 82,
    overtake: 85,
    tireManagement: 82,
    energyManagement: 81,
    feedback: 80,
    pressure: 82,
    concentration: 83,
    resilience: 84,
    aggressiveness: 72,
    ambition: 88,
    loyalty: 76,
    professionalism: 85,
    reputation: 74,
    globalPopularity: 62,
    localPopularity: 88,
    localMarket: 'NZ',
    moraleState: 75,
    confidence: 78,
    physicalCondition: 95,
    stress: 30,
    adaptability: 84,
    adaptationF1: 82,
    adaptationCar: 80,
    adaptationTeam: 82,
    preferredNumber: 30,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Graduado do programa Red Bull Junior. Conquistou pontos logo em suas primeiras corridas de substituição e agora assume assento titular em tempo integral.',
    revealedTraits: ['Combate Agressivo (TR09)', 'Adaptação Rápida (TR11)'],
    salaryUsd: 4000000,
    salaryBrl: 4000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    exitClauseUsd: 15000000,
    winBonusUsd: 500000,
    potentialMin: 85,
    potentialMax: 90,
    f1RacesCompleted: 11,
    superlicensePoints: 50,
    photoFilename: 'lawson.webp',
  },
  {
    id: 'mbj-003',
    name: 'Lewis Hamilton',
    nationality: 'Reino Unido',
    age: 41,
    category: 'f1',
    role: 'titular',
    teamKey: 'ferrari',
    teamName: 'Scuderia Ferrari',
    speed: 96,
    consistency: 95,
    rain: 97,
    defense: 95,
    qualifying: 95,
    racePace: 97,
    start: 92,
    overtake: 96,
    tireManagement: 98,
    energyManagement: 94,
    feedback: 96,
    pressure: 98,
    concentration: 96,
    resilience: 95,
    aggressiveness: 78,
    ambition: 98,
    loyalty: 88,
    professionalism: 97,
    reputation: 100,
    globalPopularity: 100,
    localPopularity: 98,
    localMarket: 'GB',
    moraleState: 88,
    confidence: 94,
    physicalCondition: 92,
    stress: 20,
    adaptability: 94,
    adaptationF1: 99,
    adaptationCar: 92,
    adaptationTeam: 93,
    preferredNumber: 44,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Heptacampeão mundial de F1 e ícone global do esporte motor. Estreou pela McLaren em 2007, construiu uma dinastia na Mercedes e agora veste o macacão escarlate da Scuderia Ferrari.',
    revealedTraits: [
      'Gestão de Pneus Primorosa (TR10)',
      'Especialista em Chuva (TR01)',
      'Liderança de Garagem (TR02)',
    ],
    salaryUsd: 60000000,
    salaryBrl: 60000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    exitClauseUsd: 150000000,
    winBonusUsd: 2500000,
    potentialMin: 94,
    potentialMax: 97,
    f1RacesCompleted: 350,
    superlicensePoints: 100,
    photoFilename: 'hamilton.webp',
  },
  {
    id: 'mbj-004',
    name: 'Charles Leclerc',
    nationality: 'Mônaco',
    age: 28,
    category: 'f1',
    role: 'titular',
    teamKey: 'ferrari',
    teamName: 'Scuderia Ferrari',
    speed: 97,
    consistency: 91,
    rain: 92,
    defense: 93,
    qualifying: 98,
    racePace: 95,
    start: 91,
    overtake: 94,
    tireManagement: 90,
    energyManagement: 92,
    feedback: 91,
    pressure: 89,
    concentration: 92,
    resilience: 90,
    aggressiveness: 82,
    ambition: 96,
    loyalty: 94,
    professionalism: 92,
    reputation: 96,
    globalPopularity: 95,
    localPopularity: 99,
    localMarket: 'MC',
    moraleState: 85,
    confidence: 90,
    physicalCondition: 96,
    stress: 25,
    adaptability: 92,
    adaptationF1: 96,
    adaptationCar: 94,
    adaptationTeam: 97,
    preferredNumber: 16,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Campeão da GP3 em 2016 e da F2 em 2017. Estreou na F1 em 2018 e tornou-se a referência técnica de velocidade pura da Scuderia Ferrari, reconhecido mundialmente pela habilidade em voltas de classificação.',
    revealedTraits: ['Mestre da Pole Position (TR02)', 'Determinação Focada (TR10)'],
    salaryUsd: 36000000,
    salaryBrl: 36000000 * USD_TO_BRL_RATE,
    contractYears: 4,
    exitClauseUsd: 90000000,
    winBonusUsd: 1500000,
    potentialMin: 95,
    potentialMax: 98,
    f1RacesCompleted: 145,
    superlicensePoints: 85,
    photoFilename: 'leclerc.webp',
  },
  {
    id: 'mbj-005',
    name: 'Lando Norris',
    nationality: 'Reino Unido',
    age: 26,
    category: 'f1',
    role: 'titular',
    teamKey: 'mclaren',
    teamName: 'McLaren F1 Team',
    speed: 95,
    consistency: 93,
    rain: 94,
    defense: 92,
    salaryUsd: 25000000,
    salaryBrl: 25000000 * USD_TO_BRL_RATE,
    contractYears: 3,
    potentialMin: 94,
    potentialMax: 98,
    f1RacesCompleted: 125,
    superlicensePoints: 80,
    photoFilename: 'norris.webp',
  },
  {
    id: 'mbj-006',
    name: 'Oscar Piastri',
    nationality: 'Austrália',
    age: 24,
    category: 'f1',
    role: 'titular',
    teamKey: 'mclaren',
    teamName: 'McLaren F1 Team',
    speed: 93,
    consistency: 92,
    rain: 91,
    defense: 93,
    salaryUsd: 12000000,
    salaryBrl: 12000000 * USD_TO_BRL_RATE,
    contractYears: 3,
    potentialMin: 93,
    potentialMax: 97,
    f1RacesCompleted: 44,
    superlicensePoints: 75,
    photoFilename: 'piastri.webp',
  },
  {
    id: 'mbj-007',
    name: 'George Russell',
    nationality: 'Reino Unido',
    age: 28,
    category: 'f1',
    role: 'titular',
    teamKey: 'mercedes',
    teamName: 'Mercedes-AMG Petronas F1 Team',
    speed: 94,
    consistency: 92,
    rain: 93,
    defense: 91,
    salaryUsd: 20000000,
    salaryBrl: 20000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 92,
    potentialMax: 96,
    f1RacesCompleted: 125,
    superlicensePoints: 80,
    photoFilename: 'russell.webp',
  },
  {
    id: 'mbj-008',
    name: 'Andrea Kimi Antonelli',
    nationality: 'Itália',
    age: 19,
    category: 'f1',
    role: 'titular',
    teamKey: 'mercedes',
    teamName: 'Mercedes-AMG Petronas F1 Team',
    speed: 88,
    consistency: 84,
    rain: 86,
    defense: 85,
    salaryUsd: 5000000,
    salaryBrl: 5000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 90,
    potentialMax: 97,
    f1RacesCompleted: 0,
    superlicensePoints: 60,
    photoFilename: 'antonelli.webp',
  },
  {
    id: 'mbj-009',
    name: 'Fernando Alonso',
    nationality: 'Espanha',
    age: 44,
    category: 'f1',
    role: 'titular',
    teamKey: 'aston_martin',
    teamName: 'Aston Martin Aramco F1 Team',
    speed: 93,
    consistency: 94,
    rain: 96,
    defense: 98,
    salaryUsd: 22000000,
    salaryBrl: 22000000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 91,
    potentialMax: 94,
    f1RacesCompleted: 400,
    superlicensePoints: 100,
    photoFilename: 'alonso.webp',
  },
  {
    id: 'mbj-010',
    name: 'Lance Stroll',
    nationality: 'Canadá',
    age: 27,
    category: 'f1',
    role: 'titular',
    teamKey: 'aston_martin',
    teamName: 'Aston Martin Aramco F1 Team',
    speed: 82,
    consistency: 80,
    rain: 88,
    defense: 84,
    salaryUsd: 10000000,
    salaryBrl: 10000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 80,
    potentialMax: 85,
    f1RacesCompleted: 165,
    superlicensePoints: 65,
    photoFilename: 'stroll.webp',
  },
  {
    id: 'mbj-011',
    name: 'Pierre Gasly',
    nationality: 'França',
    age: 30,
    category: 'f1',
    role: 'titular',
    teamKey: 'alpine',
    teamName: 'BWT Alpine F1 Team',
    speed: 87,
    consistency: 86,
    rain: 88,
    defense: 87,
    salaryUsd: 9000000,
    salaryBrl: 9000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 85,
    potentialMax: 89,
    f1RacesCompleted: 150,
    superlicensePoints: 70,
    photoFilename: 'gasly.webp',
  },
  {
    id: 'mbj-012',
    name: 'Jack Doohan',
    nationality: 'Austrália',
    age: 23,
    category: 'f1',
    role: 'titular',
    teamKey: 'alpine',
    teamName: 'BWT Alpine F1 Team',
    speed: 81,
    consistency: 80,
    rain: 82,
    defense: 81,
    salaryUsd: 2500000,
    salaryBrl: 2500000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 82,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'doohan.webp',
  },
  {
    id: 'mbj-013',
    name: 'Alexander Albon',
    nationality: 'Tailândia',
    age: 29,
    category: 'f1',
    role: 'titular',
    teamKey: 'williams',
    teamName: 'Williams Racing',
    speed: 88,
    consistency: 87,
    rain: 86,
    defense: 89,
    salaryUsd: 8000000,
    salaryBrl: 8000000 * USD_TO_BRL_RATE,
    contractYears: 3,
    potentialMin: 86,
    potentialMax: 90,
    f1RacesCompleted: 105,
    superlicensePoints: 70,
    photoFilename: 'albon.webp',
  },
  {
    id: 'mbj-014',
    name: 'Carlos Sainz Jr',
    nationality: 'Espanha',
    age: 31,
    category: 'f1',
    role: 'titular',
    teamKey: 'williams',
    teamName: 'Williams Racing',
    speed: 92,
    consistency: 93,
    rain: 91,
    defense: 94,
    salaryUsd: 18000000,
    salaryBrl: 18000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 91,
    potentialMax: 94,
    f1RacesCompleted: 200,
    superlicensePoints: 85,
    photoFilename: 'sainz.webp',
  },
  {
    id: 'mbj-015',
    name: 'Yuki Tsunoda',
    nationality: 'Japão',
    age: 25,
    category: 'f1',
    role: 'titular',
    teamKey: 'rb',
    teamName: 'Visa Cash App RB F1 Team',
    speed: 86,
    consistency: 84,
    rain: 85,
    defense: 86,
    salaryUsd: 5000000,
    salaryBrl: 5000000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 85,
    potentialMax: 89,
    f1RacesCompleted: 88,
    superlicensePoints: 65,
    photoFilename: 'tsunoda.webp',
  },
  {
    id: 'mbj-016',
    name: 'Isack Hadjar',
    nationality: 'França',
    age: 21,
    category: 'f1',
    role: 'titular',
    teamKey: 'rb',
    teamName: 'Visa Cash App RB F1 Team',
    speed: 83,
    consistency: 81,
    rain: 82,
    defense: 83,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 84,
    potentialMax: 90,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'hadjar.webp',
  },
  {
    id: 'mbj-017',
    name: 'Esteban Ocon',
    nationality: 'França',
    age: 29,
    category: 'f1',
    role: 'titular',
    teamKey: 'haas',
    teamName: 'MoneyGram Haas F1 Team',
    speed: 87,
    consistency: 86,
    rain: 89,
    defense: 91,
    salaryUsd: 8000000,
    salaryBrl: 8000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 85,
    potentialMax: 89,
    f1RacesCompleted: 154,
    superlicensePoints: 70,
    photoFilename: 'ocon.webp',
  },
  {
    id: 'mbj-018',
    name: 'Oliver Bearman',
    nationality: 'Reino Unido',
    age: 20,
    category: 'f1',
    role: 'titular',
    teamKey: 'haas',
    teamName: 'MoneyGram Haas F1 Team',
    speed: 85,
    consistency: 83,
    rain: 84,
    defense: 85,
    salaryUsd: 3000000,
    salaryBrl: 3000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 86,
    potentialMax: 92,
    f1RacesCompleted: 3,
    superlicensePoints: 50,
    photoFilename: 'bearman.webp',
  },
  {
    id: 'mbj-019',
    name: 'Nico Hülkenberg',
    nationality: 'Alemanha',
    age: 38,
    category: 'f1',
    role: 'titular',
    teamKey: 'audi',
    teamName: 'Audi Revolut F1 Team',
    speed: 88,
    consistency: 89,
    rain: 91,
    defense: 88,
    qualifying: 89,
    racePace: 87,
    start: 86,
    overtake: 86,
    tireManagement: 88,
    energyManagement: 87,
    feedback: 94,
    pressure: 88,
    concentration: 89,
    resilience: 87,
    aggressiveness: 68,
    ambition: 82,
    loyalty: 89,
    professionalism: 95,
    reputation: 86,
    globalPopularity: 78,
    localPopularity: 92,
    localMarket: 'DE',
    moraleState: 84,
    confidence: 86,
    physicalCondition: 90,
    stress: 22,
    adaptability: 91,
    adaptationF1: 96,
    adaptationCar: 90,
    adaptationTeam: 91,
    preferredNumber: 27,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Piloto experiente com passagens marcantes por Williams, Force India, Renault e Haas. Escolhido como líder da transição e desenvolvimento do projeto de fábrica da Audi.',
    revealedTraits: [
      'Feedback Técnico de Elite (TR02)',
      'Especialista em Chuva (TR01)',
      'Constância de Long Run (TR10)',
    ],
    salaryUsd: 7000000,
    salaryBrl: 7000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    exitClauseUsd: 20000000,
    winBonusUsd: 800000,
    potentialMin: 86,
    potentialMax: 89,
    f1RacesCompleted: 228,
    superlicensePoints: 75,
    photoFilename: 'hulkenberg.webp',
  },
  {
    id: 'mbj-020',
    name: 'Gabriel Bortoleto',
    nationality: 'Brasil',
    age: 21,
    category: 'f1',
    role: 'titular',
    teamKey: 'audi',
    teamName: 'Audi Revolut F1 Team',
    speed: 86,
    consistency: 85,
    rain: 86,
    defense: 87,
    qualifying: 86,
    racePace: 87,
    start: 84,
    overtake: 88,
    tireManagement: 87,
    energyManagement: 85,
    feedback: 84,
    pressure: 86,
    concentration: 85,
    resilience: 88,
    aggressiveness: 76,
    ambition: 94,
    loyalty: 88,
    professionalism: 90,
    reputation: 82,
    globalPopularity: 74,
    localPopularity: 98,
    localMarket: 'BR',
    moraleState: 89,
    confidence: 88,
    physicalCondition: 98,
    stress: 20,
    adaptability: 92,
    adaptationF1: 85,
    adaptationCar: 88,
    adaptationTeam: 90,
    preferredNumber: 5,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Campeão da Fórmula 3 da FIA em 2023 e campeão da Fórmula 2 em 2024. Revelação brasileira que integra o projeto oficial Audi F1 para a nova era dos motores 2026.',
    revealedTraits: ['Inteligência de Corrida (TR11)', 'Ultrapassagens Precisas (TR09)'],
    salaryUsd: 3500000,
    salaryBrl: 3500000 * USD_TO_BRL_RATE,
    contractYears: 2,
    exitClauseUsd: 25000000,
    winBonusUsd: 600000,
    potentialMin: 87,
    potentialMax: 94,
    f1RacesCompleted: 0,
    superlicensePoints: 55,
    photoFilename: 'bortoleto.webp',
  },
  {
    id: 'mbj-021',
    name: 'Sergio Pérez',
    nationality: 'México',
    age: 36,
    category: 'f1',
    role: 'titular',
    teamKey: 'cadillac',
    teamName: 'Cadillac F1 Team',
    speed: 88,
    consistency: 86,
    rain: 89,
    defense: 91,
    qualifying: 84,
    racePace: 89,
    start: 85,
    overtake: 88,
    tireManagement: 94,
    energyManagement: 89,
    feedback: 88,
    pressure: 87,
    concentration: 86,
    resilience: 89,
    aggressiveness: 77,
    ambition: 85,
    loyalty: 84,
    professionalism: 89,
    reputation: 88,
    globalPopularity: 90,
    localPopularity: 100,
    localMarket: 'MX',
    moraleState: 80,
    confidence: 82,
    physicalCondition: 89,
    stress: 26,
    adaptability: 88,
    adaptationF1: 96,
    adaptationCar: 87,
    adaptationTeam: 88,
    preferredNumber: 11,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Múltiplo vencedor de GPs de F1 com Red Bull, Racing Point e Sauber. Reconhecido como o "Rei das Ruas" e mestre da conservação de pneus, agora lidera a estreia americana da Cadillac.',
    revealedTraits: [
      'Mestre dos Circuitos de Rua (TR10)',
      'Gestão Notável de Pneus (TR02)',
      'Defesa Feroz (TR09)',
    ],
    salaryUsd: 14000000,
    salaryBrl: 14000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    exitClauseUsd: 35000000,
    winBonusUsd: 1200000,
    potentialMin: 86,
    potentialMax: 90,
    f1RacesCompleted: 280,
    superlicensePoints: 85,
    photoFilename: 'perez.webp',
  },
  {
    id: 'mbj-022',
    name: 'Valtteri Bottas',
    nationality: 'Finlândia',
    age: 36,
    category: 'f1',
    role: 'titular',
    teamKey: 'cadillac',
    teamName: 'Cadillac F1 Team',
    speed: 88,
    consistency: 88,
    rain: 86,
    defense: 87,
    qualifying: 90,
    racePace: 87,
    start: 86,
    overtake: 85,
    tireManagement: 88,
    energyManagement: 88,
    feedback: 93,
    pressure: 87,
    concentration: 89,
    resilience: 87,
    aggressiveness: 70,
    ambition: 83,
    loyalty: 90,
    professionalism: 94,
    reputation: 88,
    globalPopularity: 86,
    localPopularity: 96,
    localMarket: 'FI',
    moraleState: 82,
    confidence: 84,
    physicalCondition: 92,
    stress: 21,
    adaptability: 89,
    adaptationF1: 96,
    adaptationCar: 86,
    adaptationTeam: 88,
    preferredNumber: 77,
    eligibilityStatus: 'SUPERLICENÇA VÁLIDA FIA',
    biography:
      'Vencedor de 10 GPs na F1 e vice-campeão mundial em 2019 e 2020 pela Mercedes. Traz precisão cirúrgica na volta lançada e maturidade técnica incomparável para a novata Cadillac.',
    revealedTraits: ['Qualy Cirúrgico (TR02)', 'Jogador de Equipe (TR10)'],
    salaryUsd: 12000000,
    salaryBrl: 12000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    exitClauseUsd: 30000000,
    winBonusUsd: 1000000,
    potentialMin: 86,
    potentialMax: 89,
    f1RacesCompleted: 246,
    superlicensePoints: 80,
    photoFilename: 'bottas.webp',
  },

  // --- 2. RESERVAS OFICIAIS F1 2026 (11 equipes) ---
  {
    id: 'mbj-023',
    name: 'Ayumu Iwasa',
    nationality: 'Japão',
    age: 24,
    category: 'f1',
    role: 'reserva',
    teamKey: 'red_bull',
    teamName: 'Red Bull Racing',
    speed: 80,
    consistency: 79,
    rain: 80,
    defense: 79,
    salaryUsd: 800000,
    salaryBrl: 800000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'iwasa.webp',
  },
  {
    id: 'mbj-024',
    name: 'Antonio Giovinazzi',
    nationality: 'Itália',
    age: 32,
    category: 'f1',
    role: 'reserva',
    teamKey: 'ferrari',
    teamName: 'Scuderia Ferrari',
    speed: 81,
    consistency: 82,
    rain: 81,
    defense: 83,
    salaryUsd: 1500000,
    salaryBrl: 1500000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 62,
    superlicensePoints: 50,
    photoFilename: 'giovinazzi.webp',
  },
  {
    id: 'mbj-025',
    name: "Patricio O'Ward",
    nationality: 'México',
    age: 26,
    category: 'f1',
    role: 'reserva',
    teamKey: 'mclaren',
    teamName: 'McLaren F1 Team',
    speed: 85,
    consistency: 82,
    rain: 83,
    defense: 86,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 84,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'oward.webp',
  },
  {
    id: 'mbj-026',
    name: 'Frederik Vesti',
    nationality: 'Dinamarca',
    age: 24,
    category: 'f1',
    role: 'reserva',
    teamKey: 'mercedes',
    teamName: 'Mercedes-AMG Petronas F1 Team',
    speed: 80,
    consistency: 81,
    rain: 82,
    defense: 80,
    salaryUsd: 900000,
    salaryBrl: 900000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 81,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'vesti.webp',
  },
  {
    id: 'mbj-027',
    name: 'Felipe Drugovich',
    nationality: 'Brasil',
    age: 25,
    category: 'f1',
    role: 'reserva',
    teamKey: 'aston_martin',
    teamName: 'Aston Martin Aramco F1 Team',
    speed: 83,
    consistency: 84,
    rain: 84,
    defense: 83,
    salaryUsd: 1600000,
    salaryBrl: 1600000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 83,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 50,
    photoFilename: 'drugovich.webp',
  },
  {
    id: 'mbj-028',
    name: 'Victor Martins',
    nationality: 'França',
    age: 24,
    category: 'f1',
    role: 'reserva',
    teamKey: 'alpine',
    teamName: 'BWT Alpine F1 Team',
    speed: 82,
    consistency: 79,
    rain: 81,
    defense: 82,
    salaryUsd: 850000,
    salaryBrl: 850000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 81,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'martins.webp',
  },
  {
    id: 'mbj-029',
    name: 'Franco Colapinto',
    nationality: 'Argentina',
    age: 22,
    category: 'f1',
    role: 'reserva',
    teamKey: 'williams',
    teamName: 'Williams Racing',
    speed: 85,
    consistency: 82,
    rain: 83,
    defense: 85,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 85,
    potentialMax: 91,
    f1RacesCompleted: 9,
    superlicensePoints: 45,
    photoFilename: 'colapinto.webp',
  },
  {
    id: 'mbj-030',
    name: 'Arvid Lindblad',
    nationality: 'Reino Unido',
    age: 18,
    category: 'f1',
    role: 'reserva',
    teamKey: 'rb',
    teamName: 'Visa Cash App RB F1 Team',
    speed: 80,
    consistency: 78,
    rain: 79,
    defense: 79,
    salaryUsd: 700000,
    salaryBrl: 700000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 82,
    potentialMax: 91,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    isAcademyProspect: true,
    photoFilename: 'lindblad.webp',
  },
  {
    id: 'mbj-031',
    name: 'Pietro Fittipaldi',
    nationality: 'Brasil',
    age: 29,
    category: 'f1',
    role: 'reserva',
    teamKey: 'haas',
    teamName: 'MoneyGram Haas F1 Team',
    speed: 79,
    consistency: 81,
    rain: 80,
    defense: 81,
    salaryUsd: 1100000,
    salaryBrl: 1100000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 78,
    potentialMax: 82,
    f1RacesCompleted: 2,
    superlicensePoints: 40,
    photoFilename: 'fittipaldi.webp',
  },
  {
    id: 'mbj-032',
    name: 'Zane Maloney',
    nationality: 'Barbados',
    age: 22,
    category: 'f1',
    role: 'reserva',
    teamKey: 'audi',
    teamName: 'Audi Revolut F1 Team',
    speed: 82,
    consistency: 81,
    rain: 83,
    defense: 81,
    salaryUsd: 900000,
    salaryBrl: 900000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 81,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'maloney.webp',
  },
  {
    id: 'mbj-033',
    name: 'Colton Herta',
    nationality: 'Estados Unidos',
    age: 26,
    category: 'f1',
    role: 'reserva',
    teamKey: 'cadillac',
    teamName: 'Cadillac F1 Team',
    speed: 86,
    consistency: 81,
    rain: 84,
    defense: 85,
    salaryUsd: 3000000,
    salaryBrl: 3000000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 85,
    potentialMax: 90,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'herta.webp',
  },

  // --- 3. AGENTES LIVRES / MERCADO GLOBAL (sem vínculo) ---
  {
    id: 'mbj-034',
    name: 'Daniel Ricciardo',
    nationality: 'Austrália',
    age: 36,
    category: 'mercado',
    speed: 85,
    consistency: 83,
    rain: 86,
    defense: 87,
    salaryUsd: 8000000,
    salaryBrl: 8000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 87,
    f1RacesCompleted: 257,
    superlicensePoints: 75,
    photoFilename: 'ricciardo.webp',
  },
  {
    id: 'mbj-035',
    name: 'Kevin Magnussen',
    nationality: 'Dinamarca',
    age: 33,
    category: 'mercado',
    speed: 84,
    consistency: 82,
    rain: 85,
    defense: 89,
    salaryUsd: 5000000,
    salaryBrl: 5000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 182,
    superlicensePoints: 65,
    photoFilename: 'magnussen.webp',
  },
  {
    id: 'mbj-036',
    name: 'Guanyu Zhou',
    nationality: 'China',
    age: 26,
    category: 'mercado',
    speed: 81,
    consistency: 83,
    rain: 82,
    defense: 81,
    salaryUsd: 3500000,
    salaryBrl: 3500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 84,
    f1RacesCompleted: 66,
    superlicensePoints: 50,
    photoFilename: 'zhou.webp',
  },
  {
    id: 'mbj-037',
    name: 'Mick Schumacher',
    nationality: 'Alemanha',
    age: 27,
    category: 'mercado',
    speed: 83,
    consistency: 80,
    rain: 82,
    defense: 82,
    salaryUsd: 3000000,
    salaryBrl: 3000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 87,
    f1RacesCompleted: 43,
    superlicensePoints: 50,
    photoFilename: 'schumacher.webp',
  },
  {
    id: 'mbj-038',
    name: 'Logan Sargeant',
    nationality: 'Estados Unidos',
    age: 25,
    category: 'mercado',
    speed: 78,
    consistency: 76,
    rain: 78,
    defense: 77,
    salaryUsd: 1500000,
    salaryBrl: 1500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 77,
    potentialMax: 82,
    f1RacesCompleted: 36,
    superlicensePoints: 40,
    photoFilename: 'sargeant.webp',
  },
  {
    id: 'mbj-039',
    name: 'Nyck de Vries',
    nationality: 'Holanda',
    age: 31,
    category: 'mercado',
    speed: 82,
    consistency: 81,
    rain: 83,
    defense: 80,
    salaryUsd: 2500000,
    salaryBrl: 2500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 84,
    f1RacesCompleted: 11,
    superlicensePoints: 45,
    photoFilename: 'devries.webp',
  },
  {
    id: 'mbj-040',
    name: 'Robert Shwartzman',
    nationality: 'Israel',
    age: 26,
    category: 'mercado',
    speed: 82,
    consistency: 83,
    rain: 81,
    defense: 83,
    salaryUsd: 1800000,
    salaryBrl: 1800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'shwartzman.webp',
  },
  {
    id: 'mbj-041',
    name: 'Theo Pourchaire',
    nationality: 'França',
    age: 22,
    category: 'mercado',
    speed: 83,
    consistency: 82,
    rain: 82,
    defense: 83,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'pourchaire.webp',
  },
  {
    id: 'mbj-042',
    name: 'Alex Palou',
    nationality: 'Espanha',
    age: 28,
    category: 'indycar',
    speed: 89,
    consistency: 91,
    rain: 88,
    defense: 90,
    salaryUsd: 6500000,
    salaryBrl: 6500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 88,
    potentialMax: 93,
    f1RacesCompleted: 0,
    superlicensePoints: 50,
    photoFilename: 'palou.webp',
  },
  {
    id: 'mbj-043',
    name: 'Kyle Kirkwood',
    nationality: 'Estados Unidos',
    age: 27,
    category: 'indycar',
    speed: 83,
    consistency: 81,
    rain: 80,
    defense: 84,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'kirkwood.webp',
  },
  {
    id: 'mbj-044',
    name: 'Josef Newgarden',
    nationality: 'Estados Unidos',
    age: 35,
    category: 'indycar',
    speed: 87,
    consistency: 88,
    rain: 85,
    defense: 89,
    salaryUsd: 5000000,
    salaryBrl: 5000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 85,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 50,
    photoFilename: 'newgarden.webp',
  },
  {
    id: 'mbj-045',
    name: 'Scott McLaughlin',
    nationality: 'Nova Zelândia',
    age: 32,
    category: 'indycar',
    speed: 86,
    consistency: 86,
    rain: 87,
    defense: 86,
    salaryUsd: 4200000,
    salaryBrl: 4200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 84,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'mclaughlin.webp',
  },
  {
    id: 'mbj-046',
    name: 'Stoffel Vandoorne',
    nationality: 'Bélgica',
    age: 34,
    category: 'formula_e',
    speed: 83,
    consistency: 84,
    rain: 85,
    defense: 84,
    salaryUsd: 2800000,
    salaryBrl: 2800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 42,
    superlicensePoints: 45,
    photoFilename: 'vandoorne.webp',
  },
  {
    id: 'mbj-047',
    name: 'Pascal Wehrlein',
    nationality: 'Alemanha',
    age: 31,
    category: 'formula_e',
    speed: 84,
    consistency: 85,
    rain: 86,
    defense: 85,
    salaryUsd: 3000000,
    salaryBrl: 3000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 39,
    superlicensePoints: 45,
    photoFilename: 'wehrlein.webp',
  },
  {
    id: 'mbj-048',
    name: 'Jean-Eric Vergne',
    nationality: 'França',
    age: 35,
    category: 'formula_e',
    speed: 84,
    consistency: 85,
    rain: 88,
    defense: 87,
    salaryUsd: 3200000,
    salaryBrl: 3200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 58,
    superlicensePoints: 50,
    photoFilename: 'vergne.webp',
  },
  {
    id: 'mbj-049',
    name: 'Nick Cassidy',
    nationality: 'Nova Zelândia',
    age: 31,
    category: 'formula_e',
    speed: 84,
    consistency: 85,
    rain: 87,
    defense: 84,
    salaryUsd: 2700000,
    salaryBrl: 2700000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'cassidy.webp',
  },
  {
    id: 'mbj-050',
    name: 'Mitch Evans',
    nationality: 'Nova Zelândia',
    age: 31,
    category: 'formula_e',
    speed: 85,
    consistency: 84,
    rain: 86,
    defense: 86,
    salaryUsd: 2900000,
    salaryBrl: 2900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'evans.webp',
  },
  {
    id: 'mbj-051',
    name: 'Kamui Kobayashi',
    nationality: 'Japão',
    age: 39,
    category: 'prototipos',
    speed: 84,
    consistency: 87,
    rain: 89,
    defense: 88,
    salaryUsd: 2500000,
    salaryBrl: 2500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 85,
    f1RacesCompleted: 76,
    superlicensePoints: 60,
    photoFilename: 'kobayashi.webp',
  },
  {
    id: 'mbj-052',
    name: 'Brendon Hartley',
    nationality: 'Nova Zelândia',
    age: 36,
    category: 'prototipos',
    speed: 82,
    consistency: 86,
    rain: 87,
    defense: 85,
    salaryUsd: 2100000,
    salaryBrl: 2100000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 84,
    f1RacesCompleted: 25,
    superlicensePoints: 50,
    photoFilename: 'hartley.webp',
  },
  {
    id: 'mbj-053',
    name: 'Sebastien Buemi',
    nationality: 'Suíça',
    age: 37,
    category: 'prototipos',
    speed: 83,
    consistency: 86,
    rain: 88,
    defense: 86,
    salaryUsd: 2400000,
    salaryBrl: 2400000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 55,
    superlicensePoints: 55,
    photoFilename: 'buemi.webp',
  },
  {
    id: 'mbj-054',
    name: 'Ross Chastain',
    nationality: 'Estados Unidos',
    age: 33,
    category: 'nascar',
    speed: 79,
    consistency: 80,
    rain: 74,
    defense: 88,
    salaryUsd: 3500000,
    salaryBrl: 3500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 76,
    potentialMax: 82,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    photoFilename: 'chastain.webp',
  },
  {
    id: 'mbj-055',
    name: 'Kyle Larson',
    nationality: 'Estados Unidos',
    age: 33,
    category: 'nascar',
    speed: 85,
    consistency: 84,
    rain: 80,
    defense: 86,
    salaryUsd: 5500000,
    salaryBrl: 5500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'larson.webp',
  },

  // --- 4. PROSPECTOS & ACADEMIA (Jovens talentos F2 / F3 / Academias) ---
  {
    id: 'mbj-056',
    name: 'Paul Aron',
    nationality: 'Estônia',
    age: 22,
    category: 'f2',
    speed: 82,
    consistency: 80,
    rain: 81,
    defense: 81,
    salaryUsd: 750000,
    salaryBrl: 750000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 82,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    isAcademyProspect: true,
    photoFilename: 'aron.webp',
  },
  {
    id: 'mbj-057',
    name: 'Enzo Fittipaldi',
    nationality: 'Brasil',
    age: 24,
    category: 'f2',
    speed: 80,
    consistency: 81,
    rain: 82,
    defense: 80,
    salaryUsd: 700000,
    salaryBrl: 700000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 79,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    isAcademyProspect: true,
    photoFilename: 'efittipaldi.webp',
  },
  {
    id: 'mbj-058',
    name: "Zak O'Sullivan",
    nationality: 'Reino Unido',
    age: 21,
    category: 'f2',
    speed: 80,
    consistency: 79,
    rain: 81,
    defense: 79,
    salaryUsd: 650000,
    salaryBrl: 650000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    isAcademyProspect: true,
    photoFilename: 'osullivan.webp',
  },
  {
    id: 'mbj-059',
    name: 'Dennis Hauger',
    nationality: 'Noruega',
    age: 23,
    category: 'f2',
    speed: 81,
    consistency: 80,
    rain: 83,
    defense: 81,
    salaryUsd: 700000,
    salaryBrl: 700000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    isAcademyProspect: true,
    photoFilename: 'hauger.webp',
  },
  {
    id: 'mbj-060',
    name: 'Luke Browning',
    nationality: 'Reino Unido',
    age: 24,
    category: 'f2',
    speed: 81,
    consistency: 79,
    rain: 80,
    defense: 80,
    salaryUsd: 600000,
    salaryBrl: 600000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    isAcademyProspect: true,
    photoFilename: 'browning.webp',
  },
  {
    id: 'mbj-061',
    name: 'Dino Beganovic',
    nationality: 'Suécia',
    age: 22,
    category: 'f2',
    speed: 81,
    consistency: 80,
    rain: 81,
    defense: 80,
    salaryUsd: 650000,
    salaryBrl: 650000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 81,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    isAcademyProspect: true,
    photoFilename: 'beganovic.webp',
  },
  {
    id: 'mbj-062',
    name: 'Leonardo Fornaroli',
    nationality: 'Itália',
    age: 21,
    category: 'f2',
    speed: 82,
    consistency: 84,
    rain: 82,
    defense: 83,
    salaryUsd: 750000,
    salaryBrl: 750000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 82,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    isAcademyProspect: true,
    photoFilename: 'fornaroli.webp',
  },
  {
    id: 'mbj-063',
    name: 'Gabriele Mini',
    nationality: 'Itália',
    age: 21,
    category: 'f2',
    speed: 82,
    consistency: 80,
    rain: 81,
    defense: 82,
    salaryUsd: 700000,
    salaryBrl: 700000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 82,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    isAcademyProspect: true,
    photoFilename: 'mini.webp',
  },
  {
    id: 'mbj-064',
    name: 'Kush Maini',
    nationality: 'Índia',
    age: 25,
    category: 'f2',
    speed: 79,
    consistency: 79,
    rain: 80,
    defense: 80,
    salaryUsd: 600000,
    salaryBrl: 600000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 78,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'maini.webp',
  },
  {
    id: 'mbj-065',
    name: 'Richard Verschoor',
    nationality: 'Holanda',
    age: 25,
    category: 'f2',
    speed: 80,
    consistency: 81,
    rain: 82,
    defense: 80,
    salaryUsd: 650000,
    salaryBrl: 650000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 79,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    photoFilename: 'verschoor.webp',
  },
  {
    id: 'mbj-066',
    name: 'Jak Crawford',
    nationality: 'Estados Unidos',
    age: 20,
    category: 'f2',
    speed: 81,
    consistency: 80,
    rain: 79,
    defense: 80,
    salaryUsd: 650000,
    salaryBrl: 650000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 81,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    isAcademyProspect: true,
    photoFilename: 'crawford.webp',
  },
  {
    id: 'mbj-067',
    name: 'Rafael Camara',
    nationality: 'Brasil',
    age: 20,
    category: 'f2',
    speed: 82,
    consistency: 81,
    rain: 83,
    defense: 82,
    salaryUsd: 800000,
    salaryBrl: 800000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 83,
    potentialMax: 92,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    isAcademyProspect: true,
    photoFilename: 'camara.webp',
  },
  {
    id: 'mbj-068',
    name: 'Tuukka Taponen',
    nationality: 'Finlândia',
    age: 19,
    category: 'f2',
    speed: 80,
    consistency: 80,
    rain: 82,
    defense: 80,
    salaryUsd: 600000,
    salaryBrl: 600000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 81,
    potentialMax: 90,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'taponen.webp',
  },
  {
    id: 'mbj-069',
    name: 'Freddie Slater',
    nationality: 'Reino Unido',
    age: 17, // < 18: Piloto em Formação / Academia
    category: 'f2',
    speed: 78,
    consistency: 77,
    rain: 80,
    defense: 78,
    salaryUsd: 400000,
    salaryBrl: 400000 * USD_TO_BRL_RATE,
    contractYears: 3,
    potentialMin: 83,
    potentialMax: 93,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    isAcademyProspect: true,
    photoFilename: 'slater.webp',
    notes: 'Talento precoce < 18 anos. Elegível para desenvolvimento em academia.',
  },
  {
    id: 'mbj-070',
    name: 'Ugo Ugochukwu',
    nationality: 'Estados Unidos',
    age: 18,
    category: 'f2',
    speed: 79,
    consistency: 77,
    rain: 78,
    defense: 78,
    salaryUsd: 500000,
    salaryBrl: 500000 * USD_TO_BRL_RATE,
    contractYears: 2,
    potentialMin: 80,
    potentialMax: 89,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'ugochukwu.webp',
  },
  {
    id: 'mbj-071',
    name: 'Alexander Dunne',
    nationality: 'Irlanda',
    age: 20,
    category: 'f2',
    speed: 80,
    consistency: 78,
    rain: 81,
    defense: 79,
    salaryUsd: 550000,
    salaryBrl: 550000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'dunne.webp',
  },
  {
    id: 'mbj-072',
    name: 'Nikola Tsolov',
    nationality: 'Bulgária',
    age: 19,
    category: 'f2',
    speed: 79,
    consistency: 77,
    rain: 79,
    defense: 78,
    salaryUsd: 500000,
    salaryBrl: 500000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'tsolov.webp',
  },
  {
    id: 'mbj-073',
    name: 'Mari Boya',
    nationality: 'Espanha',
    age: 21,
    category: 'f2',
    speed: 78,
    consistency: 78,
    rain: 79,
    defense: 77,
    salaryUsd: 480000,
    salaryBrl: 480000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 78,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    isAcademyProspect: true,
    photoFilename: 'boya.webp',
  },
  {
    id: 'mbj-074',
    name: 'Noel Leon',
    nationality: 'México',
    age: 21,
    category: 'f2',
    speed: 78,
    consistency: 77,
    rain: 78,
    defense: 77,
    salaryUsd: 450000,
    salaryBrl: 450000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 78,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    isAcademyProspect: true,
    photoFilename: 'leon.webp',
  },
  {
    id: 'mbj-075',
    name: 'Tim Tramnitz',
    nationality: 'Alemanha',
    age: 21,
    category: 'f2',
    speed: 79,
    consistency: 78,
    rain: 80,
    defense: 78,
    salaryUsd: 500000,
    salaryBrl: 500000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 79,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'tramnitz.webp',
  },
  {
    id: 'mbj-076',
    name: 'Callum Voisin',
    nationality: 'Reino Unido',
    age: 20,
    category: 'f2',
    speed: 78,
    consistency: 77,
    rain: 79,
    defense: 78,
    salaryUsd: 450000,
    salaryBrl: 450000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 78,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    isAcademyProspect: true,
    photoFilename: 'voisin.webp',
  },
  {
    id: 'mbj-077',
    name: 'Christian Mansell',
    nationality: 'Austrália',
    age: 21,
    category: 'f2',
    speed: 79,
    consistency: 78,
    rain: 80,
    defense: 79,
    salaryUsd: 520000,
    salaryBrl: 520000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 79,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'mansell.webp',
  },
  {
    id: 'mbj-078',
    name: 'Sami Meguetounif',
    nationality: 'França',
    age: 21,
    category: 'f2',
    speed: 77,
    consistency: 77,
    rain: 78,
    defense: 76,
    salaryUsd: 420000,
    salaryBrl: 420000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 77,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    isAcademyProspect: true,
    photoFilename: 'meguetounif.webp',
  },
  {
    id: 'mbj-079',
    name: 'Oliver Goethe',
    nationality: 'Alemanha',
    age: 21,
    category: 'f2',
    speed: 79,
    consistency: 78,
    rain: 79,
    defense: 79,
    salaryUsd: 530000,
    salaryBrl: 530000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 79,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'goethe.webp',
  },
  {
    id: 'mbj-080',
    name: 'Martinius Stenshorne',
    nationality: 'Noruega',
    age: 20,
    category: 'f2',
    speed: 80,
    consistency: 78,
    rain: 81,
    defense: 79,
    salaryUsd: 580000,
    salaryBrl: 580000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 25,
    isAcademyProspect: true,
    photoFilename: 'stenshorne.webp',
  },

  // Pilotos complementares do universo MBJ (IndyNXT, F3, Protótipos e Mercado Expandido)
  {
    id: 'mbj-081',
    name: 'Louis Foster',
    nationality: 'Reino Unido',
    age: 22,
    category: 'indynxt',
    speed: 81,
    consistency: 80,
    rain: 81,
    defense: 80,
    salaryUsd: 650000,
    salaryBrl: 650000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 81,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'foster.webp',
  },
  {
    id: 'mbj-082',
    name: 'Jacob Abel',
    nationality: 'Estados Unidos',
    age: 24,
    category: 'indynxt',
    speed: 78,
    consistency: 79,
    rain: 78,
    defense: 79,
    salaryUsd: 500000,
    salaryBrl: 500000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 77,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    photoFilename: 'abel.webp',
  },
  {
    id: 'mbj-083',
    name: 'Caio Collet',
    nationality: 'Brasil',
    age: 24,
    category: 'indycar',
    speed: 81,
    consistency: 80,
    rain: 82,
    defense: 81,
    salaryUsd: 900000,
    salaryBrl: 900000 * USD_TO_BRL_RATE,
    contractYears: 1,
    potentialMin: 80,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'collet.webp',
  },
  {
    id: 'mbj-084',
    name: 'Robin Frijns',
    nationality: 'Holanda',
    age: 34,
    category: 'formula_e',
    speed: 83,
    consistency: 84,
    rain: 86,
    defense: 83,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'frijns.webp',
  },
  {
    id: 'mbj-085',
    name: 'Antonio Felix da Costa',
    nationality: 'Portugal',
    age: 34,
    category: 'formula_e',
    speed: 83,
    consistency: 84,
    rain: 85,
    defense: 85,
    salaryUsd: 2500000,
    salaryBrl: 2500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'dacosta.webp',
  },
  {
    id: 'mbj-086',
    name: 'Oliver Rowland',
    nationality: 'Reino Unido',
    age: 33,
    category: 'formula_e',
    speed: 83,
    consistency: 82,
    rain: 84,
    defense: 86,
    salaryUsd: 2300000,
    salaryBrl: 2300000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'rowland.webp',
  },
  {
    id: 'mbj-087',
    name: 'Sam Bird',
    nationality: 'Reino Unido',
    age: 39,
    category: 'formula_e',
    speed: 81,
    consistency: 81,
    rain: 82,
    defense: 82,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 79,
    potentialMax: 82,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'bird.webp',
  },
  {
    id: 'mbj-088',
    name: 'Maximilian Günther',
    nationality: 'Alemanha',
    age: 28,
    category: 'formula_e',
    speed: 82,
    consistency: 82,
    rain: 84,
    defense: 82,
    salaryUsd: 2100000,
    salaryBrl: 2100000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'gunther.webp',
  },
  {
    id: 'mbj-089',
    name: 'Jake Dennis',
    nationality: 'Reino Unido',
    age: 30,
    category: 'formula_e',
    speed: 84,
    consistency: 85,
    rain: 86,
    defense: 85,
    salaryUsd: 2800000,
    salaryBrl: 2800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'dennis.webp',
  },
  {
    id: 'mbj-090',
    name: 'Norman Nato',
    nationality: 'França',
    age: 33,
    category: 'formula_e',
    speed: 80,
    consistency: 81,
    rain: 82,
    defense: 81,
    salaryUsd: 1800000,
    salaryBrl: 1800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 79,
    potentialMax: 82,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'nato.webp',
  },
  {
    id: 'mbj-091',
    name: 'Marcus Armstrong',
    nationality: 'Nova Zelândia',
    age: 25,
    category: 'indycar',
    speed: 82,
    consistency: 82,
    rain: 81,
    defense: 82,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'armstrong.webp',
  },
  {
    id: 'mbj-092',
    name: 'Christian Lundgaard',
    nationality: 'Dinamarca',
    age: 24,
    category: 'indycar',
    speed: 84,
    consistency: 83,
    rain: 84,
    defense: 83,
    salaryUsd: 2500000,
    salaryBrl: 2500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'lundgaard.webp',
  },
  {
    id: 'mbj-093',
    name: 'Felix Rosenqvist',
    nationality: 'Suécia',
    age: 34,
    category: 'indycar',
    speed: 84,
    consistency: 82,
    rain: 84,
    defense: 84,
    salaryUsd: 2800000,
    salaryBrl: 2800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'rosenqvist.webp',
  },
  {
    id: 'mbj-094',
    name: 'Rinus VeeKay',
    nationality: 'Holanda',
    age: 25,
    category: 'indycar',
    speed: 82,
    consistency: 80,
    rain: 83,
    defense: 83,
    salaryUsd: 2100000,
    salaryBrl: 2100000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'veekay.webp',
  },
  {
    id: 'mbj-095',
    name: 'Santino Ferrucci',
    nationality: 'Estados Unidos',
    age: 27,
    category: 'indycar',
    speed: 81,
    consistency: 80,
    rain: 80,
    defense: 87,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'ferrucci.webp',
  },
  {
    id: 'mbj-096',
    name: 'David Malukas',
    nationality: 'Estados Unidos',
    age: 24,
    category: 'indycar',
    speed: 82,
    consistency: 79,
    rain: 81,
    defense: 81,
    salaryUsd: 1700000,
    salaryBrl: 1700000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'malukas.webp',
  },
  {
    id: 'mbj-097',
    name: 'Kyffin Simpson',
    nationality: 'Ilhas Cayman',
    age: 21,
    category: 'indycar',
    speed: 77,
    consistency: 78,
    rain: 78,
    defense: 78,
    salaryUsd: 1200000,
    salaryBrl: 1200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 76,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 20,
    photoFilename: 'simpson.webp',
  },
  {
    id: 'mbj-098',
    name: 'Nolan Siegel',
    nationality: 'Estados Unidos',
    age: 21,
    category: 'indycar',
    speed: 80,
    consistency: 79,
    rain: 80,
    defense: 80,
    salaryUsd: 1400000,
    salaryBrl: 1400000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'siegel.webp',
  },
  {
    id: 'mbj-099',
    name: 'Linus Lundqvist',
    nationality: 'Suécia',
    age: 26,
    category: 'indycar',
    speed: 81,
    consistency: 80,
    rain: 82,
    defense: 80,
    salaryUsd: 1500000,
    salaryBrl: 1500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'lundqvist.webp',
  },
  {
    id: 'mbj-100',
    name: 'Callum Ilott',
    nationality: 'Reino Unido',
    age: 27,
    category: 'prototipos',
    speed: 83,
    consistency: 83,
    rain: 84,
    defense: 83,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'ilott.webp',
  },
  {
    id: 'mbj-101',
    name: 'Will Stevens',
    nationality: 'Reino Unido',
    age: 34,
    category: 'prototipos',
    speed: 80,
    consistency: 83,
    rain: 82,
    defense: 81,
    salaryUsd: 1400000,
    salaryBrl: 1400000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 79,
    potentialMax: 82,
    f1RacesCompleted: 18,
    superlicensePoints: 40,
    photoFilename: 'stevens.webp',
  },
  {
    id: 'mbj-102',
    name: 'Earl Bamber',
    nationality: 'Nova Zelândia',
    age: 35,
    category: 'prototipos',
    speed: 83,
    consistency: 85,
    rain: 87,
    defense: 86,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'bamber.webp',
  },
  {
    id: 'mbj-103',
    name: 'Alex Lynn',
    nationality: 'Reino Unido',
    age: 32,
    category: 'prototipos',
    speed: 82,
    consistency: 84,
    rain: 85,
    defense: 83,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'lynn.webp',
  },
  {
    id: 'mbj-104',
    name: 'Mike Conway',
    nationality: 'Reino Unido',
    age: 42,
    category: 'prototipos',
    speed: 82,
    consistency: 85,
    rain: 85,
    defense: 84,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'conway.webp',
  },
  {
    id: 'mbj-105',
    name: 'Jose Maria Lopez',
    nationality: 'Argentina',
    age: 42,
    category: 'prototipos',
    speed: 82,
    consistency: 84,
    rain: 85,
    defense: 85,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'lopez.webp',
  },
  {
    id: 'mbj-106',
    name: 'Rene Rast',
    nationality: 'Alemanha',
    age: 39,
    category: 'prototipos',
    speed: 84,
    consistency: 86,
    rain: 88,
    defense: 85,
    salaryUsd: 2600000,
    salaryBrl: 2600000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 85,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'rast.webp',
  },
  {
    id: 'mbj-107',
    name: 'Laurens Vanthoor',
    nationality: 'Bélgica',
    age: 34,
    category: 'prototipos',
    speed: 84,
    consistency: 86,
    rain: 87,
    defense: 85,
    salaryUsd: 2400000,
    salaryBrl: 2400000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'vanthoor.webp',
  },
  {
    id: 'mbj-108',
    name: 'Kevin Estre',
    nationality: 'França',
    age: 37,
    category: 'prototipos',
    speed: 85,
    consistency: 86,
    rain: 89,
    defense: 87,
    salaryUsd: 2700000,
    salaryBrl: 2700000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 45,
    photoFilename: 'estre.webp',
  },
  {
    id: 'mbj-109',
    name: 'Andre Lotterer',
    nationality: 'Alemanha',
    age: 44,
    category: 'prototipos',
    speed: 82,
    consistency: 86,
    rain: 87,
    defense: 85,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 1,
    superlicensePoints: 50,
    photoFilename: 'lotterer.webp',
  },
  {
    id: 'mbj-110',
    name: 'Felipe Nasr',
    nationality: 'Brasil',
    age: 33,
    category: 'prototipos',
    speed: 83,
    consistency: 85,
    rain: 87,
    defense: 86,
    salaryUsd: 2400000,
    salaryBrl: 2400000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 39,
    superlicensePoints: 50,
    photoFilename: 'nasr.webp',
  },
  {
    id: 'mbj-111',
    name: 'Dane Cameron',
    nationality: 'Estados Unidos',
    age: 37,
    category: 'prototipos',
    speed: 81,
    consistency: 83,
    rain: 82,
    defense: 83,
    salaryUsd: 1700000,
    salaryBrl: 1700000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'cameron.webp',
  },
  {
    id: 'mbj-112',
    name: 'Mathieu Jaminet',
    nationality: 'França',
    age: 31,
    category: 'prototipos',
    speed: 83,
    consistency: 84,
    rain: 86,
    defense: 84,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'jaminet.webp',
  },
  {
    id: 'mbj-113',
    name: 'Matt Campbell',
    nationality: 'Austrália',
    age: 31,
    category: 'prototipos',
    speed: 84,
    consistency: 84,
    rain: 86,
    defense: 85,
    salaryUsd: 2100000,
    salaryBrl: 2100000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 87,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'campbell.webp',
  },
  {
    id: 'mbj-114',
    name: 'Nick Yelloly',
    nationality: 'Reino Unido',
    age: 35,
    category: 'prototipos',
    speed: 81,
    consistency: 83,
    rain: 84,
    defense: 82,
    salaryUsd: 1600000,
    salaryBrl: 1600000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'yelloly.webp',
  },
  {
    id: 'mbj-115',
    name: 'Connor De Phillippi',
    nationality: 'Estados Unidos',
    age: 33,
    category: 'prototipos',
    speed: 80,
    consistency: 82,
    rain: 81,
    defense: 82,
    salaryUsd: 1500000,
    salaryBrl: 1500000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 79,
    potentialMax: 82,
    f1RacesCompleted: 0,
    superlicensePoints: 30,
    photoFilename: 'dephillippi.webp',
  },
  {
    id: 'mbj-116',
    name: 'Sheldon van der Linde',
    nationality: 'África do Sul',
    age: 26,
    category: 'prototipos',
    speed: 84,
    consistency: 83,
    rain: 85,
    defense: 84,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'vanderlinde.webp',
  },
  {
    id: 'mbj-117',
    name: 'Marco Wittmann',
    nationality: 'Alemanha',
    age: 36,
    category: 'prototipos',
    speed: 82,
    consistency: 84,
    rain: 85,
    defense: 83,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'wittmann.webp',
  },
  {
    id: 'mbj-118',
    name: 'Robin Frijns WEC',
    nationality: 'Holanda',
    age: 34,
    category: 'prototipos',
    speed: 83,
    consistency: 85,
    rain: 86,
    defense: 83,
    salaryUsd: 2100000,
    salaryBrl: 2100000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 84,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'frijns.webp',
  },
  {
    id: 'mbj-119',
    name: 'Dries Vanthoor',
    nationality: 'Bélgica',
    age: 27,
    category: 'prototipos',
    speed: 84,
    consistency: 83,
    rain: 85,
    defense: 84,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'driesvanthoor.webp',
  },
  {
    id: 'mbj-120',
    name: 'Raffaele Marciello',
    nationality: 'Suíça',
    age: 31,
    category: 'prototipos',
    speed: 85,
    consistency: 85,
    rain: 88,
    defense: 86,
    salaryUsd: 2600000,
    salaryBrl: 2600000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 83,
    potentialMax: 88,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'marciello.webp',
  },
  {
    id: 'mbj-121',
    name: 'Ricky Taylor',
    nationality: 'Estados Unidos',
    age: 36,
    category: 'prototipos',
    speed: 82,
    consistency: 83,
    rain: 84,
    defense: 83,
    salaryUsd: 1800000,
    salaryBrl: 1800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'taylor.webp',
  },
  {
    id: 'mbj-122',
    name: 'Filipe Albuquerque',
    nationality: 'Portugal',
    age: 40,
    category: 'prototipos',
    speed: 82,
    consistency: 84,
    rain: 86,
    defense: 84,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'albuquerque.webp',
  },
  {
    id: 'mbj-123',
    name: 'Louis Deletraz',
    nationality: 'Suíça',
    age: 28,
    category: 'prototipos',
    speed: 83,
    consistency: 83,
    rain: 85,
    defense: 84,
    salaryUsd: 2000000,
    salaryBrl: 2000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'deletraz.webp',
  },
  {
    id: 'mbj-124',
    name: 'Jordan Taylor',
    nationality: 'Estados Unidos',
    age: 34,
    category: 'prototipos',
    speed: 81,
    consistency: 83,
    rain: 83,
    defense: 83,
    salaryUsd: 1700000,
    salaryBrl: 1700000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'jordantaylor.webp',
  },
  {
    id: 'mbj-125',
    name: 'Tom Blomqvist',
    nationality: 'Reino Unido',
    age: 32,
    category: 'prototipos',
    speed: 83,
    consistency: 84,
    rain: 85,
    defense: 84,
    salaryUsd: 2100000,
    salaryBrl: 2100000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'blomqvist.webp',
  },
  {
    id: 'mbj-126',
    name: 'Jack Aitken',
    nationality: 'Reino Unido',
    age: 30,
    category: 'prototipos',
    speed: 82,
    consistency: 83,
    rain: 83,
    defense: 83,
    salaryUsd: 1800000,
    salaryBrl: 1800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 84,
    f1RacesCompleted: 1,
    superlicensePoints: 35,
    photoFilename: 'aitken.webp',
  },
  {
    id: 'mbj-127',
    name: 'Pipo Derani',
    nationality: 'Brasil',
    age: 32,
    category: 'prototipos',
    speed: 84,
    consistency: 83,
    rain: 86,
    defense: 87,
    salaryUsd: 2300000,
    salaryBrl: 2300000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'derani.webp',
  },
  {
    id: 'mbj-128',
    name: 'Sebastien Bourdais',
    nationality: 'França',
    age: 47,
    category: 'prototipos',
    speed: 83,
    consistency: 85,
    rain: 87,
    defense: 86,
    salaryUsd: 2400000,
    salaryBrl: 2400000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 84,
    f1RacesCompleted: 27,
    superlicensePoints: 50,
    photoFilename: 'bourdais.webp',
  },
  {
    id: 'mbj-129',
    name: 'Renger van der Zande',
    nationality: 'Holanda',
    age: 39,
    category: 'prototipos',
    speed: 82,
    consistency: 83,
    rain: 85,
    defense: 84,
    salaryUsd: 1900000,
    salaryBrl: 1900000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 80,
    potentialMax: 83,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'vanderzande.webp',
  },
  {
    id: 'mbj-130',
    name: 'Romain Grosjean',
    nationality: 'França',
    age: 39,
    category: 'indycar',
    speed: 84,
    consistency: 79,
    rain: 85,
    defense: 83,
    salaryUsd: 3200000,
    salaryBrl: 3200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 85,
    f1RacesCompleted: 179,
    superlicensePoints: 60,
    photoFilename: 'grosjean.webp',
  },
  {
    id: 'mbj-131',
    name: 'Marcus Ericsson',
    nationality: 'Suécia',
    age: 35,
    category: 'indycar',
    speed: 82,
    consistency: 83,
    rain: 83,
    defense: 84,
    salaryUsd: 3000000,
    salaryBrl: 3000000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 81,
    potentialMax: 84,
    f1RacesCompleted: 97,
    superlicensePoints: 50,
    photoFilename: 'ericsson.webp',
  },
  {
    id: 'mbj-132',
    name: 'Takuma Sato',
    nationality: 'Japão',
    age: 49,
    category: 'indycar',
    speed: 80,
    consistency: 79,
    rain: 83,
    defense: 82,
    salaryUsd: 1800000,
    salaryBrl: 1800000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 78,
    potentialMax: 81,
    f1RacesCompleted: 90,
    superlicensePoints: 45,
    photoFilename: 'sato.webp',
  },
  {
    id: 'mbj-133',
    name: 'Alexander Rossi',
    nationality: 'Estados Unidos',
    age: 34,
    category: 'indycar',
    speed: 84,
    consistency: 83,
    rain: 84,
    defense: 85,
    salaryUsd: 3600000,
    salaryBrl: 3600000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 82,
    potentialMax: 86,
    f1RacesCompleted: 5,
    superlicensePoints: 45,
    photoFilename: 'rossi.webp',
  },
  {
    id: 'mbj-134',
    name: 'Helio Castroneves',
    nationality: 'Brasil',
    age: 50,
    category: 'indycar',
    speed: 80,
    consistency: 82,
    rain: 81,
    defense: 84,
    salaryUsd: 2200000,
    salaryBrl: 2200000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 78,
    potentialMax: 81,
    f1RacesCompleted: 0,
    superlicensePoints: 40,
    photoFilename: 'castroneves.webp',
  },
  {
    id: 'mbj-135',
    name: 'Tony Kanaan',
    nationality: 'Brasil',
    age: 51,
    category: 'indycar',
    speed: 79,
    consistency: 82,
    rain: 80,
    defense: 83,
    salaryUsd: 1600000,
    salaryBrl: 1600000 * USD_TO_BRL_RATE,
    contractYears: 0,
    potentialMin: 77,
    potentialMax: 80,
    f1RacesCompleted: 0,
    superlicensePoints: 35,
    photoFilename: 'kanaan.webp',
  },
]

export function getOverallRating(pilot: {
  speed: number
  consistency: number
  rain: number
  defense: number
}): number {
  return Math.round(
    pilot.speed * 0.4 + pilot.consistency * 0.3 + pilot.rain * 0.15 + pilot.defense * 0.15,
  )
}

export function checkEligibility(pilot: {
  age: number
  f1RacesCompleted?: number
  superlicensePoints?: number
}) {
  const isMinor = pilot.age < 18
  const needsHomologation =
    (pilot.f1RacesCompleted ?? 0) === 0 && (pilot.superlicensePoints ?? 0) < 40

  if (isMinor) {
    return {
      status: 'academia' as const,
      label: 'Piloto em Formação / Academia',
      description:
        'Menor de 18 anos. Elegível apenas para desenvolvimento e programa de jovens talentos.',
      canSignTitular: false,
      canSignReserve: true,
      requiresHomologation: true,
    }
  }

  if (needsHomologation) {
    return {
      status: 'homologacao' as const,
      label: 'Exige Homologação FIA',
      description:
        'Sem histórico de corridas na F1 e pontuação mínima de superlicença pendente de validação pela FIA.',
      canSignTitular: true,
      canSignReserve: true,
      requiresHomologation: true,
    }
  }

  return {
    status: 'elegivel' as const,
    label: 'Totalmente Elegível',
    description: 'Atende a todos os critérios da FIA e requisitos contratuais para qualquer vaga.',
    canSignTitular: true,
    canSignReserve: true,
    requiresHomologation: false,
  }
}
