/**
 * Banco de Nomes e Sobrenomes Coerentes Culturalmente por Região / País
 * F1 Manager 2026 — Geração Procedural
 */

export interface NamePoolRegion {
  firstNamesMale: string[]
  firstNamesFemale: string[]
  lastNames: string[]
  nationalities: { name: string; flag: string }[]
}

export const CULTURAL_NAME_POOLS: Record<string, NamePoolRegion> = {
  brasil: {
    firstNamesMale: [
      'Lucas',
      'Gabriel',
      'Matheus',
      'Felipe',
      'Enzo',
      'Rodrigo',
      'Guilherme',
      'Thiago',
      'Bernardo',
      'Henrique',
      'Caio',
      'Vinicius',
      'Arthur',
      'Rafael',
      'Eduardo',
      'Gustavo',
    ],
    firstNamesFemale: [
      'Beatriz',
      'Mariana',
      'Helena',
      'Larissa',
      'Carolina',
      'Camila',
      'Fernanda',
      'Isabela',
      'Gabriela',
      'Juliana',
    ],
    lastNames: [
      'Silva',
      'Moretti',
      'Santos',
      'Oliveira',
      'Souza',
      'Lima',
      'Pereira',
      'Carvalho',
      'Ribeiro',
      'Almeida',
      'Costa',
      'Barbosa',
      'Moraes',
      'Fontes',
      'Castilho',
      'Fagundes',
      'Menezes',
      'Cardoso',
    ],
    nationalities: [{ name: 'Brasil', flag: '🇧🇷' }],
  },
  europa_ocidental: {
    firstNamesMale: [
      'Theo',
      'Arthur',
      'Maxence',
      'Hugo',
      'Louis',
      'Jules',
      'Pierre',
      'Antoine',
      'Felix',
      'Lukas',
      'Leon',
      'Maximilian',
      'Jonas',
      'Julian',
      'Finn',
      'Matteo',
      'Leonardo',
      'Lorenzo',
      'Alessandro',
      'Francesco',
    ],
    firstNamesFemale: [
      'Camille',
      'Lea',
      'Manon',
      'Emma',
      'Sophie',
      'Mia',
      'Hannah',
      'Giulia',
      'Sofia',
      'Chiara',
    ],
    lastNames: [
      'Dubois',
      'Laurent',
      'Moreau',
      'Simon',
      'Michel',
      'Lefebvre',
      'Leroy',
      'Schmidt',
      'Weber',
      'Meyer',
      'Wagner',
      'Becker',
      'Hoffmann',
      'Rossi',
      'Ferrari',
      'Russo',
      'Bianchi',
      'Romano',
      'Colombo',
      'Ricci',
    ],
    nationalities: [
      { name: 'França', flag: '🇫🇷' },
      { name: 'Alemanha', flag: '🇩🇪' },
      { name: 'Itália', flag: '🇮🇹' },
      { name: 'Suíça', flag: '🇨🇭' },
      { name: 'Áustria', flag: '🇦🇹' },
      { name: 'Bélgica', flag: '🇧🇪' },
    ],
  },
  reino_unido_nordicos: {
    firstNamesMale: [
      'Oliver',
      'George',
      'Harry',
      'Jack',
      'Jacob',
      'Noah',
      'Charlie',
      'William',
      'Freddie',
      'Oscar',
      'Emil',
      'Rasmus',
      'Elias',
      'Viktor',
      'Lasse',
      'Anton',
      'Kasper',
    ],
    firstNamesFemale: [
      'Olivia',
      'Amelia',
      'Isla',
      'Ava',
      'Freja',
      'Astrid',
      'Maja',
      'Ella',
      'Saga',
      'Linnea',
    ],
    lastNames: [
      'Smith',
      'Jones',
      'Taylor',
      'Brown',
      'Williams',
      'Wilson',
      'Johnson',
      'Davies',
      'Robinson',
      'Wright',
      'Hansen',
      'Johansen',
      'Olsen',
      'Larsen',
      'Andersen',
      'Nilsson',
      'Lindqvist',
      'Berg',
    ],
    nationalities: [
      { name: 'Reino Unido', flag: '🇬🇧' },
      { name: 'Dinamarca', flag: '🇩🇰' },
      { name: 'Suécia', flag: '🇸🇪' },
      { name: 'Noruega', flag: '🇳🇴' },
      { name: 'Finlândia', flag: '🇫🇮' },
    ],
  },
  iberia_latam: {
    firstNamesMale: [
      'Mateo',
      'Santiago',
      'Alejandro',
      'Diego',
      'Nicolas',
      'Matias',
      'Joaquin',
      'Tomas',
      'Pablo',
      'Alvaro',
      'Adrian',
      'Marcos',
      'Javier',
      'Daniel',
    ],
    firstNamesFemale: [
      'Lucia',
      'Martina',
      'Paula',
      'Valeria',
      'Elena',
      'Catalina',
      'Valentina',
      'Camila',
    ],
    lastNames: [
      'Garcia',
      'Rodriguez',
      'Gonzalez',
      'Fernandez',
      'Lopez',
      'Martinez',
      'Sanchez',
      'Perez',
      'Gomez',
      'Martin',
      'Torres',
      'Alvarez',
      'Diaz',
      'Romero',
      'Morales',
    ],
    nationalities: [
      { name: 'Espanha', flag: '🇪🇸' },
      { name: 'Argentina', flag: '🇦🇷' },
      { name: 'México', flag: '🇲🇽' },
      { name: 'Colômbia', flag: '🇨🇴' },
      { name: 'Chile', flag: '🇨🇱' },
      { name: 'Portugal', flag: '🇵🇹' },
    ],
  },
  america_norte: {
    firstNamesMale: [
      'Ethan',
      'Mason',
      'Logan',
      'Aiden',
      'Carter',
      'Wyatt',
      'Colton',
      'Jackson',
      'Hunter',
      'Chase',
    ],
    firstNamesFemale: ['Harper', 'Evelyn', 'Abigail', 'Emily', 'Elizabeth', 'Avery', 'Madison'],
    lastNames: [
      'Miller',
      'Davis',
      'Anderson',
      'Thomas',
      'Moore',
      'Jackson',
      'White',
      'Harris',
      'Clark',
      'Lewis',
    ],
    nationalities: [
      { name: 'Estados Unidos', flag: '🇺🇸' },
      { name: 'Canadá', flag: '🇨🇦' },
    ],
  },
  asia_oceania: {
    firstNamesMale: [
      'Ren',
      'Haruto',
      'Souta',
      'Yuto',
      'Takumi',
      'Kaito',
      'Riku',
      'Hayato',
      'Wei',
      'Hao',
      'Chen',
      'Jun',
      'Min-jun',
      'Seo-jun',
      'Liam',
      'Cooper',
      'Lachlan',
    ],
    firstNamesFemale: ['Yui', 'Aoi', 'Hina', 'Mei', 'Sakura', 'Chloe', 'Zoe', 'Mia'],
    lastNames: [
      'Sato',
      'Suzuki',
      'Takahashi',
      'Tanaka',
      'Watanabe',
      'Ito',
      'Yamamoto',
      'Nakamura',
      'Kobayashi',
      'Wang',
      'Li',
      'Zhang',
      'Kim',
      'Lee',
      'Miller',
      'Kelly',
    ],
    nationalities: [
      { name: 'Japão', flag: '🇯🇵' },
      { name: 'Austrália', flag: '🇦🇺' },
      { name: 'Nova Zelândia', flag: '🇳🇿' },
      { name: 'China', flag: '🇨🇳' },
      { name: 'Coreia do Sul', flag: '🇰🇷' },
    ],
  },
}
