import { CanonicalSponsor, SponsorSector } from '@/types/canonical-commercial'

/**
 * Pool oficial e procedimental de marcas patrocinadoras para o Gerenciador de F1 2026/2027
 * Mistura empresas globais, parceiros técnicos e proceduralmente balanceados.
 */
export const OFFICIAL_SPONSOR_POOL: CanonicalSponsor[] = [
  // Setor Bancário / Financeiro
  {
    sponsorId: 'sp_itau',
    name: 'Itaú Private Motorsport',
    country: 'Brasil',
    region: 'América do Sul',
    sector: 'bancos',
    budgetTier: 'enterprise',
    targetMarkets: ['Brasil', 'América do Sul', 'EUA'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'tradicional',
    riskTolerance: 'conservador',
    performanceExpectation: 'top3',
    contractPreferenceYears: 3,
  },
  {
    sponsorId: 'sp_santander',
    name: 'Santander Premier Global',
    country: 'Espanha',
    region: 'Europa',
    sector: 'bancos',
    budgetTier: 'enterprise',
    targetMarkets: ['Espanha', 'Reino Unido', 'Brasil', 'México'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'campea',
    riskTolerance: 'conservador',
    performanceExpectation: 'top3',
    contractPreferenceYears: 4,
  },
  {
    sponsorId: 'sp_revolut',
    name: 'Revolut Pay Cloud',
    country: 'Reino Unido',
    region: 'Europa',
    sector: 'fintech',
    budgetTier: 'major',
    targetMarkets: ['Reino Unido', 'Europa', 'Austrália'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'arrojado',
    performanceExpectation: 'top5',
    contractPreferenceYears: 2,
  },
  {
    sponsorId: 'sp_nubank',
    name: 'Nubank Ultra',
    country: 'Brasil',
    region: 'América Latina',
    sector: 'fintech',
    budgetTier: 'major',
    targetMarkets: ['Brasil', 'México', 'Colômbia'],
    preferredExposure: 'media',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'moderado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 2,
  },

  // Tecnologia & Software
  {
    sponsorId: 'sp_sap',
    name: 'SAP Enterprise Cloud',
    country: 'Alemanha',
    region: 'Europa',
    sector: 'software',
    budgetTier: 'enterprise',
    targetMarkets: ['Alemanha', 'EUA', 'Mundial'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'campea',
    riskTolerance: 'conservador',
    performanceExpectation: 'top3',
    contractPreferenceYears: 4,
  },
  {
    sponsorId: 'sp_oracle',
    name: 'Apex AI Data Systems',
    country: 'EUA',
    region: 'América do Norte',
    sector: 'tecnologia',
    budgetTier: 'enterprise',
    targetMarkets: ['EUA', 'Europa', 'Japão'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'campea',
    riskTolerance: 'moderado',
    performanceExpectation: 'top3',
    contractPreferenceYears: 3,
  },
  {
    sponsorId: 'sp_crowdstrike',
    name: 'CyberShield Sentinel',
    country: 'EUA',
    region: 'América do Norte',
    sector: 'tecnologia',
    budgetTier: 'major',
    targetMarkets: ['Mundial'],
    preferredExposure: 'media',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'moderado',
    performanceExpectation: 'top5',
    contractPreferenceYears: 2,
  },
  {
    sponsorId: 'sp_lenovo',
    name: 'ThinkEdge Computing',
    country: 'China',
    region: 'Ásia',
    sector: 'tecnologia',
    budgetTier: 'major',
    targetMarkets: ['China', 'EUA', 'Europa', 'Japão'],
    preferredExposure: 'media',
    preferredTeamProfile: 'qualquer',
    riskTolerance: 'moderado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 2,
  },

  // Telecom
  {
    sponsorId: 'sp_claro',
    name: 'Claro 5G Telemetria',
    country: 'México',
    region: 'América Latina',
    sector: 'telecom',
    budgetTier: 'major',
    targetMarkets: ['México', 'Brasil', 'América Latina'],
    preferredExposure: 'media',
    preferredTeamProfile: 'qualquer',
    riskTolerance: 'moderado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 2,
  },
  {
    sponsorId: 'sp_vodafone',
    name: 'Vodafone Enterprise Grid',
    country: 'Reino Unido',
    region: 'Europa',
    sector: 'telecom',
    budgetTier: 'major',
    targetMarkets: ['Reino Unido', 'Alemanha', 'Itália'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'tradicional',
    riskTolerance: 'conservador',
    performanceExpectation: 'top5',
    contractPreferenceYears: 3,
  },

  // Energia & Combustíveis
  {
    sponsorId: 'sp_petrobras',
    name: 'Petrobras Energy & Biocombustíveis',
    country: 'Brasil',
    region: 'América do Sul',
    sector: 'energia',
    budgetTier: 'enterprise',
    targetMarkets: ['Brasil', 'América do Sul', 'Europa'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'moderado',
    performanceExpectation: 'top5',
    contractPreferenceYears: 3,
  },
  {
    sponsorId: 'sp_aramco',
    name: 'Desert Synthetics Energy',
    country: 'Arábia Saudita',
    region: 'Oriente Médio',
    sector: 'energia',
    budgetTier: 'enterprise',
    targetMarkets: ['Oriente Médio', 'Mundial'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'campea',
    riskTolerance: 'conservador',
    performanceExpectation: 'top3',
    contractPreferenceYears: 5,
  },
  {
    sponsorId: 'sp_valeverde',
    name: 'Vale Verde Sustentabilidade',
    country: 'Brasil',
    region: 'América do Sul',
    sector: 'energia',
    budgetTier: 'regional',
    targetMarkets: ['Brasil'],
    preferredExposure: 'baixa',
    preferredTeamProfile: 'qualquer',
    riskTolerance: 'arrojado',
    performanceExpectation: 'livre',
    contractPreferenceYears: 1,
  },

  // Aviação & Logística
  {
    sponsorId: 'sp_embraer',
    name: 'Embraer Aerospace Tech',
    country: 'Brasil',
    region: 'América do Sul',
    sector: 'aviacao',
    budgetTier: 'major',
    targetMarkets: ['Brasil', 'EUA', 'Europa'],
    preferredExposure: 'media',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'moderado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 3,
  },
  {
    sponsorId: 'sp_dhl',
    name: 'FastCargo Global Express',
    country: 'Alemanha',
    region: 'Europa',
    sector: 'logistica',
    budgetTier: 'major',
    targetMarkets: ['Alemanha', 'Mundial'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'tradicional',
    riskTolerance: 'conservador',
    performanceExpectation: 'top5',
    contractPreferenceYears: 3,
  },

  // Moda / Luxo & Bebidas não alcoólicas
  {
    sponsorId: 'sp_tagheuer',
    name: 'Chronos Swiss Precision',
    country: 'Suíça',
    region: 'Europa',
    sector: 'moda_luxo',
    budgetTier: 'major',
    targetMarkets: ['Mundial', 'Suíça', 'Itália', 'Mônaco'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'tradicional',
    riskTolerance: 'conservador',
    performanceExpectation: 'top5',
    contractPreferenceYears: 3,
  },
  {
    sponsorId: 'sp_redbull',
    name: 'HydroCharge Energy Bio',
    country: 'Áustria',
    region: 'Europa',
    sector: 'bebidas_nao_alcoolicas',
    budgetTier: 'enterprise',
    targetMarkets: ['Mundial'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'campea',
    riskTolerance: 'arrojado',
    performanceExpectation: 'top3',
    contractPreferenceYears: 3,
  },

  // Automotivo & Industrial
  {
    sponsorId: 'sp_vipal',
    name: 'Vipal Borrachas Industriais',
    country: 'Brasil',
    region: 'América do Sul',
    sector: 'industrial',
    budgetTier: 'major',
    targetMarkets: ['Brasil', 'América Latina', 'EUA'],
    preferredExposure: 'media',
    preferredTeamProfile: 'tradicional',
    riskTolerance: 'moderado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 2,
  },
  {
    sponsorId: 'sp_pirelli',
    name: 'Apex Tire Technologies',
    country: 'Itália',
    region: 'Europa',
    sector: 'automotivo',
    budgetTier: 'enterprise',
    targetMarkets: ['Itália', 'Mundial'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'qualquer',
    riskTolerance: 'conservador',
    performanceExpectation: 'top5',
    contractPreferenceYears: 4,
  },
  {
    sponsorId: 'sp_bosch',
    name: 'Bosch Mobility Engineering',
    country: 'Alemanha',
    region: 'Europa',
    sector: 'industrial',
    budgetTier: 'enterprise',
    targetMarkets: ['Alemanha', 'Europa', 'EUA', 'Japão'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'conservador',
    performanceExpectation: 'top5',
    contractPreferenceYears: 3,
  },

  // Seguros & Varejo
  {
    sponsorId: 'sp_allianz',
    name: 'Allianz Apex Risk Care',
    country: 'Alemanha',
    region: 'Europa',
    sector: 'seguros',
    budgetTier: 'enterprise',
    targetMarkets: ['Alemanha', 'Europa', 'América Latina'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'tradicional',
    riskTolerance: 'conservador',
    performanceExpectation: 'top3',
    contractPreferenceYears: 4,
  },
  {
    sponsorId: 'sp_mercado_livre',
    name: 'Mercado Livre Express Pay',
    country: 'Argentina',
    region: 'América Latina',
    sector: 'varejo',
    budgetTier: 'major',
    targetMarkets: ['Brasil', 'Argentina', 'México'],
    preferredExposure: 'alta',
    preferredTeamProfile: 'inovadora',
    riskTolerance: 'arrojado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 2,
  },
]

/**
 * Gerador de patrocinadores procedurais/fictícios caso o pool se esgote
 */
export function generateProceduralSponsor(seed: number): CanonicalSponsor {
  const prefixes = [
    'Vortex',
    'Quantum',
    'Aero',
    'Helios',
    'Titan',
    'Nexus',
    'Hyper',
    'Spectra',
    'Omni',
    'Cyber',
  ]
  const suffixes = [
    'Dynamics',
    'Solutions',
    'Systems',
    'Industries',
    'Technologies',
    'Capital',
    'Logistics',
    'Energy',
    'Motorsport',
    'Global',
  ]
  const sectors: SponsorSector[] = [
    'fintech',
    'tecnologia',
    'software',
    'logistica',
    'industrial',
    'energia',
    'automotivo',
  ]
  const countries = ['Brasil', 'Alemanha', 'Reino Unido', 'EUA', 'Japão', 'França', 'Itália']

  const pIdx = Math.abs(seed) % prefixes.length
  const sIdx = Math.abs(seed * 7 + 3) % suffixes.length
  const secIdx = Math.abs(seed * 13 + 5) % sectors.length
  const cIdx = Math.abs(seed * 17 + 11) % countries.length

  const name = `${prefixes[pIdx]} ${suffixes[sIdx]}`
  const sector = sectors[secIdx]
  const country = countries[cIdx]

  return {
    sponsorId: `proc_sp_${Math.abs(seed)}`,
    name,
    country,
    region: country === 'Brasil' ? 'América do Sul' : 'Global',
    sector,
    budgetTier: seed % 2 === 0 ? 'major' : 'regional',
    targetMarkets: [country, 'Mundial'],
    preferredExposure: 'media',
    preferredTeamProfile: 'qualquer',
    riskTolerance: 'moderado',
    performanceExpectation: 'top8',
    contractPreferenceYears: 2,
  }
}
